(ns icare.core
  (:require ["package:flutter/material.dart" :as m]
            ["package:google_fonts/google_fonts.dart" :as gf]
            ["package:flutter/services.dart" :as services]
            [cljd.flutter :as f]
            [icare.ui.ast :refer [state->ast]]
            [icare.ui.build :refer [ast->widget]]
            [icare.resources.state :refer [initialize-state! gather-pub-keys-and-uuids get-user-pub-key get-people-cards]]
            [icare.resources.derived-state :refer [initialize-derived-state!]]
            [icare.resources.network :refer [initialize-network!]]
            [icare.network-events :refer [start-listening!]]
            [icare.resources.storage :refer [initialize-storage!]]))

(defn main []
  (f/run
    (m/MaterialApp
      .title "iCare"
      .theme (m/ThemeData
               .primarySwatch m/Colors.blue
               .textTheme (gf/GoogleFonts.getTextTheme "Playwrite GB J")))
    .home
    (m/Scaffold)
    .body
    ;; (m/AnnotatedRegion
    ;;  .value (services/SystemUiOverlayStyle
    ;;          .systemNavigationBarColor (m/Color 0xFF0a3a07)
    ;;          .systemNavigationBarIconBrightness services/Brightness.light
    ;;          .statusBarColor (m/Color 0xFF0a3a07)
    ;;          .statusBarIconBrightness services/Brightness.light))
    (m/SafeArea)
    (m/FutureBuilder
     .future (initialize-storage!)
     .initialData nil)
    .builder
    (fn [_ ^m/AsyncSnapshot snapshot]
      (cond
        (= m/ConnectionState.done (.-connectionState snapshot))
        (let [[private-key public-key persisted-state] (.-data snapshot)
              store (initialize-state! public-key persisted-state)
              state @store
              people-cards (get-people-cards state)
              {:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids state)
              user-pub-key (get-user-pub-key state)]
          (initialize-derived-state! people-cards)
          (.then (initialize-network! private-key)
                 (fn [ws] (start-listening! ws user-task-uuids friend-pub-keys user-pub-key)))
          (f/widget
           :watch [state store]
           (-> state                   ;;state is the end-user representation of the app
               state->ast              ;;ui is the programmers representation of the app
               ast->widget)))          ;;widgets are the machine representation of the app

        :else
        (m/Text "Loading...")))))
