(ns icare.network-events
  (:require ["package:nostr/nostr.dart" :refer [Event]]
            ["dart:convert" :refer [jsonDecode]]
            [cljd.edn :refer [read-string]]
            [icare.resources.glue :refer [update-state-and-persist!]]
            [icare.ui.glue :refer [render-ui!]]))

(def send-updated-task-kind 39505)
(def liked-event-kind 39506)
(def update-request-to-notify-kind 39507)
(def fulfill-notify-kind 29508) ;;a 2 here is a nostr convention that means that this kind is ephemeral and should not be stored by the relay

;;This module handles incoming websocket events.
;;It parses incoming messages and updates state + storage directly.

(defn handle-event! [data]
  (try
    (let [subscription-id (get data 1)
          event-json (get data 2)
          event ^Event (.fromJson Event event-json)] ;;this will automatically verify the event signature, if invalid it will throw
      (condp = (.-kind event)
        update-request-to-notify-kind
        (let [content (read-string (.-content event))
              task-uuid (:task-uuid content)
              want-notifications? (:want-notifications? content)
              notification-requester (.-pubkey event)]
          (update-state-and-persist! {:type :update-notify-requesters :want-notifications? want-notifications?
                                      :task-uuid task-uuid :notification-requester notification-requester
                                      :event-json event-json})
          (prn "Received request to notify event:" (.-content event) "with tags:" (.-tags event)))

        ;; liked-event-kind
        ;; (let [content (read-string (.-content event))
        ;;       task-uuid (:task-uuid content)
        ;;       liked (:liked content)
        ;;       creator-pub-key (.-pubkey event)]
        ;;   (update-state-and-persist! {:type :liked-event :liked liked
        ;;                               :task-uuid task-uuid :creator-pub-key creator-pub-key})
        ;;   (prn "Received liked event:" (.-content event) "with tags:" (.-tags event)))

        send-updated-task-kind
        (let [task-data (read-string (.-content event))
              creator-pub-key (.-pubkey event)]
          (when-not (nil? task-data)
            (update-state-and-persist! {:type :update-task-event :task task-data
                                        :creator-pub-key creator-pub-key})
            (prn "Received update task event:" task-data "with tags:" (.-tags event))))

        (prn "Unhandled event kind:" (.-kind event) "with content:" (.-content event))))
    (catch Exception e
      (prn "Event message from server does not comply to either NIP01 or my custom protocol:" e))))

(defn handle-ok [data]
  (try
    (let [request-id (get data 1)
          accepted (get data 2)
          message (get data 3)]
      (if accepted
        (prn "Request" request-id "was accepted by server:" (if-not (empty? message)
                                                              message "No message"))
        (prn "Request" request-id "was rejected by server:" (if-not (empty? message)
                                                              message "No message"))))
    (catch Exception e
      (prn "Ok message from server does not comply to NIP01:" e))))

(defn handle-network-data! [data]
  (try
    (let [data (jsonDecode data)]
      (condp = (get data 0)
        "OK" (handle-ok data)
        "EVENT" (handle-event! data)
        "EOSE" nil
        "NOTICE" nil
        (prn "Unhandled WebSocket message:" data)))
    (catch Exception e
      (prn "Websocket message is not a json object" e))))
