(ns icare.network-events
  (:require ["package:nostr/nostr.dart" :refer [Event]]
            ["dart:convert" :refer [jsonDecode]]
            [cljd.edn :refer [read-string]]
            [icare.resources.utils :refer [update-state-and-persist!]]))
;;If you require icare.resources.network here you will cause a cyclic dependancy. Therefore, incoming network events can't
;;be resolved by sending out another network event. If you think an incoming network event should be resolved by an outbound network event
;;consider another solution before refactoring. BTW, the simplest way to refactor this to make that issue
;;work is by deleting this file and moving the contents to network.cljd

(def liked-event-kind 39506)
(def update-task-event-kind 39505)

;;This module handles incoming websocket events.
;;It parses incoming messages and updates state + storage directly.

(defn handle-event! [data]
  (try
    (let [subscription-id (get data 1)
          event-json (get data 2)
          event ^Event (.fromJson Event event-json)]
      (condp = (.-kind event)
        liked-event-kind
        (let [content (read-string (.-content event))
              task-uuid (:task-uuid content)
              liked (:liked content)
              creator-pub-key (.-pubkey event)]
          (update-state-and-persist! {:type :liked-event :liked liked
                                      :task-uuid task-uuid :creator-pub-key creator-pub-key})
          (prn "Received liked event:" (.-content event) "with tags:" (.-tags event)))

        update-task-event-kind
        (let [task-data (read-string (.-content event))
              creator-pub-key (.-pubkey event)]
          (when-not (nil? task-data)
            (update-state-and-persist! {:type :update-task-event :task task-data
                                        :creator-pub-key creator-pub-key})
            (prn "Received update task event:" task-data "with tags:" (.-tags event))))

        (prn "Unhandled event kind:" (.-kind event) "with content:" (.-content event))))
    (catch Exception e
      (prn "Event message from server does not comply to either NIP01 or my custom protocol:" e))))

(defn handle-ok [data]
  (try
    (let [request-id (get data 1)
          accepted (get data 2)
          message (get data 3)]
      (if accepted
        (prn "Request" request-id "was accepted by server:" (if-not (empty? message)
                                                              message "No message"))
        (prn "Request" request-id "was rejected by server:" (if-not (empty? message)
                                                              message "No message"))))
    (catch Exception e
      (prn "Ok message from server does not comply to NIP01:" e))))

(defn handle-network-data! [data]
  (try
    (let [data (jsonDecode data)]
      (condp = (get data 0)
        "OK" (handle-ok data)
        "EVENT" (handle-event! data)
        "EOSE" nil
        "NOTICE" nil
        (prn "Unhandled WebSocket message:" data)))
    (catch Exception e
      (prn "Websocket message is not a json object" e))))
