(ns icare.state
  (:require ["package:uuid/uuid.dart" :refer [Uuid]]))

(def uuid-generator (.-v4 (Uuid)))


;;This namespace defines all side effects on our store
;;
(defonce initialized? (atom false))

(defonce store (atom {:reorderable-items [{:type :user
                                           :name "Me"
                                           :pub-key nil
                                           :tasks [{:title "wake up"
                                                    :uuid (uuid-generator)
                                                    :completed false
                                                    :liked-by #{1}
                                                    :subitems []}
                                                   {:title "go to monkey bars"
                                                    :uuid (uuid-generator)
                                                    :completed true
                                                    :liked-by #{}
                                                    :subitems [{:type :time :value "2026-01-06 09:18:04Z"}
                                                               {:type :image :value "https://www.adventuretoys.co.uk/images/product/27695monkeybarattach.jpg"}]}]}
                                          {:type :friend
                                           :name "Jun"
                                           :pub-key "b5bff73132049a564cb588dad986a2acc31fa52c07bbecd991237b8cb9c2fa3b"
                                           :tasks [{:title "Defeated bear"
                                                    :uuid (uuid-generator)
                                                    :liked false
                                                    :completed false
                                                    :subitems []}
                                                   {:title "go to sleep"
                                                    :uuid (uuid-generator)
                                                    :liked false
                                                    :completed true
                                                    :subitems [{:type :time :value "2026-01-06 21:18:04Z"}]}
                                                   {:title "went for walk"
                                                    :uuid (uuid-generator)
                                                    :liked false
                                                    :completed true
                                                    :subitems [{:type :time :value "2026-01-06 14:25:04Z"}
                                                               {:type :image :value "https://media.bizj.us/view/img/10481361/ext-nw-corner-building-copy*900xx3840-2160-0-0.jpg"}]}]}
                                          {:type :friend-search}]
                      :undo-redo {:x 240 :y 700}}))

;;Helper functions. Read only operations.

(defn friend-search-at-bottom? [reorderable-items]
  (= :friend-search (:type (last reorderable-items))))

(defn get-pub-to-name-map []
  (let [reorderable-items (:reorderable-items @store)]
    (into {}
          (->> reorderable-items
               (filter #(#{:friend :user} (:type %)))
               (map (juxt :pub-key :name))))))

(defn get-person-task-uuids [person]
  (let [{:keys [tasks]} person]
    (mapv (fn [task] (:uuid task)) tasks)))

(defn gather-pub-keys-and-uuids []
  (let [reorderable-items (:reorderable-items @store)]
    (reduce
     (fn [acc reorderable-item]
       (condp = (:type reorderable-item)
         :user (assoc acc :user-task-uuids (get-person-task-uuids reorderable-item))
         :friend (update acc :friend-pub-keys conj (:pub-key reorderable-item))
         acc))
     {:user-task-uuids nil
      :friend-pub-keys []}
     reorderable-items)))

(defn get-user-pub-key []
  (let [reorderable-items (:reorderable-items @store)]
    (->> reorderable-items
         (filter #(= :user (:type %)))
         first
         :pub-key)))

(defn get-reorderable-item-idx-by-predicate [reorderable-items predicate]
  (->> reorderable-items
       (map vector (range))
       (filter (fn [[idx item]] (predicate item)))
       first
       ((fn [[idx item]] idx))))

(defn uuid->task-idx [tasks task-uuid]
  (get-reorderable-item-idx-by-predicate tasks #(= (:uuid %) task-uuid)))

(defn pub-key->reorderable-item-idx [reorderable-items pub-key]
  (get-reorderable-item-idx-by-predicate
   reorderable-items
   #(= (:pub-key %) pub-key)))

(defn get-user-reorderable-item-idx [reorderable-items]
  (get-reorderable-item-idx-by-predicate
   reorderable-items
   #(= (:type %) :user)))

;;
;;DISPATCH HANDLERS
;;
;;

;;TODO we need to something about events coming through the network
;;so that we can batch them. Not neccessary now.
;;network event handler
(defn handle-liked-event [state event]
  (let [{:keys [liked task-uuid creator-pub-key]} event
        user-card-idx (get-user-reorderable-item-idx (:reorderable-items state))
        task-idx (uuid->task-idx
                  (get-in state [:reorderable-items user-card-idx :tasks])
                  task-uuid)]
    (if liked
      (update-in state
                [:reorderable-items user-card-idx :tasks task-idx :liked-by]
                conj creator-pub-key)
      (update-in state
                [:reorderable-items user-card-idx :tasks task-idx :liked-by]
                disj creator-pub-key))))

;;network event handler
(defn handle-update-task-event [state event]
  (let [{:keys [task task-uuid creator-pub-key]} event
        card-idx (pub-key->reorderable-item-idx
                   (:reorderable-items state)
                   creator-pub-key)
        task-idx (uuid->task-idx
                  (get-in state [:reorderable-items card-idx :tasks])
                  task-uuid)]
    (cond
      (nil? card-idx) state ;;we don't have this person yet
      (nil? task-idx) (update-in state ;;new task
                                [:reorderable-items card-idx :tasks]
                                conj task)
      :else (assoc-in state ;;update existing task
                      [:reorderable-items card-idx :tasks task-idx]
                      task))))

(defn handle-complete-user-task[state event]
  (let [{:keys [user-card-idx task-idx completed creator-pub-key]} event]
    (update-in state [:reorderable-items user-card-idx :tasks task-idx]
           (fn [task]
             (let [new-task (assoc task :completed completed)]
               (cond (and (not completed)
                          (seq (:subitems new-task))
                          (-> (:subitems new-task) first :type (= :time)))
                     (update new-task
                             :subitems subvec 1)
                     completed
                     (update new-task
                             :subitems #(apply vector {:type :time
                                                       :value (.toIso8601String (DateTime/now))} %))
                     :else new-task))))))

(defn handle-delete-user-task [state event]
  (let [{:keys [user-card-idx task-idx]} event]
    (update-in state [:reorderable-items user-card-idx :tasks]
               (fn [tasks] (vec (concat (subvec tasks 0 task-idx)
                                        (subvec tasks (inc task-idx))))))))

(defn handle-rename-user-task [state event]
  (let [{:keys [user-card-idx task-idx title]} event]
    (assoc-in state
              [:reorderable-items user-card-idx :tasks task-idx :title]
              title)))

(defn handle-like-friend-task [state event]
  (let [{:keys [friend-card-idx task-idx liked]} event]
    (assoc-in state
              [:reorderable-items friend-card-idx :tasks task-idx :liked]
              liked)))

(defn handle-add-user-task [state event]
  (let [{:keys [user-card-idx new-task]} event]
    (update-in state
               [:reorderable-items user-card-idx :tasks]
               conj new-task)))

(defn handle-delete-card [state event]
  (let [{:keys [card-idx]} event]
    (update state :reorderable-items
            (fn [items]
              (vec (concat (subvec items 0 card-idx)
                           (subvec items (inc card-idx))))))))
(defn handle-rename-card [state event]
  (let [{:keys [card-idx name]} event]
    (assoc-in state
              [:reorderable-items card-idx :name]
              name)))

(defn handle-add-friend [state event]
  (let [{:keys [pub-key]} event]
    (if-not (empty? pub-key)
      (update state :reorderable-items
              (fn [items]
                (let [new-friend {:type :friend
                                  :pub-key pub-key ;;obviously this is wrong TODO
                                  :name pub-key ;;obviously this is wrong TODO
                                  :tasks []}]
                  (if (friend-search-at-bottom? items)
                    (vec (concat (subvec items 0 (dec (count items)))
                                 [new-friend]
                                 (subvec items (dec (count items)))))
                    (conj items new-friend)))))
      state)))

(defn handle-reorder-items [state event]
  (let [{:keys [from-index to-index]} event]
    (update state :reorderable-items
            (fn [items]
              (vec
                (if (< from-index to-index)
                  (concat (subvec items 0 from-index)
                          (subvec items (inc from-index) (inc to-index))
                          [(nth items from-index)]
                          (subvec items (inc to-index)))
                  (concat (subvec items 0 to-index)
                          [(nth items from-index)]
                          (subvec items to-index from-index)
                          (subvec items (inc from-index)))))))))

(defn handle-move-undo-redo [state event]
  (let [{:keys [dx dy]} event]
    (update-in state [:undo-redo]
               (fn [undo-redo]
                 (let [{:keys [x y]} undo-redo]
                   {:x (+ x dx)
                    :y (+ y dy)})))))

(defn apply-state-event [state event]
  (condp = (:type event)
    :liked-event (handle-liked-event state event)
    :update-task-event (handle-update-task-event state event)
    :complete-user-task (handle-complete-user-task state event)
    :delete-user-task (handle-delete-user-task state event)
    :rename-user-task (handle-rename-user-task state event)
    :like-friend-task (handle-like-friend-task state event)
    :add-user-task (handle-add-user-task state event)
    :delete-card (handle-delete-card state event)
    :rename-card (handle-rename-card state event)
    :add-friend (handle-add-friend state event)
    :reorder-items (handle-reorder-items state event)
    :move-undo-redo (handle-move-undo-redo state event)
    (throw (Exception (str "No dispatch function found for event: " event)))))

;;TODO
;;at some point I'll have to implement event batching
;;To do that, disptach network events should queue events
;;then we have to write a flush function that clears the
;;queue and runs swap! store (reduce #(... appply-network-event acc event) state queue)
;;We should be careful about when to run this flush since we want to be fairly responsive...
;;but you'll get the idea
(defn dispatch! [event]
  (if-not @initialized?
    (throw (Exception. "State store not initialized yet! Call initialize-state! from core first."))
    (swap! store apply-state-event event)))

(defn update-user-pub-key! [pub-key]
  (swap! store update :reorderable-items
         (fn [items]
           (let [user-idx (get-user-reorderable-item-idx items)]
             (assoc-in items [user-idx :pub-key] pub-key)))))

;;Call this function from core, this is the intended way to get a reference to the store
(defn initialize-state! [pub-key]
  (prn "Initializing state with pub key:" pub-key)
  (reset! initialized? true)
  (update-user-pub-key! pub-key)
  store)

;;TODO derived state caching?
;;things like pub-key->name list of friend pub keys ...
;;although let's worry about the derived state performance issue when I actually start to get
;;performance issues
