(ns icare.state
  (:require ["package:flutter/material.dart" :as m]
            [cljd.flutter :as f]))

(def store (atom {:reorderable-items [{:type :user
                                       :name "Me"
                                       :pub-key nil
                                       :tasks [{:title "wake up"
                                                :uuid 0
                                                :completed false
                                                :subitems []}
                                               {:title "go to monkey bars"
                                                :uuid 1
                                                :completed true
                                                :subitems [{:type :time :value "2026-01-06 09:18:04Z"}
                                                           {:type :image :value "https://www.adventuretoys.co.uk/images/product/27695monkeybarattach.jpg"}]}]}
                                      {:type :friend
                                       :name "Jun"
                                       :pub-key 1
                                       :tasks [{:title "Defeated bear"
                                                :uuid 2
                                                :liked false
                                                :completed false
                                                :subitems []}
                                               {:title "go to sleep"
                                                :uuid 3
                                                :liked false
                                                :completed true
                                                :subitems [{:type :time :value "2026-01-06 21:18:04Z"}]}
                                               {:title "went for walk"
                                                :uuid 4
                                                :liked false
                                                :completed true
                                                :subitems [{:type :time :value "2026-01-06 14:25:04Z"}
                                                           {:type :image :value "https://media.bizj.us/view/img/10481361/ext-nw-corner-building-copy*900xx3840-2160-0-0.jpg"}]}]}
                                      {:type :friend-search}]
                  :undo-redo {:x 240 :y 700}}))

(defn get-reorderable-item-idx-by-predicate [reorderable-items predicate]
  (->> reorderable-items
       (map vector (range))
       (filter (fn [[idx item]] (predicate item)))
       first
       ((fn [[idx item]] idx))))

(defn pub-key->reorderable-item-idx [reorderable-items pub-key]
  (get-reorderable-item-idx-by-predicate
   reorderable-items
   #(= (:pub-key %) pub-key)))

(defn get-user-reorderable-item-idx [reorderable-items]
  (get-reorderable-item-idx-by-predicate
   reorderable-items
   #(= (:type %) :user)))

(defn update-user-pub-key! [store pub-key]
  (swap! store update :reorderable-items
         (fn [items]
           (let [user-idx (get-user-reorderable-item-idx items)]
             (assoc-in items [user-idx :pub-key] pub-key)))))

(defn friend-search-at-bottom? [reorderable-items]
  (= :friend-search (:type (last reorderable-items))))

(defn task-subitems->ui [subitem]
  (let [{:keys [type value]} subitem]
    (cond
      (= type :time) {:ui-type :subitem-time :time value}
      (= type :image) {:ui-type :subitem-image :url value}
      :else (throw (Exception. (str "task-subitems->ui was given a task subitem with unknown type: " type))))))

(defn user-task->ui [task-idx task]
  (let [{:keys [title completed subitems reorderable-item-idx]} task]
    {:ui-type :editable-task
     :title title
     :on-complete (fn [store]
                    (fn []
                      (swap! store update-in [:reorderable-items reorderable-item-idx :tasks task-idx]
                             (fn [task]
                               (let [new-task (assoc task :completed (not completed))]
                                 (cond (and completed
                                            (seq (:subitems new-task))
                                            (-> (:subitems new-task) first :type (= :time)))
                                       (update new-task
                                               :subitems subvec 1)
                                       (not completed)
                                       (update new-task
                                               :subitems #(apply vector {:type :time
                                                                         :value (.toIso8601String (DateTime/now))} %))
                                       :else new-task))))))
     :on-edit-task-title (fn [store]
                           (fn [value]
                             (if (empty? value)
                               (swap! store update-in [:reorderable-items reorderable-item-idx :tasks]
                                      (fn [tasks] (vec (concat (subvec tasks 0 task-idx)
                                                               (subvec tasks (inc task-idx))))))
                               (swap! store assoc-in
                                      [:reorderable-items reorderable-item-idx :tasks task-idx :title] value))))


     :completed completed
     :subitems (mapv task-subitems->ui subitems)}))

(defn friend-task->ui [task-idx task]
  (let [{:keys [title completed liked subitems reorderable-item-idx]} task]
    {:ui-type :ronly-task
     :title title
     :completed completed
     :on-liked (fn [store]
                 (fn []
                   (swap! store assoc-in [:reorderable-items reorderable-item-idx :tasks task-idx :liked]
                          (not liked))))

     :liked liked
     :subitems (mapv task-subitems->ui subitems)}))

(defn add-tasks->ui [reorderable-item-idx]
  {:ui-type :add-task-area
   :on-add-task (fn [store ^m/TextEditingController text-controller random-hex-generator]
                  (fn [value]
                    (.clear text-controller)
                    (when (not (empty? value))
                      (swap! store update-in
                             [:reorderable-items reorderable-item-idx :tasks]
                             conj {:title value
                                   :uuid (random-hex-generator)
                                   :completed false
                                   :subitems []}))))})

(defn person->ui [reorderable-item-idx person]
  (let [{:keys [user? name tasks pub-key]} person
        tasks (mapv #(conj % {:reorderable-item-idx reorderable-item-idx}) tasks)]
    {:ui-type :task-card
     :initially-expanded user?
     :add-tasks? user?
     :key pub-key
     :title name
     :on-rename-title (fn [store]
                        (fn [value]
                          (if (empty? value)
                            (swap! store update :reorderable-items
                                   (fn [items]
                                     (vec (concat (subvec items 0 reorderable-item-idx)
                                                  (subvec items (inc reorderable-item-idx))))))
                            (swap! store assoc-in [:reorderable-items reorderable-item-idx :name] value))))
     :tasks (if user?
              (conj (mapv user-task->ui (range) tasks) (add-tasks->ui reorderable-item-idx))
              (mapv friend-task->ui (range) tasks))}))

(defn friend-search->ui []
  {:ui-type :friend-search-area
   :on-search (fn [store ^m/TextEditingController text-controller]
                (fn [value]
                  (.clear text-controller)
                  (when (not (empty? value))
                    (swap! store update :reorderable-items
                           (fn [items]
                             (let [new-friend {:type :friend
                                               :pub-key value ;;obviously this is wrong TODO
                                               :name value
                                               :tasks []}]
                               (if (friend-search-at-bottom? items)
                                 (vec (concat (subvec items 0 (dec (count items)))
                                              [new-friend]
                                              (subvec items (dec (count items)))))
                                 (conj items new-friend))))))))})

(defn list-item->ui [reorderable-item-idx item]
  (let [{:keys [type]} item]
    (cond
      (= type :user) (person->ui reorderable-item-idx (conj item {:user? true}))
      (= type :friend) (person->ui reorderable-item-idx (conj item {:user? false}))
      (= type :friend-search) (friend-search->ui)
      :else (throw (Exception. (str "list-item->ui was given a list item with unknown type: " type))))))

(defn reorderable-list->ui [reorderable-items]
  {:ui-type :reorderable-list
   :on-reorder (fn [store]
                 (fn [from-index to-index]
                   (let [[from-index to-index] (if (< from-index to-index)
                                                 [from-index (dec to-index)]
                                                 [from-index to-index])
                         reorder-state-list (fn [state]
                                              (update state :reorderable-items
                                                      (fn [items]
                                                        (vec
                                                          (if (< from-index to-index)
                                                            (concat (subvec items 0 from-index)
                                                                    (subvec items (inc from-index) (inc to-index))
                                                                    [(nth items from-index)]
                                                                    (subvec items (inc to-index)))
                                                            (concat (subvec items 0 to-index)
                                                                    [(nth items from-index)]
                                                                    (subvec items to-index from-index)
                                                                    (subvec items (inc from-index))))))))]
                     (swap! store reorder-state-list))))

   :items (mapv list-item->ui (range) reorderable-items)})

(defn undo-redo->ui [undo-redo]
  (let [{:keys [x y]} undo-redo]
    {:ui-type :undo-redo-area
     :x x
     :y y
     :on-move (fn [store]
                (fn [^m/DragUpdateDetails details]
                  (let [new-position (.-delta details)
                        {:flds [dx dy]} new-position]
                    (swap! store update :undo-redo
                           (fn [{:keys [x y]}]
                             {:x (+ x dx) :y (+ y dy)})))))

     :on-undo identity
     :on-redo identity}))

(defn state->ui [state]
  (let [{:keys [undo-redo reorderable-items]} state]
    {:ui-type :screen-base
     :undo-redo (undo-redo->ui undo-redo) ;
     :reorderable-list (reorderable-list->ui reorderable-items)}))
