(ns icare.ui-events
  (:require [icare.resources.network :refer [dispatch!] :rename {dispatch! network-dispatch!}]
            [icare.resources.storage :refer [dispatch!] :rename {dispatch! storage-dispatch!}]
            [icare.resources.state
             :refer [dispatch! get-task-by-indexes gather-pub-keys-and-uuids get-device-token get-new-task get-updated-task get-open-list
                     diff-lists get-updated-list is-empty-list?]
             :rename {dispatch! state-dispatch!}]
            [icare.resources.glue :refer [update-state-and-persist!]]
            [icare.ui.glue :refer [render-ui!]]
            ["package:firebase_messaging/firebase_messaging.dart" :as firebase-messaging]))

;;UI event handler for events triggered by user interactions.
;;Coordinates state updates, storage persistence, and outbound network messages.
;;UI event callbacks are defined in ast.cljd and passed to widgets in build.cljd.
;;
(defn update-state-render-and-persist! [event]
  (let [db (update-state-and-persist! event)]
    (render-ui! db)
    db))

(defonce list-snapshot (atom nil))

(defn handle-ui-event! [event]
  (let [{:keys [type]} event]
    (condp = type
     :complete-user-task
     (let [db (update-state-render-and-persist! event)
           updated-task (get-task-by-indexes (:state db) (:user-card-idx event) (:task-idx event))
           task-uuid (:uuid updated-task)
           receipts (get-in db [:notify-receipts task-uuid])]
       (network-dispatch! {:type :send-updated-task
                           :task updated-task
                           :deleted false})
       (when (and (:completed event) receipts)
         (doseq [[requester-pub-key event-json] receipts]
           (network-dispatch! {:type :fulfill-notify
                               :to-pub-key requester-pub-key
                               :notify-receipt event-json
                               :notification-content {:title (:title updated-task)
                                                      :body "Was completed"}})))) ;;TODO we want better messages such as x completed y, for this we want the notification receipt to include the task title and the user name

     :delete-user-task
     (do
       (update-state-render-and-persist! event)
       (network-dispatch! {:type :send-updated-task
                           :deleted true
                           :task (:task event)}))

     :rename-user-task
     (let [db (update-state-render-and-persist! event)
           updated-task (get-task-by-indexes (:state db) (:user-card-idx event) (:task-idx event))]
       (network-dispatch! {:type :send-updated-task
                           :deleted false
                           :task updated-task}))

     :like-friend-task
     (do
       (let [messaging (firebase-messaging/FirebaseMessaging.instance)
             settings (await (.getNotificationSettings messaging))
             status (.-authorizationStatus settings)]
         (when (= status firebase-messaging/AuthorizationStatus.provisional)
           ;;This is the first time the user is liking a task, we want to upgrade permissions from provisional to full
           ;;TODO we want to show a message here explaining why we want notification permission before we prompt
           (await (.requestPermission messaging
                     .alert true
                     .announcement true
                     .badge true
                     .carPlay false
                     .criticalAlert false
                     .provisional false
                     .sound true)))
        ;;sometimes we fail to get token on startup. This could also return nil so maybe we want to handle that case better
        (prn (get-device-token))
        (when-not (get-device-token)
          (let [token (await (-> (.getToken messaging)
                                 (.catchError (fn [e]
                                                (prn "Failed to get device token: " e)
                                                nil))))
                db (state-dispatch! {:type :update-device-token :device-token token})]
            (storage-dispatch! {:type :state-change-event :new-state (:state db)}))))
       ;;this breaks atomicity, but I don't think there can be a race condition because of how flutter handles ui callbacks on the same thread.
       (update-state-render-and-persist! event)
       (network-dispatch! {:type :update-request-to-notify
                           :want-notifications? (:want-notifications? event)
                           :to-pub-key (:creator-pub-key event)
                           :task-uuid (:task-uuid event)}))

     :add-user-task
     (let [db (update-state-render-and-persist! event)
           new-task (get-task-by-indexes (:state db) (:user-card-idx event) (:task-idx event))
           {:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids (:state db))
           user-pub-key (:user-pub-key (:derived-state db))]
       (network-dispatch! {:type :send-updated-task
                           :deleted false
                           :task new-task})
       (network-dispatch! {:type :update-notify-requests-subscription
                           :user-pub-key user-pub-key
                           :user-task-uuids user-task-uuids
                           :friend-pub-keys friend-pub-keys}))

     :delete-card
     (let [db (update-state-render-and-persist! event)
           {:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids (:state db))
           user-pub-key (:user-pub-key (:derived-state db))]
       (network-dispatch! {:type :update-friend-tasks-subscription
                           :friend-pub-keys friend-pub-keys})
       (network-dispatch! {:type :update-notify-requests-subscription
                           :user-pub-key user-pub-key
                           :user-task-uuids user-task-uuids
                           :friend-pub-keys friend-pub-keys}))

     :add-friend
     (update-state-render-and-persist! event)

     :initialize-friend
     (let [db (update-state-render-and-persist! event)
           {:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids (:state db))
           user-pub-key (:user-pub-key (:derived-state db))]
       (network-dispatch! {:type :update-friend-tasks-subscription
                           :friend-pub-keys friend-pub-keys})
       (network-dispatch! {:type :update-notify-requests-subscription
                           :user-pub-key user-pub-key
                           :user-task-uuids user-task-uuids
                           :friend-pub-keys friend-pub-keys}))

     :delete-uninitialized-card
     (update-state-render-and-persist! event)

     :rename-uninitialized-card-friend
     (update-state-render-and-persist! event)

     :rename-uninitialized-card-self
     (update-state-render-and-persist! event)

     :rename-card
     (update-state-render-and-persist! event)

     :task-notification-finishes
     (update-state-render-and-persist! event)

     :card-expansion
     (update-state-render-and-persist! event)

     :reorder-items
     (update-state-render-and-persist! event)

     :send-friend-request
     (update-state-render-and-persist! event)

     :toggle-wobble
     (let [db (state-dispatch! event)]
       (render-ui! db))

     :toggle-handshake-qr ;;just showing a qr code, no need to persist state
     (let [db (state-dispatch! event)]
       (render-ui! db))

     :toggle-handshake-network
     (let [db (state-dispatch! event)]
       (render-ui! db))

     ;;shared ui-events
     :navigate
     (update-state-render-and-persist! event)

     ;;--- Home.todo-list page events
     :rename-list
     (update-state-render-and-persist! event)

     :edit-list-asset
     (update-state-render-and-persist! event)

     :reorder-asset-list
     (update-state-render-and-persist! event)

     ;;--- Home page events
     :icon-expansion-toggle
     (let [db (as-> (state-dispatch! event) db
                (or (when-let [snapshot @list-snapshot]
                      (reset! list-snapshot nil)
                      (let [{:keys [added removed modified new-title new-asset]} (diff-lists snapshot (get-updated-list db (:list-idx event)))]
                        (when (or (seq added) (seq removed) (seq modified) new-title new-asset)
                          ;;we want to send batched network events here and count the number of changes to keep track of commit logs
                          (when (is-empty-list? snapshot)
                            (prn "Modified an empty-list")
                            (state-dispatch! {:type :add-list
                                              :list-idx (:list-idx event)})))))
                    db))]
       (when-let [expanded-list (get-open-list db)]
         (reset! list-snapshot expanded-list))
       (storage-dispatch! {:type :state-change-event :new-state (:state db)})
       (render-ui! db))

     :add-list
     (update-state-render-and-persist! event)

     :reorder-icons
     (update-state-render-and-persist! event)

     :reorder-tasks
     (update-state-render-and-persist! event)

     :complete-task
     (let [db (update-state-render-and-persist! event)
           updated-task (get-updated-task db (:task-idx event) (:list-idx event))
           task-uuid (:uuid updated-task)
           receipts (get-in db [:notify-receipts task-uuid])]
       (network-dispatch! {:type :send-updated-task
                           :task updated-task
                           :deleted false})
       (when (and (:completed event) receipts)
         (doseq [[requester-pub-key event-json] receipts]
           (network-dispatch! {:type :fulfill-notify
                               :to-pub-key requester-pub-key
                               :notify-receipt event-json
                               :notification-content {:title (:title updated-task)
                                                      :body "Was completed"}}))))

     :delete-task
     (do
       (update-state-render-and-persist! event)
       (network-dispatch! {:type :send-updated-task
                           :deleted true
                           :task (:task event)}))

     :rename-task
     (let [db (update-state-render-and-persist! event)]
       (network-dispatch! {:type :send-updated-task
                           :deleted false
                           :task (get-updated-task db (:task-idx event) (:list-idx event))}))

     :add-task
     (let [db (update-state-render-and-persist! event)]
       (network-dispatch! {:type :send-updated-task
                           :deleted false
                           :task (get-new-task db (:task-idx event) (:list-idx event))}))

     (throw (Exception (str "Unknown event type in ui-events dispatch: " event))))))
