(ns icare.ui.screens.qr
  (:require ["package:flutter/material.dart" :as m]
            ["package:flutter_svg/flutter_svg.dart" :as svg]
            ["package:qr_flutter/qr_flutter.dart" :as qr]
            ["package:share_plus/share_plus.dart" :as share]
            ["package:haptic_feedback/haptic_feedback.dart" :as haptics]
            ["dart:ui" :as ui]
            ["dart:math" :as math]
            [cljd.flutter :as f]))

;;TODO this is just a placeholder
(defn state->ast [db]
  (let [{:keys [derived-state state]} db]
    {:id "root"
     :ui-type :root}))

(defn ast-store->widget
  ([ast-store handle-ui-event!] (ast-store->widget handle-ui-event! ast-store @(get @ast-store "root")))
  ([handle-ui-event! ast-store {:keys [ui-type id] :as ui}]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store @(get @ast-store ast-id)))
         get-ast-atom (fn [] (get @ast-store id))
         {:keys [key]} @(get-ast-atom)]
     (condp = ui-type
       :root))))
