(ns icare.ui.shared.paint
  (:require ["package:flutter/material.dart" :as m]
            ["dart:ui" :as ui]
            ["package:flutter/rendering.dart" :as rendering]
            ["dart:math" :refer [pi]]
            [cljd.flutter :as f]))

(defn hsv
  ([hue saturation value] (.toColor (m/HSVColor.fromAHSV 1 hue saturation value)))
  ([alpha hue saturation value] (.toColor (m/HSVColor.fromAHSV alpha hue saturation value))))

(defn debug-border [.child .color]
  (m/Container
   .decoration (m/BoxDecoration
                .border (m/Border.all .color (if color color m/Colors.red) .width 2))
   .child child))

(defn glass-border-painter [r]
  (reify :extends m/CustomPainter
    (paint [_ canvas size]
      (let [hi 0.9
            mid 0.7
            lo 0.4
            stroke 1.35
            half (/ stroke 2.0)
            rect (ui/Rect.fromLTWH half half
                   (- (.-width size) stroke)
                   (- (.-height size) stroke))
            rrect (ui/RRect.fromRectAndRadius rect
                    (ui/Radius.circular (- r half)))
            grad (m/SweepGradient
                  .startAngle 0.0
                  .endAngle (* 2.0 pi)
                  .colors [(m/Colors.white.withOpacity lo) (m/Colors.white.withOpacity lo)
                           (m/Colors.white.withOpacity hi) (m/Colors.white.withOpacity hi)
                           (m/Colors.white.withOpacity mid)
                           (m/Colors.white.withOpacity lo) (m/Colors.white.withOpacity lo)
                           (m/Colors.white.withOpacity hi) (m/Colors.white.withOpacity hi)
                           (m/Colors.white.withOpacity mid)
                           (m/Colors.white.withOpacity lo) (m/Colors.white.withOpacity lo)]
                  .stops [0.00 0.02
                          0.035 0.336
                          0.37 0.414
                          0.561 0.585
                          0.811 0.86
                          0.914 1.00])
            p (doto (m/Paint)
                (.-style! ui/PaintingStyle.stroke)
                (.-strokeWidth! stroke)
                (.-strokeJoin! ui/StrokeJoin.round)
                (.-isAntiAlias! true)
                (.-blendMode! m/BlendMode.hardLight)
                (.-shader! (.createShader grad rect)))]
        (.drawRRect canvas rrect p)))
    (shouldRepaint [_ _] false)))

(defn navigation-button
  "creates a default styled navigation button, content is a list of widgets given to a row,
  on-tap is the callback for when the button is tapped"
  [content on-tap]
  (f/widget
   :let [radius 12]
   (m/DefaultTextStyle.merge
    .style (m/TextStyle
            .color m/Colors.black
            .fontSize 16))
   (m/IconTheme
    .data (m/IconThemeData
           .color m/Colors.black
           .size 14))
   (m/GestureDetector
    .onTap on-tap)
   (m/CustomPaint
    .foregroundPainter (glass-border-painter radius))
   (m/Container
    .decoration (m/BoxDecoration
                 .color (hsv 0.2 0 0 1)
                 .borderRadius (m/BorderRadius.circular radius)))
   :padding {:vertical 6 :horizontal 12}
   (m/Row
    .mainAxisSize m/MainAxisSize.min)
   .children
   content))

(defn gradient-blur-with-column
  "defines a gradient blur along the y axis. 0 is at the top, 1 is at the bottom"
  [width height {:keys [start-stop end-stop start-sigma end-sigma]}]
  (let [n-steps 40
        containers (conj (apply vector
                                (m/Container .width width .height (* start-stop height) .color m/Colors.transparent)
                                (map (fn [_]
                                      (m/Container .width width
                                                   .height (/ (abs (- (* start-stop height) (* end-stop height))) n-steps)
                                                   .color m/Colors.transparent))
                                     (range n-steps)))
                         (m/Container .width width .height (* (- 1 end-stop) height) .color m/Colors.transparent))]
    (f/widget
     m/BackdropGroup
     m/Column
     .children
     (mapv (fn [idx container]
             (m/ClipRect
              .child (m/BackdropFilter.grouped
                      .filter (ui/ImageFilter.blur .sigmaX (ui/lerpDouble start-sigma end-sigma (/ idx (inc n-steps)))
                                                   .sigmaY (ui/lerpDouble start-sigma end-sigma (/ idx (inc n-steps))))
                      .child container)))
          (range) containers))))

(defn gradient-blur-with-stack
  "defines a gradient blur along the y axis. 0 is at the top, 1 is at the bottom
  uses a stack of blurs to create the gradient. This is more finicky to set up and more expensive
  than the gradient-blur-with-column approach"
  [height]
  (m/Stack
   .children
   (mapv (fn [[frac sigma]]
           (m/ClipRect
            .child
            (m/BackdropFilter
             .filter (ui/ImageFilter.blur .sigmaX sigma .sigmaY sigma)
             .child (m/SizedBox
                     .height (* height frac)
                     .width double.infinity))))
         [[0.8 6.0]
          [0.9 2.0]
          [0.95 3.0]
          [1.0 1.0]])))

(defn add-fade-gradient
  "applies a fade gradient to the child, fading from start-stop to end-stop along the y axis. 0 is at the top, 1 is at the bottom"
  [{:keys [start-stop end-stop]} child]
  (m/ShaderMask
     .blendMode m/BlendMode.dstIn
     .shaderCallback (fn [^m/Rect rect]
                       (.createShader
                        (m/LinearGradient
                         .begin m/Alignment.topCenter
                         .end m/Alignment.bottomCenter
                         .colors [m/Colors.black (m/Color 0x00000000)]
                         .stops [start-stop end-stop])
                        rect))
     .child child))

;; render element used with fade-sliver
(deftype RenderFadeSliver
  [^:mutable ^double fadeStart
   ^:mutable ^double fadeExtent]
  :extends rendering/RenderProxySliver
  (paint [this ^m/PaintingContext context ^m/Offset offset]
   (let [constraints  ^rendering/SliverConstraints (.-constraints this)
         sliver-top   (- (.-viewportMainAxisExtent constraints)
                         (.-remainingPaintExtent constraints))
         cross        (.-crossAxisExtent constraints)
         paint-extent (.-paintExtent (.-geometry this))
         fade-end     (+ fadeStart fadeExtent)
         rect         (.& offset (m/Size cross paint-extent))]
     (if (>= sliver-top fade-end)
       (.paintChild context (.-child this) offset)
       ;;don't ask me about the math for this
       (let [start-opacity             (.clamp (/ (- sliver-top fadeStart) fadeExtent) 0.0 1.0)
             start-stop                (.clamp (/ (- fadeStart sliver-top) paint-extent) 0.0 1.0)
             full-opacity-stop         (.clamp (/ (- fade-end sliver-top) paint-extent) 0.0 1.0)
             shader        (.createShader
                            (m/LinearGradient
                             .begin  m/Alignment.topCenter
                             .end    m/Alignment.bottomCenter
                             .colors [(m/Colors.black.withOpacity
                                       start-opacity)
                                      m/Colors.black]
                             .stops  [start-stop full-opacity-stop])
                            rect)]
         (.pushLayer context
                     (doto (rendering/ShaderMaskLayer)
                       (.-shader!    shader)
                       (.-maskRect!  rect)
                       (.-blendMode! m/BlendMode.dstIn))
                     (fn [^m/PaintingContext ctx ^m/Offset off]
                       (.paintChild ctx (.-child this) off))
                     offset))))))

(defn fade-sliver
  "takes a sliver child and applies a fade out gradient from the top of the screen to fadeStart + fadeExtent pixels down
  useful for making a sliver list fade out as it scrolls up.
  This should only be used with slivers. On regular widgets simply apply a shader mask."
  [.child .fadeExtent .fadeStart]
  (reify :extends (m/SingleChildRenderObjectWidget .child child)
    (createRenderObject [this ^m/BuildContext _ctx]
      (RenderFadeSliver fadeStart fadeExtent))
    (updateRenderObject [this ^m/BuildContext _ctx ^RenderFadeSliver ro]
      (.-fadeStart!  ro (double fadeStart))
      (.-fadeExtent! ro (double fadeExtent))
      nil)))
