(ns icare.ui.shared.utils
  (:require ["package:flutter/material.dart" :as m]
            ["dart:math" :refer [pi sqrt atan2 cos sin]]))

(defn rad->deg
  [rad]
  (* rad (/ 180 pi)))

(defn deg->rad
  [deg]
  (* deg (/ pi 180)))

(defn xy->rt [x y]
  (let [radius (sqrt (+ (* x x) (* y y)))
        rad (atan2 y x)
        degree (as-> (rad->deg rad) d
                 (if (< d 0) (+ d 360) d)
                 (mod (- d 90) 360)
                 (- 360 d)
                 (mod d 360))]
    [radius degree]))

(defn ^m/Offset rt->offset
  [radius degree]
  (let [rad (deg->rad degree)
        x (* radius (sin rad)) ;;this is flipped because 0 degrees is at the bottom instead of the right
        y (* radius (cos rad))]
    (m/Offset x y)))

(defn lerp-polar [r1 theta1 r2 theta2 t]
  (let [dtheta (- theta2 theta1)
        ;; Wrap to [-180, 180] (degrees)
        dtheta (cond
                 (> dtheta 180)  (- dtheta 360)
                 (< dtheta -180) (+ dtheta 360)
                 :else           dtheta)
        r (+ r1 (* (- r2 r1) t))
        theta (+ theta1 (* dtheta t))]
    [r theta]))

(defn ^m/Offset lerp-polar-offsets [^m/Offset a ^m/Offset b t]
  (let [[ra ta] (xy->rt (.-dx a) (.-dy a))
        [rb tb] (xy->rt (.-dx b) (.-dy b))
        [r theta] (lerp-polar ra ta rb tb t)]
      (rt->offset r theta)))

(defn get-polar-lerp-from-offsets [^m/Offset a ^m/Offset b]
  (let [[ra ta] (xy->rt (.-dx a) (.-dy a))
        [rb tb] (xy->rt (.-dx b) (.-dy b))]
    (fn [t]
      (let [[r theta] (lerp-polar ra ta rb tb t)]
        (rt->offset r theta)))))

(defn get-phone-measurements
  "gets phone measurements from context
  usually using mediaquery will cause
  the calling widget to rebuild when
  the mediaquery object changes, I'm not sure
  if this is true when accessing mediaquery like this"
  [context]
  (let [phone-padding (m/MediaQuery.viewPaddingOf context)
        notch-height (.-top phone-padding)
        {:flds [width height]} (m/MediaQuery.sizeOf context)]
    {:notch-height notch-height
     :phone-height height
     :phone-width  width}))
