(ns icare.resources.dispatch
  (:require [icare.resources.network :refer [dispatch!] :rename {dispatch! network-dispatch!}]
            [icare.resources.storage :refer [dispatch!] :rename {dispatch! storage-dispatch!}]
            [icare.resources.derived-state :refer [dispatch!] :rename {dispatch! derived-state-dispatch!}]
            [icare.resources.state :refer [dispatch! get-people-cards get-task-by-indexes gather-pub-keys-and-uuids get-user-pub-key]
             :rename {dispatch! state-dispatch!}]))

;;Central dispatch handler for all events (UI and network incoming).
;;Coordinates state updates, storage persistence, and outbound network messages.
;;Notice that each resource module has its own dispatch! function. This is
;;the central one that calls them as needed. Our app has two entry points:
;;- UI events from user interactions, those live in the actual widgest defined in build
;;     we define the callbacks for those events in ast.cljd and pass them down to build where
;;     they actually get called
;;- Network events from listening to our server. The code for that lives in network_events.cljd


(def network-only-events #{:tasks-request :reactions-request})

(defn dispatch! [event]
  (let [{:keys [type]} event]
    (if (network-only-events type)
      ;; Network-only events (no state change)
      (network-dispatch! event)
      ;; Normal events (state + storage + maybe network + maybe derived-state)
      (let [new-state (state-dispatch! event)]
        (storage-dispatch! {:type :state-change-event
                            :new-state new-state})
        (condp = type
          ;; UI events that need network dispatch
          :complete-user-task
         (let [updated-task (get-task-by-indexes new-state (:user-card-idx event) (:task-idx event))]
           (network-dispatch! {:type :update-task-event
                               :deleted false
                               :task updated-task}))

         :delete-user-task
         (network-dispatch! {:type :update-task-event
                             :deleted true
                             :task (:task event)})

         :rename-user-task
         (let [updated-task (get-task-by-indexes new-state (:user-card-idx event) (:task-idx event))]
           (network-dispatch! {:type :update-task-event
                               :deleted false
                               :task updated-task}))

         :like-friend-task
         (network-dispatch! {:type :liked-event
                             :liked (:liked event)
                             :creator-pub-key (:creator-pub-key event)
                             :task-uuid (:task-uuid event)})

         :add-user-task
         (let [{:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids new-state)
               user-pub-key (get-user-pub-key new-state)]
           (network-dispatch! {:type :update-task-event
                               :deleted false
                               :task (:new-task event)})
           (network-dispatch! {:type :reactions-request
                               :user-pub-key user-pub-key
                               :user-task-uuids user-task-uuids
                               :friend-pub-keys friend-pub-keys}))

         :delete-card
         (let [{:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids new-state)
               user-pub-key (get-user-pub-key new-state)
               people-cards (get-people-cards new-state)]
           (derived-state-dispatch! {:type :derive-state
                                     :people-cards people-cards})
           (network-dispatch! {:type :tasks-request
                               :friend-pub-keys friend-pub-keys})
           (network-dispatch! {:type :reactions-request
                               :user-pub-key user-pub-key
                               :user-task-uuids user-task-uuids
                               :friend-pub-keys friend-pub-keys}))

         :add-friend
         (let [{:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids new-state)
               user-pub-key (get-user-pub-key new-state)
               people-cards (get-people-cards new-state)]
           (derived-state-dispatch! {:type :derive-state
                                     :people-cards people-cards})
           (network-dispatch! {:type :tasks-request
                               :friend-pub-keys friend-pub-keys})
           (network-dispatch! {:type :reactions-request
                               :user-pub-key user-pub-key
                               :user-task-uuids user-task-uuids
                               :friend-pub-keys friend-pub-keys}))

         :rename-card ;;TODO this is a somewhat inneficient way to handle this case, we should have a derived state dispatch that just changes a name based on a pub-key
         (let [people-cards (get-people-cards new-state)]
           (derived-state-dispatch! {:type :derive-state
                                     :people-cards people-cards}))

         :card-expansion
         (let [people-cards (get-people-cards new-state)]
           (derived-state-dispatch! {:type :update-expansions
                                     :people-cards people-cards}))

         ;;These events don't require any more dispatch calls
         :reorder-items nil
         :transform-magic-button nil

         ;;Incoming network events, these events also don't require any more dispatch calls
         :liked-event nil
         :update-task-event nil

         (throw (Exception (str "Unknown event type in central dispatch: " event))))))))
