(ns icare.resources.glue
  (:require [icare.resources.state
             :refer [dispatch! initialize-state! gather-pub-keys-and-uuids]
             :rename {dispatch! state-dispatch!}]
            [icare.resources.storage :refer [dispatch!] :rename {dispatch! storage-dispatch!}]
            [icare.resources.network :refer [initialize-network!]]))

(defn update-state-and-persist! [event]
  (let [db (state-dispatch! event)]
    (storage-dispatch! {:type :state-change-event :new-state (:state db)})
    db))

(defn initialize-resources-from-storage! [private-key public-key persisted-state handle-network-data!]
  (let [db @(initialize-state! public-key persisted-state)
        {:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids (:state db))]
    (initialize-network! private-key user-task-uuids friend-pub-keys public-key handle-network-data!)
    db))
