(ns icare.resources.network
  (:require ["package:nostr/nostr.dart" :refer [Event Request Filter]]
            ["dart:io" :refer [WebSocket]]
            [icare.resources.state :refer [get-device-token]]))

;;This module handles outbound network messages.
;;It creates and sends Nostr events to the relay.
;;Incoming events are handled by network-events.cljd

(defonce send-events true)
(defonce initialized? (atom false))
(defonce private-key (atom nil))
(defonce web-socket (atom nil))

(def send-updated-task-kind 39505)
(def liked-event-kind 39506)
(def update-request-to-notify-kind 39507)
(def fulfill-notify-kind 29508) ;;a 2 here is a nostr convention that means that this kind is ephemeral and should not be stored by the relay

(def relay-url "ws://localhost:8080")
;; (def relay-url "wss://relay.damus.io")

;;we want to support offline first workflows
;;that means that the first time we connect to the websocket
;;we should resend all our tasks and receive all possible tasks
;;if we can't connect, don't even try to queue just don't send anything because we can't
;;the next time we connect we will resend everything

(defn create-message [event]
  (condp = (:type event)
    :fulfill-notify
    (let [{:keys [to-pub-key notify-receipt notification-content]} event]
      (-> (.from Event
                 .kind fulfill-notify-kind
                 .content (prn-str {:notify-receipt notify-receipt
                                    :notification-content notification-content
                                    :to-pub-key to-pub-key})
                 .tags [(.from #/(List String) ["p" to-pub-key])]
                 .privkey @private-key)
          .serialize))

    :update-request-to-notify
    (let [{:keys [to-pub-key task-uuid want-notifications?]} event
          device-token (get-device-token)]
      (when device-token
        (-> (.from Event
                   .kind update-request-to-notify-kind
                   .content (prn-str {:want-notifications? want-notifications?
                                      :task-uuid task-uuid
                                      :device-token device-token
                                      :to-pub-key to-pub-key})
                   .tags [(.from #/(List String) ["a" (str update-request-to-notify-kind ":" to-pub-key ":" task-uuid)])]
                   .privkey @private-key)
            .serialize)))

    ;;we send this event both when creating a new task and when updating an existing task, the deleted flag is what determines whether the task should be deleted or not
    :send-updated-task
    (let [{:keys [task deleted]} event
          task-uuid (:uuid task)
          task (conj task [:deleted deleted])]
      (-> (.from Event
                 .kind send-updated-task-kind
                 .content (prn-str task) ;;TODO is this a security risk?
                 .tags [(.from #/(List String) ["d" task-uuid])]
                 .privkey @private-key)
          .serialize))

    ;;we request all add-or-remove-notify-events that relate to our tasks and originate from our friends
    :update-notify-requests-subscription
    (let [{:keys [user-pub-key user-task-uuids friend-pub-keys]} event
          a-tags (or (mapv (fn [task-uuid]
                             (str update-request-to-notify-kind ":" user-pub-key ":" task-uuid))
                           user-task-uuids)
                     [])]
      (-> (Request "notification requests"
                   [(Filter
                     .authors friend-pub-keys
                     .kinds [update-request-to-notify-kind]
                     .a a-tags)])
          .serialize))

    :update-friend-tasks-subscription
    (let [{:keys [friend-pub-keys]} event]
      (-> (Request "tasks from friends"
                   [(Filter
                     .authors friend-pub-keys
                     .kinds [send-updated-task-kind])])
          .serialize))

    (throw (Exception (str "Create message received an unknown event type:" event)))))

(defn dispatch! [event]
  (let [message (create-message event)]
    (if (and send-events @web-socket @initialized? message)
      (do (.add ^WebSocket @web-socket message)
          (prn "Sent event to relay:" message))
      (prn "WebSocket not initialized while trying to send event"))))

(defn start-listening! [ws user-task-uuids friend-pub-keys user-pub-key handle-network-data!]
  (.listen ^WebSocket ws
           (fn [data]
             (handle-network-data! data))
           .onError (fn [error] ;;TODO reconnection logic
                      (prn "WebSocket error:" error)
                      (reset! web-socket nil))
           .onDone (fn [] ;;TODO reconnection logic
                     (prn "WebSocket closed")
                     (reset! web-socket nil)))
  (dispatch! {:type :update-friend-tasks-subscription
              :friend-pub-keys friend-pub-keys})
  (dispatch! {:type :update-notify-requests-subscription
              :user-pub-key user-pub-key
              :user-task-uuids user-task-uuids
              :friend-pub-keys friend-pub-keys}))

(defn ^Future initialize-network! [new-private-key user-task-uuids friend-pub-keys user-pub-key handle-network-data!]
  (when-not @initialized?
    (prn "Initializing network...")
    (reset! initialized? true)
    (reset! private-key new-private-key)
    (try
      (let [ws (await (.connect WebSocket relay-url))] ;;TODO this can throw an exception, we need to handle reconnection logic here
        (reset! web-socket ws)
        (start-listening! ws user-task-uuids friend-pub-keys user-pub-key handle-network-data!))
      (catch Exception e
        (prn "Failed to connect to WebSocket relay:" e))))
  @web-socket)
