(ns icare.resources.network
  (:require ["package:nostr/nostr.dart" :refer [Event Request Filter]]
            ["dart:io" :refer [WebSocket]]))

;;This module handles outbound network messages.
;;It creates and sends Nostr events to the relay.
;;Incoming events are handled by network-events.cljd

(defonce send-events true)
(defonce initialized? (atom false))
(defonce private-key (atom nil))
(defonce web-socket (atom nil))

(def send-updated-task-kind 39505)
(def liked-event-kind 39506)
(def update-request-to-notify-kind 39507)
(def fulfill-notify-kind 29508) ;;a 2 here is a nostr convention that means that this kind is ephemeral and should not be stored by the relay

(def relay-url "ws://localhost:8080")
;; (def relay-url "wss://relay.damus.io")

;;we want to support offline first workflows
;;that means that the first time we connect to the websocket
;;we should resend all our tasks and receive all possible tasks
;;if we can't connect, don't even try to queue just don't send anything because we can't
;;the next time we connect we will resend everything

(defn create-message [event]
  (condp = (:type event)
    :fulfill-notify
    (let [{:keys [to-pub-key notify-receipt notification-content]} event]
      (-> (.from Event
                 .kind fulfill-notify-kind
                 .content (prn-str {:notify-receipt notify-receipt :notification-content notification-content})
                 .tags [(.from #/(List String) ["p" to-pub-key])]
                 .privkey @private-key)
          .serialize))

    :update-request-to-notify
    (let [{:keys [to-pub-key task-uuid want-notifications?]} event]
      (-> (.from Event
                 .kind update-request-to-notify-kind
                 .content (prn-str {:want-notifications? want-notifications? :task-uuid task-uuid :device-token nil}) ;;TODO we need to include the actual device token
                 .tags [(.from #/(List String) ["a" (str update-request-to-notify-kind ":" to-pub-key ":" task-uuid)])]
                 .privkey @private-key)
          .serialize))

    ;; ;;the naming here is pretty confusing, this is sent when adding or removing a like, the creator-pub-key is the pub key of the person who created the task, not the person liking the task, the task-uuid is the uuid of the task being liked, and liked is a boolean representing whether this is adding or removing a like
    ;; ;;deprecated, our app no longer sends these events, instead, liking a task sends a request to be notified about that task usint the add-or-remove-notify-event
    ;; ;;will probably delete soon
    ;; :liked-event
    ;; (let [{:keys [liked creator-pub-key task-uuid]} event]
    ;;   (-> (.from Event
    ;;              .kind liked-event-kind
    ;;              .content (prn-str {:liked liked :task-uuid task-uuid})
    ;;              .tags [(.from #/(List String) ["a" (str update-task-event-kind ":" creator-pub-key ":" task-uuid)])]
    ;;              .privkey @private-key)
    ;;       .serialize))

    ;;we send this event both when creating a new task and when updating an existing task, the deleted flag is what determines whether the task should be deleted or not
    :send-updated-task
    (let [{:keys [task deleted]} event
          task-uuid (:uuid task)
          task (conj task [:deleted deleted])]
      (-> (.from Event
                 .kind send-updated-task-kind
                 .content (prn-str task) ;;TODO is this a security risk? are we gonna get pwned son?
                 .tags [(.from #/(List String) ["d" task-uuid])]
                 .privkey @private-key)
          .serialize))

    ;;we request all add-or-remove-notify-events that relate to our tasks and originate from our friends
    :update-notify-requests-subscription
    (let [{:keys [user-pub-key user-task-uuids friend-pub-keys]} event
          a-tags (or (mapv (fn [task-uuid]
                             (str update-request-to-notify-kind ":" user-pub-key ":" task-uuid))
                           user-task-uuids)
                     [])]
      (-> (Request "notification requests"
                   [(Filter
                     .authors friend-pub-keys
                     .kinds [update-request-to-notify-kind]
                     .a a-tags)])
          .serialize))

    ;; ;;this is deprecates since we no longer send liked-events
    ;; ;;will delete soon
    ;; :reactions-request
    ;; (let [{:keys [user-pub-key user-task-uuids friend-pub-keys]} event
    ;;       a-tags (or (mapv (fn [task-uuid]
    ;;                          (str update-task-event-kind ":" user-pub-key ":" task-uuid))
    ;;                        user-task-uuids)
    ;;                  [])]
    ;;   (-> (Request "notification requests"
    ;;                [(Filter
    ;;                  .authors friend-pub-keys
    ;;                  .kinds [liked-event-kind]
    ;;                  .a a-tags)])
    ;;       .serialize))

    :update-friend-tasks-subscription
    (let [{:keys [friend-pub-keys]} event]
      (-> (Request "tasks from friends"
                   [(Filter
                     .authors friend-pub-keys
                     .kinds [send-updated-task-kind])])
          .serialize))

    (throw (Exception (str "Create message received an unknown event type:" event)))))

(defn dispatch! [event]
  (let [message (create-message event)]
    (if (and send-events @web-socket @initialized?)
      (do (.add ^WebSocket @web-socket message)
          (prn "Sent event to relay:" message))
      (prn "WebSocket not initialized while trying to send event"))))

(defn start-listening! [ws user-task-uuids friend-pub-keys user-pub-key handle-network-data!]
  (.listen ^WebSocket ws
           handle-network-data!
           .onError (fn [error] ;;TODO reconnection logic
                      (prn "WebSocket error:" error)
                      (reset! web-socket nil))
           .onDone (fn [] ;;TODO reconnection logic
                     (prn "WebSocket closed")
                     (reset! web-socket nil)))
  (dispatch! {:type :update-friend-tasks-subscription
              :friend-pub-keys friend-pub-keys})
  (dispatch! {:type :update-notify-requests-subscription
              :user-pub-key user-pub-key
              :user-task-uuids user-task-uuids
              :friend-pub-keys friend-pub-keys}))

(defn ^Future initialize-network! [new-private-key user-task-uuids friend-pub-keys user-pub-key handle-network-data!]
  (when-not @initialized?
    (prn "Initializing network...")
    (reset! initialized? true)
    (reset! private-key new-private-key)
    (let [ws (await (.connect WebSocket relay-url))] ;;TODO this can throw an exception, we need to handle reconnection logic here
      (reset! web-socket ws)
      (start-listening! ws user-task-uuids friend-pub-keys user-pub-key handle-network-data!)))
  @web-socket)
