(ns icare.resources.network
  (:require ["package:nostr/nostr.dart" :refer [Event Request Filter]]
            ["dart:io" :refer [WebSocket]]
            [icare.network-events :refer [handle-network-data! liked-event-kind update-task-event-kind]]))

;;This module handles outbound network messages.
;;It creates and sends Nostr events to the relay.
;;Incoming events are handled by network-events.cljd

(defonce send-events true)
(defonce initialized? (atom false))
(defonce private-key (atom nil))
(defonce web-socket (atom nil))

(def relay-url "ws://localhost:8080")

;;we want to support offline first workflows
;;that means that the first time we connect to the websocket
;;we should resend all our tasks and receive all possible tasks
;;if we can't connect, don't even try to queue just don't send anything because we can't
;;the next time we connect we will resend everything

(defn generate-liked-event [event]
  (let [{:keys [liked creator-pub-key task-uuid]} event]
    (-> (.from Event
               .kind liked-event-kind
               .content (prn-str {:liked liked :task-uuid task-uuid})
               .tags [(.from #/(List String) ["a" (str update-task-event-kind ":" creator-pub-key ":" task-uuid)])]
               .privkey @private-key)
        .serialize)))

(defn generate-update-task-event [event]
  (let [{:keys [task deleted]} event
        task-uuid (:uuid task)
        task (conj task [:deleted deleted])]
    (-> (.from Event
               .kind update-task-event-kind
               .content (prn-str task)
               .tags [(.from #/(List String) ["d" task-uuid])]
               .privkey @private-key)
        .serialize)))

(defn generate-reactions-request [event]
  (let [{:keys [user-pub-key user-task-uuids friend-pub-keys]} event
        a-tags (or (mapv (fn [task-uuid]
                           (str update-task-event-kind ":" user-pub-key ":" task-uuid))
                        user-task-uuids)
                   [])]
    (-> (Request "reactions"
                 [(Filter
                   .authors friend-pub-keys
                   .kinds [liked-event-kind]
                   .a a-tags)])
        .serialize)))

(defn generate-tasks-request [event]
  (let [{:keys [friend-pub-keys]} event]
    (-> (Request "tasks"
                 [(Filter
                   .authors friend-pub-keys
                   .kinds [update-task-event-kind])])
        .serialize)))

(defn create-message [event]
  (condp = (:type event)
    :liked-event (generate-liked-event event)
    :update-task-event (generate-update-task-event event)
    :reactions-request (generate-reactions-request event)
    :tasks-request (generate-tasks-request event)
    (prn "Unhandled action type in network manager:" (:type event))))

(defn dispatch! [event]
  (let [message (create-message event)]
    (if (and send-events @web-socket @initialized?)
      (do (.add ^WebSocket @web-socket message)
          (prn "Sent event to relay:" message))
      (prn "WebSocket not initialized while trying to send event:" message))))

(defn start-listening! [ws user-task-uuids friend-pub-keys user-pub-key]
  (when-not (= @web-socket ws)
    (prn "Started listening to web socket events...")
    (reset! web-socket ws)
    (.listen ^WebSocket ws
             handle-network-data!
             .onError (fn [error] ;;TODO reconnection logic
                        (prn "WebSocket error:" error)
                        (reset! web-socket nil))
             .onDone (fn [] ;;TODO reconnection logic
                       (prn "WebSocket closed")
                       (reset! web-socket nil)))
    (dispatch! {:type :tasks-request
                :friend-pub-keys friend-pub-keys})
    (dispatch! {:type :reactions-request
                :user-pub-key user-pub-key
                :user-task-uuids user-task-uuids
                :friend-pub-keys friend-pub-keys})))

(defn ^Future initialize-network! [new-private-key user-task-uuids friend-pub-keys user-pub-key]
  (when-not @initialized?
    (prn "Initializing network...")
    (reset! initialized? true)
    (reset! private-key new-private-key)
    (let [ws (await (.connect WebSocket relay-url))]
      (reset! web-socket ws)
      (start-listening! ws user-task-uuids friend-pub-keys user-pub-key)))
  @web-socket)
