(ns icare.resources.state
  (:require ["package:uuid/uuid.dart" :refer [Uuid]]))

(def uuid-generator (.-v4 (Uuid)))
(def use-persistent-storage? true)

;;This namespace defines all side effects on our store
;;
(defonce initialized? (atom false))

(defonce store (atom {:reorderable-items [{:type :user
                                           :name "Me"
                                           :expanded? true
                                           :pub-key nil
                                           :tasks [{:title "wake up"
                                                    :uuid (uuid-generator)
                                                    :completed false
                                                    :notify? false
                                                    :liked-by #{"b5bff73132049a564cb588dad986a2acc31fa52c07bbecd991237b8cb9c2fa3b"}
                                                    :subitems []}
                                                   {:title "go to monkey bars"
                                                    :uuid (uuid-generator)
                                                    :completed true
                                                    :notify? false
                                                    :liked-by #{}
                                                    :subitems [{:type :time :value "2026-01-06 09:18:04Z"}]}]}
                                                               ;; {:type :image :value "https://www.adventuretoys.co.uk/images/product/27695monkeybarattach.jpg"}]}]}
                                          {:type :friend
                                           :name "Example 🎸🎸"
                                           :expanded? false
                                           :pub-key "b5bff73132049a564cb588dad986a2acc31fa52c07bbecd991237b8cb9c2fa3b"
                                           :tasks [{:title "Defeated bear"
                                                    :uuid (uuid-generator)
                                                    :liked false
                                                    :notify? false
                                                    :completed false
                                                    :subitems []}
                                                   {:title "go to sleep"
                                                    :uuid (uuid-generator)
                                                    :liked false
                                                    :notify? true
                                                    :completed true
                                                    :subitems [{:type :time :value "2026-01-06 21:18:04Z"}]}
                                                   {:title "went for walk"
                                                    :uuid (uuid-generator)
                                                    :liked false
                                                    :notify? false
                                                    :completed true
                                                    :subitems [{:type :time :value "2026-01-06 14:25:04Z"}
                                                               {:type :image :value "https://media.bizj.us/view/img/10481361/ext-nw-corner-building-copy*900xx3840-2160-0-0.jpg"}]}]}
                                          ;; {:type :uninitialized-person
                                          ;;  :name "Jun before jun"
                                          ;;  :uuid (uuid-generator)}
                                          {:type :friend-search}]
                      :show-qr? false}))

;;Helper functions. Read only operations.

(defn get-people-cards
  ([] (get-people-cards @store))
  ([state] (filterv #(#{:friend :user} (:type %)) (:reorderable-items state))))

(defn friend-search-at-bottom? [reorderable-items]
  (= :friend-search (:type (last reorderable-items))))

(defn get-pub-to-name-map
  ([] (get-pub-to-name-map @store))
  ([state] (let [reorderable-items (:reorderable-items state)]
             (into {}
                   (->> reorderable-items
                        (filter #(#{:friend :user} (:type %)))
                        (map (juxt :pub-key :name)))))))

(defn get-task-by-indexes
  ([user-card-idx task-idx] (get-task-by-indexes @store user-card-idx task-idx))
  ([state user-card-idx task-idx] (get-in state [:reorderable-items user-card-idx :tasks task-idx])))

(defn get-person-task-uuids [person]
  (let [{:keys [tasks]} person]
    (mapv (fn [task] (:uuid task)) tasks)))

(defn gather-pub-keys-and-uuids
  ([] (gather-pub-keys-and-uuids @store))
  ([state] (let [reorderable-items (:reorderable-items state)]
             (reduce
              (fn [acc reorderable-item]
                (condp = (:type reorderable-item)
                  :user (assoc acc :user-task-uuids (get-person-task-uuids reorderable-item))
                  :friend (update acc :friend-pub-keys conj (:pub-key reorderable-item))
                  acc))
              {:user-task-uuids nil
               :friend-pub-keys []}
              reorderable-items))))

(defn get-user-pub-key
  ([] (get-user-pub-key @store))
  ([state] (let [reorderable-items (:reorderable-items state)]
             (->> reorderable-items
                  (filter #(= :user (:type %)))
                  first
                  :pub-key))))

(defn get-reorderable-item-by-idx
  ([reorderable-item-idx] (get-reorderable-item-by-idx @store reorderable-item-idx))
  ([state reorderable-item-idx] (get-in state [:reorderable-items reorderable-item-idx])))

(defn get-reorderable-item-idx-by-predicate [reorderable-items predicate]
  (->> reorderable-items
       (map vector (range))
       (filter (fn [[idx item]] (predicate item)))
       first
       ((fn [[idx item]] idx))))

(defn uuid->task-idx [tasks task-uuid]
  (get-reorderable-item-idx-by-predicate tasks #(= (:uuid %) task-uuid)))

(defn pub-key->reorderable-item-idx [reorderable-items pub-key]
  (get-reorderable-item-idx-by-predicate
   reorderable-items
   #(= (:pub-key %) pub-key)))

(defn get-user-reorderable-item-idx [reorderable-items]
  (get-reorderable-item-idx-by-predicate
   reorderable-items
   #(= (:type %) :user)))

;;this is a helper function to update the notify? status of a task
;;It's meant to be called when we receive network events that modify a task in a meaningful way
;;Be careful notifying a task. A task with notify? true is meant to be resolved by dispatching the :clear-card-notifies event
;;This is done so that notify? controlls the notification flash animation.
;;Therefore, for notify-task to work, we have to make sure that we've also implemented the notify? animation on the appropriate ui element
;;We might want to make a universal notification system so that we can flash particular elements like the new person who liked your task or the
;;particular subitem that's been added and not the entire task. To do this, we might want to add a new AST element: notifiable.
(defn notify-task [state card-idx task-idx]
  (let [expanded? (:expanded? (get-reorderable-item-by-idx state card-idx))]
    (if expanded?
      state
      (assoc-in state [:reorderable-items card-idx :tasks task-idx :notify?] true))))

;;
;;DISPATCH HANDLERS
;;
;;

;;network event handler
(defn handle-liked-event [state event]
  (let [{:keys [liked task-uuid creator-pub-key]} event
        user-pub-key (get-user-pub-key state)
        user-card-idx (pub-key->reorderable-item-idx
                        (:reorderable-items state)
                        user-pub-key)
        task-idx (when-not (nil? user-card-idx)
                  (uuid->task-idx
                   (get-in state [:reorderable-items user-card-idx :tasks])
                   task-uuid))
        like-or-dislike-fn (if liked conj disj)]
    (if (or (nil? user-card-idx) (nil? task-idx))
      state
      (-> state
          ;; (notify-task user-card-idx task-idx)
          (update-in [:reorderable-items user-card-idx :tasks task-idx :liked-by]
                     like-or-dislike-fn
                     creator-pub-key)))))

;;TODO we shouldn't notify if we send a task and delete before the user has expanded their card. I'll  have to think about how to do this
;;network event handler
(defn handle-update-task-event [state event]
  (let [{:keys [task creator-pub-key]} event
        task-uuid (:uuid task)
        deleted? (:deleted task)
        card-idx (pub-key->reorderable-item-idx
                   (:reorderable-items state)
                   creator-pub-key)
        task-idx (when-not (nil? card-idx)
                  (uuid->task-idx
                   (get-in state [:reorderable-items card-idx :tasks])
                   task-uuid))
        user-pub-key (get-user-pub-key state)
        liked-by-user? (contains? (:liked-by task) user-pub-key)
        task (if liked-by-user?
               (conj task [:liked true])
               (conj task [:liked false]))]
    (letfn [(handle-task-deletion [state]
              (when (and card-idx task-idx deleted?)
                (update-in state
                           [:reorderable-items card-idx :tasks]
                           (fn [tasks] (vec (concat (subvec tasks 0 task-idx)
                                                    (subvec tasks (inc task-idx))))))))
            (handle-new-task [state]
              (when (and card-idx (nil? task-idx) (not deleted?))
                (-> state
                    (update-in [:reorderable-items card-idx :tasks] conj (conj task [:notify? true]))))) ;;always notify about a new task, even if the card is expanded
            (handle-existing-task [state]
              (when (and card-idx task-idx)
                (-> state
                    ;;TODO maybe we want to notify about particular events like task completions but not others like renaming a task
                    (assoc-in [:reorderable-items card-idx :tasks task-idx] task)
                    (notify-task card-idx task-idx))))]
      (or (handle-task-deletion state)
          (handle-new-task state)
          (handle-existing-task state)
          state)))) ;;this is the default case in case we receive a nonsensical event... TODO we should add logging here for sanity

(defn handle-complete-user-task[state event]
  (let [{:keys [user-card-idx task-idx completed creator-pub-key]} event]
    (update-in state [:reorderable-items user-card-idx :tasks task-idx]
           (fn [task]
             (let [new-task (assoc task :completed completed)]
               (cond (and (not completed)
                          (seq (:subitems new-task))
                          (-> (:subitems new-task) first :type (= :time)))
                     (update new-task
                             :subitems subvec 1)
                     completed
                     (update new-task
                             :subitems #(apply vector {:type :time
                                                       :value (.toIso8601String (DateTime/now))} %))
                     :else new-task))))))

(defn handle-delete-user-task [state event]
  (let [{:keys [user-card-idx task-idx]} event]
    (update-in state [:reorderable-items user-card-idx :tasks]
               (fn [tasks] (vec (concat (subvec tasks 0 task-idx)
                                        (subvec tasks (inc task-idx))))))))

(defn handle-rename-user-task [state event]
  (let [{:keys [user-card-idx task-idx title]} event]
    (assoc-in state
              [:reorderable-items user-card-idx :tasks task-idx :title]
              title)))

(defn handle-like-friend-task [state event]
  (let [{:keys [friend-card-idx task-idx liked]} event]
    (assoc-in state
              [:reorderable-items friend-card-idx :tasks task-idx :liked]
              liked)))

(defn handle-add-user-task [state event]
  (let [{:keys [user-card-idx new-task]} event]
    (update-in state
               [:reorderable-items user-card-idx :tasks]
               conj new-task)))

(defn handle-delete-card [state event]
  (let [{:keys [card-idx]} event]
    (update state :reorderable-items
            (fn [items]
              (vec (concat (subvec items 0 card-idx)
                           (subvec items (inc card-idx))))))))
(defn handle-rename-card [state event]
  (let [{:keys [card-idx name]} event]
    (assoc-in state
              [:reorderable-items card-idx :name]
              name)))

(defn handle-add-friend [state event]
  (let [{:keys [name]} event]
    (if-not (empty? name)
      (update state :reorderable-items
              (fn [items]
                (let [new-friend {:type :uninitialized-person
                                  :uuid (uuid-generator)
                                  :name name}] ;;obviously this is wrong TODO
                  (vec (concat (subvec items 0 (- (count items) 1)) ;;TODO this isn't right, new friends should either be unmovable or add friend should always add after new friend, probably the first
                               [new-friend]
                               (subvec items (- (count items) 1)))))))
      state)))

(defn handle-initialize-friend [state event]
  (let [{:keys [card-idx public-key]} event]
    (prn event)
    (if-not (empty? public-key)
      (update-in state [:reorderable-items card-idx]
                 conj {:pub-key public-key
                       :type :friend
                       :expanded? false
                       :tasks []})
      state)))

(defn handle-reorder-items [state event]
  (let [{:keys [from-index to-index]} event]
    (update state :reorderable-items
            (fn [items]
              (vec
                (if (< from-index to-index)
                  (concat (subvec items 0 from-index)
                          (subvec items (inc from-index) (inc to-index))
                          [(nth items from-index)]
                          (subvec items (inc to-index)))
                  (concat (subvec items 0 to-index)
                          [(nth items from-index)]
                          (subvec items to-index from-index)
                          (subvec items (inc from-index)))))))))

(defn handle-move-undo-redo [state event]
  (let [{:keys [dx dy]} event]
    (update-in state [:undo-redo]
               (fn [undo-redo]
                 (let [{:keys [x y]} undo-redo]
                   {:x (+ x dx)
                    :y (+ y dy)})))))

(defn handle-card-expansion [state event]
  (let [{:keys [card-idx expanded?]} event]
    (letfn [(handle-opening [state]
              (if-not expanded?
                state
                (-> state
                    (update :reorderable-items  ;;collapse all cards
                         #(mapv (fn [item] (if (contains? item :expanded?)
                                             (assoc item :expanded? false)
                                             item))
                                %)))))

            (handle-closing [state] state) ;;No special handling when closing a card

            (update-expansion [state]
              (assoc-in state [:reorderable-items card-idx :expanded?] expanded?))]
      (-> state
          handle-opening
          handle-closing
          update-expansion))))

(defn handle-task-notification-finishes [state event]
  (let [{:keys [card-idx]} event]
    (-> state
        (update-in [:reorderable-items card-idx :tasks]
                   #(mapv (fn [task]
                            (if (contains? task :notify?)
                              (conj task [:notify? false])
                              task))
                          %)))))

(defn handle-toggle-qr [state event]
  (update state :show-qr? not))

(defn apply-state-event [state event]
  (condp = (:type event)
    :liked-event (handle-liked-event state event)
    :update-task-event (handle-update-task-event state event)
    :complete-user-task (handle-complete-user-task state event)
    :delete-user-task (handle-delete-user-task state event)
    :rename-user-task (handle-rename-user-task state event)
    :like-friend-task (handle-like-friend-task state event)
    :add-user-task (handle-add-user-task state event)
    :delete-card (handle-delete-card state event)
    :rename-card (handle-rename-card state event)
    :add-friend (handle-add-friend state event)
    :reorder-items (handle-reorder-items state event)
    :move-undo-redo (handle-move-undo-redo state event)
    :card-expansion (handle-card-expansion state event)
    :task-notification-finishes (handle-task-notification-finishes state event)
    :toggle-qr (handle-toggle-qr state event)
    :initialize-friend (handle-initialize-friend state event)
    :delete-uninitialized-person (handle-delete-card state event)
    :rename-uninitialized-person (handle-rename-card state event)
    (throw (Exception (str "No dispatch function found for event: " event)))))

;;TODO
;;at some point I'll have to implement event batching
;;To do that, disptach network events should queue events
;;then we have to write a flush function that clears the
;;queue and runs swap! store (reduce #(... appply-network-event acc event) state queue)
;;We should be careful about when to run this flush since we want to be fairly responsive...
;;but you'll get the idea
(defn dispatch! [event]
  (if-not @initialized?
    (throw (Exception. "State store not initialized yet! Call initialize-state! from core first."))
    (swap! store apply-state-event event)))

(defn update-user-pub-key! [pub-key]
  (swap! store update :reorderable-items
         (fn [items]
           (let [user-idx (get-user-reorderable-item-idx items)]
             (assoc-in items [user-idx :pub-key] pub-key)))))

;;Call this function from core, this is the intended way to get a reference to the store
(defn initialize-state! [pub-key persisted-state]
  (when-not @initialized?
    (prn "Initializing state with pub key:" pub-key)
    (when-some [state persisted-state] ;;this is only nil the first time the app runs
      (when use-persistent-storage? (reset! store state)))
    (reset! initialized? true)
    (update-user-pub-key! pub-key))
  store)
