(ns icare.ui.screens.pages.glue
  (:require ["package:flutter/material.dart" :as m]
            [icare.ui.screens.pages.queridos.base
             :refer [state->ast ast-store->widget]
             :rename {state->ast queridos-state->ast
                      ast-store->widget queridos-ast-store->widget}]
            [icare.ui.screens.pages.list.base
             :refer [state->ast ast-store->widget]
             :rename {state->ast list-state->ast
                      ast-store->widget list-ast-store->widget}]
            [cljd.flutter :as f]))

(defn state->ast [db]
  {:id "pages"
   :ui-type ::base
   :home-page      (queridos-state->ast db)
   :bookmarks-page (list-state->ast db)})

(defn ast-store->widget [ast-store side-effects]
  (f/widget
   (m/PageView
    .children [(queridos-ast-store->widget ast-store side-effects)
               (list-ast-store->widget ast-store side-effects)])))
