(ns icare.ui.screens.pages.home
  (:require ["package:flutter/material.dart" :as m]
            ["package:reorderable_grid/reorderable_grid.dart" :as reorderable-grid]
            ["package:flutter_svg/flutter_svg.dart" :as svg]
            ["dart:ui" :as ui]
            [icare.ui.screens.pages.home-components.todo-list
             :refer [list ast-store->widget]
             :rename {ast-store->widget expanded-icon->widget}]
            [icare.ui.shared.utils :refer [get-phone-measurements]]
            [icare.ui.shared.animations :refer [animated-blur animated-asset]]
            [cljd.flutter :as f]))

(defn icon [derived-state icon-index list-item]
  (let [{:keys [name asset tasks]} list-item]
    {:ui-type ::icon
     :id (str "home-icon-" name) ;;TODO we need to disallow duplicate namings
     :idx icon-index
     :asset asset
     :expanded-icon (list derived-state tasks name)
     :key name ;;TODO we need to disallow duplicate namings
     :title name}))

(defn state->ast [db]
  (let [{:keys [derived-state state]} db]
    {:id "home-base"
     :ui-type ::base
     :on-reorder-icons (fn [handle-ui-event!]
                         (fn [old-idx new-idx]
                           (let [[old-idx new-idx] (if (< old-idx new-idx) ;;strangely, there doesn't seem to be a standard for what old and new mean when reordering
                                                     [old-idx (inc new-idx)]
                                                     [old-idx new-idx])]
                             (handle-ui-event! {:type :reorder-icons
                                                :from-index old-idx
                                                :to-index new-idx}))))
     :icons (mapv (partial icon derived-state) (range) (:lists state))}))

;; Widget stuff

(def icon-radius 20)
(def number-of-columns 4)
(def title-style (m/TextStyle
                   .color m/Colors.black
                   .fontSize 14))

(defn ctx->coords [^m/BuildContext context]
  (let [box ^m/RenderBox (.findRenderObject context)
        position (.localToGlobal box m/Offset.zero)
        size (.-size box)]
    {:position position :size size}))

(defn key->coords [^m/GlobalKey key]
  (let [box ^m/RenderBox (.findRenderObject (.-currentContext key))
        position (.localToGlobal box m/Offset.zero)
        size (.-size box)]
    {:position position :size size}))


;;TODO maybe we want to scale up here also
(defn animated-content-fade [controller content]
  (let [curved (m/CurvedAnimation .parent controller .curve (m/Interval 0.3 1.0 .curve m/Curves.easeInOut))
        opacity (.drive curved (m/Tween .begin 0.0 .end 1.0))]
    (f/widget
     :watch [_ controller]
     (m/Opacity
      .opacity (.-value opacity))
     content)))

;; AST -> STORE stuff

(defn ast-store->widget
  ([ast-store handle-ui-event!] (ast-store->widget handle-ui-event! ast-store @(get @ast-store "home-base")))
  ([handle-ui-event! ast-store {:keys [ui-type id] :as ast}]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store @(get @ast-store ast-id)))
         get-ast-atom #(get @ast-store id)
         {:keys [key]} @(get-ast-atom)]
     (condp = ui-type
       ::base
       (f/widget
        :keep-alive true
        :key key
        :context ctx
        :let [{:keys [notch-height phone-height phone-width]} (get-phone-measurements ctx)
              content-start (/ (+ notch-height 40) phone-height)]
        :vsync clock
        :managed [icon-transition-controller (m/AnimationController
                                              .vsync clock
                                              .duration (Duration .milliseconds 300))
                  expanded-icon-atom (atom nil) :dispose nil]
        :bind {:expanded-icon-atom expanded-icon-atom
               :icon-transition-controller icon-transition-controller}
        m/Stack
        .children
        [(f/widget
          :let [{:keys [on-reorder-icons]} @(get-ast-atom)]
          :watch [{:keys [icons]} (get-ast-atom)]
          (reorderable-grid/ReorderableGridView.count
           .anchor content-start
           .crossAxisCount number-of-columns
           .childAspectRatio 0.8
           .proxyDecorator (fn [child _ _] child)
           .onReorder (on-reorder-icons handle-ui-event!)
           .children (mapv recursive-call icons)))
         (f/widget
          :let [content-start 180]
          :watch [expanded-icon expanded-icon-atom]
          :when expanded-icon
          (do
            (.forward icon-transition-controller)
            (m/Stack
             .children
             [(animated-blur icon-transition-controller)
              (m/GestureDetector
               .behavior m/HitTestBehavior.opaque
               .onTap (fn [] (.then (.reverse icon-transition-controller)
                                    (fn [_] (reset! expanded-icon-atom nil)))
                        nil)
               .onHorizontalDragUpdate (fn [_] (.then (.reverse icon-transition-controller)
                                                      (fn [_] (reset! expanded-icon-atom nil)))
                                         nil)
               .child (expanded-icon->widget handle-ui-event! ast-store @(get @ast-store (:expanded-icon expanded-icon))))])))])

       ::icon
       (f/widget
        :key key
        :get [:expanded-icon-atom]
        :let [{:keys [idx expanded-icon]} @(get-ast-atom)]
        :watch [{:keys [title asset]} (get-ast-atom)
                {:keys [icon-idx]} expanded-icon-atom]
        :bypass (when (= idx icon-idx)
                 (m/SizedBox))
        :managed [image-global-key (m/GlobalKey)                      :dispose nil
                  text-global-key  (m/GlobalKey)                      :dispose nil
                  image-stream (when asset (.resolve (m/AssetImage (str "assets/animated/" asset)) m/ImageConfiguration.empty)) :dispose nil]
        (m/GestureDetector
         .behavior m/HitTestBehavior.opaque
         .onTap (fn []
                  (reset! expanded-icon-atom {:image-coords (key->coords image-global-key)
                                              :image-key image-global-key
                                              :text-coords (key->coords text-global-key)
                                              :text-key text-global-key
                                              :expanded-icon expanded-icon
                                              :icon-idx idx
                                              :image-stream image-stream
                                              :title title})))
        (m/Column
         .crossAxisAlignment m/CrossAxisAlignment.center)
        .children
        [(f/widget
          :padding {:vertical 16 :horizontal 16}
          (m/Container
           .key image-global-key)
          (if asset
            (animated-asset image-stream 40 40)
            (svg/SvgPicture.asset
             "assets/icons/fluent--person-24-filled.svg"
             .colorFilter (m/ColorFilter.mode m/Colors.black m/BlendMode.srcIn)
             .width 40
             .height 40)))
         (m/Text title
                 .key text-global-key
                 .style title-style)])

       (throw (Exception (str "Unknown ui-type in home ast-store->widget: " ast)))))))
