(ns icare.ui.screens.pages.home
  (:require ["package:flutter/material.dart" :as m]
            ["package:reorderable_grid/reorderable_grid.dart" :as reorderable-grid]
            ["package:flutter_svg/flutter_svg.dart" :as svg]
            ["dart:ui" :as ui]
            ["package:flutter/rendering.dart" :as rendering]
            [icare.ui.shared :refer [hsv navigation-button glass-border-painter
                                     get-polar-lerp-from-offsets
                                     lerp-polar-offsets
                                     animated-blur
                                     animated-fade
                                     add-fade-gradient]]
            [cljd.flutter :as f]))

(defn expanded-icon-task [derived-state pub-key task] ;;having a separate task ast allows us to have updates which only affect specific tasks, this isn't so important unless we start making tasks really fancy and people have a lot of tasks
  (let [{:keys [title completed liked subitems uuid notify?]} task]
    {:ui-type ::expanded-icon-task
     :id (str "home-task-" uuid)
     :title title
     :completed completed
     :liked liked
     :subitems subitems
     :notify? notify?}))

(defn expanded-icon [derived-state tasks pub-key]
    {:ui-type ::expanded-icon
     :id (str "home-expanded-icon-" pub-key)
     :tasks (mapv (partial expanded-icon-task derived-state pub-key) tasks)})

(defn icon [derived-state icon-index company]
  (let [{:keys [pub-key name asset tasks]} company] ;;TODO i was trying something out with company, I think friend is the better word here
    {:ui-type ::icon
     :id (str "home-icon-" pub-key)
     :idx icon-index
     :asset asset
     :expanded-icon (expanded-icon derived-state tasks pub-key)
     :key pub-key
     :title name}))

(defn state->ast [db]
  (let [{:keys [derived-state state]} db]
    {:id "home-base"
     :ui-type ::base
     :on-reorder-icons (fn [handle-ui-event!]
                         (fn [old-idx new-idx]
                           (let [[old-idx new-idx] (if (< old-idx new-idx) ;;strangely, there doesn't seem to be a standard for what old and new mean when reordering
                                                     [old-idx (inc new-idx)]
                                                     [old-idx new-idx])]
                             (handle-ui-event! {:type :reorder-icons
                                                :from-index old-idx
                                                :to-index new-idx}))))
     :icons (mapv (partial icon derived-state) (range) (:company state))}))

;; Widget stuff

(def icon-radius 20)
(def number-of-columns 4)
(def ^m/Offset image-destination (m/Offset 50 100))
(def title-style (m/TextStyle
                   .color m/Colors.black
                   .fontSize 14))

(defn ctx->coords [^m/BuildContext context]
  (let [box ^m/RenderBox (.findRenderObject context)
        position (.localToGlobal box m/Offset.zero)
        size (.-size box)]
    {:position position :size size}))

(defn key->coords [^m/GlobalKey key]
  (let [box ^m/RenderBox (.findRenderObject (.-currentContext key))
        position (.localToGlobal box m/Offset.zero)
        size (.-size box)]
    {:position position :size size}))

(defn animated-asset
  [^m/ImageStream stream width height]
  (f/widget
   :managed [image-info-atom (atom nil)                                         :dispose nil
             listener        (m/ImageStreamListener
                               (fn [^m/ImageInfo info _]
                                 (let [^m/ImageInfo? old @image-info-atom]
                                   (reset! image-info-atom info)
                                   (when old (.dispose old)))))                 :dispose nil
             _               (doto stream (.addListener listener))
                             :dispose ((fn [^m/ImageStream s]
                                         (when-let [info ^m/ImageInfo @image-info-atom]
                                           (.dispose info))
                                         (.removeListener s listener)))]
   :watch [^m/ImageInfo? info image-info-atom]
   (m/RawImage
     .image  (when info (.-image info))
     .scale  (if (and info (.-scale info)) (.-scale info) 1.0)
     .width  width
     .height height
     .fit    m/BoxFit.contain)))


;;TODO maybe we want to scale up here also
(defn animated-content-fade [controller content]
  (let [curved (m/CurvedAnimation .parent controller .curve (m/Interval 0.3 1.0 .curve m/Curves.easeInOut))
        opacity (.drive curved (m/Tween .begin 0.0 .end 1.0))]
    (f/widget
     :watch [_ controller]
     (m/Opacity
      .opacity (.-value opacity))
     content)))

(defn animated-sliver-fade [controller content]
  (let [curved (m/CurvedAnimation .parent controller .curve (m/Interval 0.3 1.0 .curve m/Curves.easeInOut))
        opacity (.drive curved (m/Tween .begin 0.0 .end 1.0))]
    (f/widget
     :watch [_ controller]
     (m/SliverOpacity
      .opacity (.-value opacity))
     .sliver
     content)))

(defn get-phone-measurements [context]
  (let [phone-padding (m/MediaQuery.viewPaddingOf context)
        notch-height (.-top phone-padding)
        {:flds [width height]} (m/MediaQuery.sizeOf context)]
    {:notch-height notch-height
     :phone-height height
     :phone-width  width}))

;; AST -> STORE stuff

(defn ast-store->widget
  ([ast-store handle-ui-event!] (ast-store->widget handle-ui-event! ast-store @(get @ast-store "home-base")))
  ([handle-ui-event! ast-store {:keys [ui-type id] :as ast}]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store @(get @ast-store ast-id)))
         get-ast-atom #(get @ast-store id)
         {:keys [key]} @(get-ast-atom)]
     (condp = ui-type
       ::base
       (f/widget
        :keep-alive true
        :key key
        :context ctx
        :let [{:keys [notch-height phone-height phone-width]} (get-phone-measurements ctx)
              content-start (/ (+ notch-height 40) phone-height)]
        :vsync clock
        :managed [icon-transition-controller (m/AnimationController
                                              .vsync clock
                                              .duration (Duration .milliseconds 300))
                  expanded-icon-atom (atom nil) :dispose nil]
        :bind {:expanded-icon-atom expanded-icon-atom
               :icon-transition-controller icon-transition-controller}
        m/Stack
        .children
        [(f/widget
          :let [{:keys [on-reorder-icons]} @(get-ast-atom)]
          :watch [{:keys [icons]} (get-ast-atom)]
          (reorderable-grid/ReorderableGridView.count
           .anchor content-start
           .crossAxisCount number-of-columns
           .childAspectRatio 0.8
           .proxyDecorator (fn [child _ _] child)
           .onReorder (on-reorder-icons handle-ui-event!)
           .children (mapv recursive-call icons)))
         (f/widget
          :let [content-start 180
                gradient-start (/ 10 content-start)]
          :watch [expanded-icon expanded-icon-atom]
          :when expanded-icon
          (do
            (.forward icon-transition-controller)
            (m/Stack
             .children
             [(animated-blur icon-transition-controller)
              (m/GestureDetector
               .behavior m/HitTestBehavior.opaque
               .onTap (fn [] (.then (.reverse icon-transition-controller)
                                    (fn [_] (reset! expanded-icon-atom nil)))
                        nil)
               .onHorizontalDragUpdate (fn [_] (.then (.reverse icon-transition-controller)
                                                      (fn [_] (reset! expanded-icon-atom nil)))
                                         nil)
               .child (recursive-call (:expanded-icon expanded-icon)))])))])

       ::icon
       (f/widget
        :key key
        :get [:expanded-icon-atom]
        :let [{:keys [idx expanded-icon]} @(get-ast-atom)]
        :watch [{:keys [title asset]} (get-ast-atom)
                {:keys [icon-idx]} expanded-icon-atom]
        :bypass (when (= idx icon-idx)
                 (m/SizedBox))
        :managed [image-global-key (m/GlobalKey)                      :dispose nil
                  text-global-key  (m/GlobalKey)                      :dispose nil
                  image-stream (when asset (.resolve (m/AssetImage (str "assets/animated/" asset)) m/ImageConfiguration.empty)) :dispose nil]
        (m/GestureDetector
         .behavior m/HitTestBehavior.opaque
         .onTap (fn []
                  (reset! expanded-icon-atom {:image-coords (key->coords image-global-key)
                                              :image-key image-global-key
                                              :text-coords (key->coords text-global-key)
                                              :text-key text-global-key
                                              :expanded-icon expanded-icon
                                              :icon-idx idx
                                              :image-stream image-stream
                                              :title title})))
        (m/Column
         .crossAxisAlignment m/CrossAxisAlignment.center)
        .children
        [(f/widget
          :padding {:vertical 16 :horizontal 16}
          (m/Container
           .key image-global-key)
          (if asset
            (animated-asset image-stream 40 40)
            (svg/SvgPicture.asset
             "assets/icons/fluent--person-24-filled.svg"
             .colorFilter (m/ColorFilter.mode m/Colors.black m/BlendMode.srcIn)
             .width 40
             .height 40)))
         (m/Text title
                 .key text-global-key
                 .style title-style)])

       ::expanded-icon
       (f/widget
        :context ctx
        :get [:icon-transition-controller :expanded-icon-atom]
        :let [{:keys [notch-height phone-height phone-width]} (get-phone-measurements ctx)
              content-start (/ (+ notch-height 150) phone-height)
              {:keys [^m/ImageStream? image-stream image-coords title text-coords]} @expanded-icon-atom
              {image-origin :position image-size :size} image-coords
              {title-origin :position ^m/Size title-size :size} text-coords
              title-destination                         (.+ image-destination (m/Offset (+ (* 0.5 (.-width title-size)) 100) 0))
              curved                                   (m/CurvedAnimation .parent icon-transition-controller .curve m/Curves.easeInOut)
              t                                        (.drive curved (m/Tween .begin 0.0 .end 1.0))
              title                                     (m/Text title .style title-style)
              image (if image-stream
                      (animated-asset image-stream 40 40)
                      (svg/SvgPicture.asset "assets/icons/fluent--person-24-filled.svg"
                       .colorFilter (m/ColorFilter.mode m/Colors.black m/BlendMode.srcIn)
                       .width 40
                       .height 40))]
        :watch [{:keys [tasks]} (get-ast-atom)]
        (m/CustomScrollView
         ;; .anchor content-start
         .physics (m/AlwaysScrollableScrollPhysics)
         .slivers [(m/SliverPersistentHeader
                    .pinned true
                    .delegate (reify :extends m/SliverPersistentHeaderDelegate
                                (build [this context shrink-offset overlaps-content?]
                                  (let [current-size (max (.-minExtent this) (- (.-maxExtent this) shrink-offset))
                                        percent (.clamp (/ shrink-offset 100) 0.0 1.0)
                                        scaled-title-offset (m/Offset -40 -30)
                                        scaled-image-offset (m/Offset 0 -30)
                                        scaledown (- 1.0 (/ shrink-offset (.-maxExtent this)))
                                        image-scale (max 0.5 scaledown)
                                        text-scale (max 0.8 scaledown)]
                                    (f/widget
                                     (m/Container
                                      .height current-size)
                                     (m/Stack
                                      .children
                                      [(f/widget
                                        :watch [_ icon-transition-controller]
                                        (m/Transform.translate
                                         .offset (m/Offset.lerp (m/Offset.lerp image-origin image-destination (.-value t))
                                                                (.+ image-destination scaled-image-offset)
                                                                (* percent (.-value t))))
                                        (m/Transform.scale
                                         .scale (ui/lerpDouble 1.0 (* image-scale 3.0) (.-value t)))
                                        image)
                                       (f/widget
                                        :watch [_ icon-transition-controller]
                                        (m/Transform.translate
                                         .offset (lerp-polar-offsets (lerp-polar-offsets title-origin title-destination (.-value t))
                                                                     (.+ title-destination scaled-title-offset)
                                                                     (* percent (.-value t))))
                                        (m/Transform.scale
                                         .scale (ui/lerpDouble 1.0 (* text-scale 2.0) (.-value t)))
                                        title)]))))
                                (maxExtent [_] 170)
                                (minExtent [_] 170)
                                (shouldRebuild [_ old-delegate] false)))
                   (animated-sliver-fade
                    icon-transition-controller
                    (fade-sliver
                     .child (m/SliverList.list
                             .children (mapv recursive-call tasks))
                     .fadeStart 100
                     .fadeExtent 100))]))

       ::expanded-icon-task
       (f/widget
        :watch [{:keys [title completed liked subitems notify?]} (get-ast-atom)]
        :padding {:vertical 5 :horizontal 28}
        m/Column
        .children
        [(m/Row
          .children
          [(f/widget
            (m/IconButton
             .icon (m/Icon (if completed
                             m/Icons.check_box
                             m/Icons.check_box_outline_blank)
                           .size 26
                           .color m/Colors.grey)
             .onPressed nil))
           (f/widget
            (m/SizedBox .width 160)
            (m/Text title
                    .maxLines nil
                    .style (m/TextStyle
                            .fontSize 22
                            .fontWeight m/FontWeight.normal
                            .color m/Colors.black
                            .decoration (if completed
                                          m/TextDecoration.lineThrough
                                          m/TextDecoration.none))))
           (m/Spacer .flex 4)
           (f/widget
            (m/IconButton
             .icon (m/Icon (if liked
                             m/Icons.favorite
                             m/Icons.favorite_border)
                           .size 26
                           .color m/Colors.red)
             .onPressed nil))
           (m/Spacer .flex 1)])])

       (throw (Exception (str "Unknown ui-type in home ast-store->widget: " ast)))))))

(deftype RenderFadeSliver [^:mutable ^double fadeStart
                           ^:mutable ^double fadeExtent]
  :extends rendering/RenderProxySliver
  (paint [this ^m/PaintingContext context ^m/Offset offset]
   (let [constraints  ^rendering/SliverConstraints (.-constraints this)
         sliver-top   (- (.-viewportMainAxisExtent constraints)
                         (.-remainingPaintExtent constraints))
         cross        (.-crossAxisExtent constraints)
         paint-extent (.-paintExtent (.-geometry this))
         fade-end     (+ fadeStart fadeExtent)
         rect         (.& offset (m/Size cross paint-extent))]
     (if (>= sliver-top fade-end)
       ;; sliver is entirely below the fade zone, paint normally
       (.paintChild context (.-child this) offset)
       (let [;; opacity at the very top of this sliver's paint area
             start-opacity             (.clamp (/ (- sliver-top fadeStart) fadeExtent) 0.0 1.0)
             start-stop                (.clamp (/ (- fadeStart sliver-top) paint-extent) 0.0 1.0)
             full-opacity-stop         (.clamp (/ (- fade-end sliver-top) paint-extent) 0.0 1.0)
             shader        (.createShader
                            (m/LinearGradient
                             .begin  m/Alignment.topCenter
                             .end    m/Alignment.bottomCenter
                             .colors [(m/Colors.black.withOpacity
                                       start-opacity)
                                      m/Colors.black]
                             .stops  [start-stop full-opacity-stop])
                            rect)]
         (.pushLayer context
                     (doto (rendering/ShaderMaskLayer)
                       (.-shader!    shader)
                       (.-maskRect!  rect)
                       (.-blendMode! m/BlendMode.dstIn))
                     (fn [^m/PaintingContext ctx ^m/Offset off]
                       (.paintChild ctx (.-child this) off))
                     offset))))))

(defn fade-sliver [.child .fadeExtent .fadeStart]
  (reify :extends (m/SingleChildRenderObjectWidget .child child)
    (createRenderObject [this ^m/BuildContext _ctx]
      (RenderFadeSliver fadeStart fadeExtent))
    (updateRenderObject [this ^m/BuildContext _ctx ^RenderFadeSliver ro]
      (.-fadeStart!  ro fadeStart)
      (.-fadeExtent! ro fadeExtent)
      nil)))
