(ns icare.ui.screens.pages.queridos.base
  (:require ["package:flutter/material.dart" :as m]
            ["package:reorderable_grid/reorderable_grid.dart" :as reorderable-grid]
            ["package:flutter_svg/flutter_svg.dart" :as svg]
            ["package:flutter/services.dart" :as services]
            ["dart:ui" :as ui]
            [icare.ui.screens.pages.queridos.todo-list
             :refer [ui-list ast-store->widget]
             :rename {ast-store->widget expanded-icon->widget}]
            [icare.ui.screens.pages.shared :refer [get-phone-measurements autoscroll-away-from-keyboard]]
            [icare.ui.screens.pages.queridos.shared :refer [home-icon-asset home-icon-title animated-blur animated-fade debug-border ctx->coords]]
            [cljd.flutter :as f]))

(defn add-querido [derived-state]
  {:ui-type ::add-querido
   :id "home-add-querido"
   :paste-content (:user-pub-key derived-state)
   :on-add-pubkey (fn [handle-ui-event!]
                     (fn [pubkey]
                       (when-not (empty? pubkey)
                         (handle-ui-event! {:type :add-pubkey
                                            :pubkey pubkey}))))})

(defn icon [derived-state expanded-icon-index icon-index list]
  (let [{:keys [name asset tasks uuid]} list
        is-expanded? (= icon-index expanded-icon-index)]
      {:ui-type ::icon
       :key uuid
       :id (str "home-icon-" uuid)
       :idx icon-index
       :is-expanded? is-expanded?
       :asset asset
       :on-expand-icon (fn [handle-ui-event!]
                         (fn []
                           (handle-ui-event! {:type :icon-expansion-toggle
                                              :list-idx icon-index})))
       :title name}))

(defn state->ast [db]
  (let [{:keys [derived-state state]} db
        {:keys [expanded-queridos-idx queridos]} state]
    {:id "home-base"
     :ui-type ::base
     :add-querido (add-querido derived-state)
     :expanded-icon (when expanded-queridos-idx
                      (let [list (nth queridos expanded-queridos-idx)]
                        (ui-list derived-state (:tasks list) (:name list) (:asset list) expanded-queridos-idx (:uuid list) (:pub-key list))))
     :on-deexpand-icon (fn [handle-ui-event!]
                         (fn [& args]
                           (when expanded-queridos-idx
                             (handle-ui-event! {:type :icon-expansion-toggle
                                                :list-idx expanded-queridos-idx}))))
     :on-reorder-icons (fn [handle-ui-event!]
                         (fn [old-idx new-idx]
                           (let [[old-idx new-idx] (if (< old-idx new-idx) ;;strangely, there doesn't seem to be a standard for what old and new mean when reordering
                                                     [old-idx (inc new-idx)]
                                                     [old-idx new-idx])]
                             (handle-ui-event! {:type :reorder-icons
                                                :from-index old-idx
                                                :to-index new-idx}))))
     :icons (mapv (partial icon derived-state expanded-queridos-idx) (range) queridos)}))

;; Widget stuff

(def number-of-columns 2)
(def icon-max-width 270)

(defn key->coords [^m/GlobalKey key]
  (let [box ^m/RenderBox (.findRenderObject (.-currentContext key))
        position (.localToGlobal box m/Offset.zero)
        size (.-size box)]
    {:position position :size size}))


;;TODO maybe we want to scale up here also
(defn animated-content-fade [controller content]
  (let [curved (m/CurvedAnimation .parent controller .curve (m/Interval 0.3 1.0 .curve m/Curves.easeInOut))
        opacity (.drive curved (m/Tween .begin 0.0 .end 1.0))]
    (f/widget
     :watch [_ controller]
     (m/Opacity
      .opacity (.-value opacity))
     content)))

;; AST -> STORE stuff

(defn ast-store->widget
  ([ast-store handle-ui-event!] (ast-store->widget handle-ui-event! ast-store "home-base"))
  ([handle-ui-event! ast-store id]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store ast-id))
         get-ast-atom #(get @ast-store id)
         {:keys [key ui-type]} @(get-ast-atom)]
     (condp = ui-type
       ::base
       (f/widget
        :keep-alive true
        :key key
        :context ctx
        :let [{:keys [notch-height phone-height phone-width]} (get-phone-measurements ctx)
              content-start (/ (+ notch-height 20) phone-height)]
        :vsync clock
        :managed [icon-transition-controller (m/AnimationController
                                              .vsync clock
                                              .duration (Duration .milliseconds 300))
                  expanded-icon-atom (atom nil) :dispose nil]
        :bind {:expanded-icon-atom expanded-icon-atom
               :icon-transition-controller icon-transition-controller}
        (m/Stack
         .alignment m/Alignment.center)
        .children
        [(f/widget
          :watch [{:keys [icons]} (get-ast-atom)]
          :let [{:keys [on-reorder-icons]} @(get-ast-atom)]
          (reorderable-grid/ReorderableGridView.extent
           .maxCrossAxisExtent icon-max-width
           .anchor content-start
           .childAspectRatio 1.1
           .proxyDecorator (fn [child _ _] child)
           .onReorder (on-reorder-icons handle-ui-event!)
           .children (mapv recursive-call icons)))
         (f/widget
          :context ctx
          :let [keyboard-to-bottom (.-bottom (m/MediaQuery.viewInsetsOf ctx))
                keyboard-height (if (pos? keyboard-to-bottom) (+ keyboard-to-bottom 10) 30)]
          (m/AnimatedPositioned
           .duration (Duration .milliseconds 100)
           .bottom (+ keyboard-height 20)
           .child (f/widget
                   (recursive-call (:add-querido @(get-ast-atom))))))
         (f/widget
          :watch [{:keys [expanded-icon]} (get-ast-atom)]
          :let [{:keys [on-deexpand-icon]} @(get-ast-atom)]
          :when expanded-icon
          (do
            (.forward icon-transition-controller)
            (m/Stack
             .children
             [(f/widget
               (animated-fade
                .controller icon-transition-controller
                .begin 0.5
                .end 1)
               (m/Container
                .color (m/Colors.white.withOpacity 0.6)
                .width phone-width
                .height phone-height))
              (animated-blur icon-transition-controller)
              (m/GestureDetector
               .behavior m/HitTestBehavior.opaque
               .onHorizontalDragStart (fn [_]
                                        (.then (.reverse icon-transition-controller)
                                               (fn [_]
                                                 (reset! expanded-icon-atom nil)
                                                 ((on-deexpand-icon handle-ui-event!))))
                                        nil)
               .child (expanded-icon->widget handle-ui-event! ast-store expanded-icon))])))])

       ::icon
       (f/widget
        :key key
        :get [:expanded-icon-atom]
        :let [{:keys [idx on-expand-icon]} @(get-ast-atom)]
        :watch [{:keys [title asset is-expanded?]} (get-ast-atom)]
        :bypass (when is-expanded?
                 (m/SizedBox))
        ;;TODO maybe we don't want to use global keys here
        :managed [image-global-key (m/GlobalKey)                      :dispose nil
                  text-global-key  (m/GlobalKey)                      :dispose nil
                  text-controller (m/TextEditingController .text title)]
        (m/GestureDetector
         .behavior m/HitTestBehavior.opaque
         .onTap (fn []
                  ((on-expand-icon handle-ui-event!))
                  (reset! expanded-icon-atom {:image-coords (key->coords image-global-key)
                                              :text-coords (key->coords text-global-key)})))
        (m/Column)
        .children
        [(m/SizedBox .height 20)
         (f/widget
          (m/Container
           .key image-global-key)
          (home-icon-asset asset))
         (f/widget
          (m/Material
           .type m/MaterialType.transparency)
          (m/SizedBox
           .key text-global-key
           .width (* 0.6 icon-max-width)
           .height 70)
          (home-icon-title .controller text-controller .enabled false))])

       ;;TODO add button to copy the pubkey to clipboard
       ::add-querido
       (f/widget
        :context ctx
        :managed [text-controller (m/TextEditingController)]
        :let [{:keys [on-add-pubkey]} @(get-ast-atom)]
        (m/Column
         .crossAxisAlignment m/CrossAxisAlignment.start)
        .children
        [(m/Row
          .children
          [(f/widget
            (m/IconButton
             .iconSize 30
             .icon (m/Icon m/Icons.content_copy)
             .onPressed (fn []
                          (services/Clipboard.setData (services/ClipboardData. .text (:paste-content @(get-ast-atom))))
                          nil)))
           (f/widget
            (m/SizedBox .width 300)
            (m/TextField
             .textInputAction m.TextInputAction/done
             .maxLines 1
             .style (m/TextStyle
                     .fontSize 22
                     .fontWeight m/FontWeight.normal
                     .color m/Colors.black)
             .decoration (m/InputDecoration
                          .hintText "paste a friend's pubkey here v"
                          .hintStyle (m/TextStyle .fontSize 22
                                                  .fontWeight m/FontWeight.normal
                                                  .color m.Colors/grey)
                          .contentPadding (m/EdgeInsets.only .bottom -10))
             .onSubmitted (fn [pubkey]
                            ((on-add-pubkey handle-ui-event!) pubkey)
                            (.clear text-controller))
             .controller text-controller))])
         (m/Text "    ^ Copy your pubey"
          .style (m/TextStyle
                  .fontSize 22
                  .fontWeight m/FontWeight.normal
                  .color m/Colors.grey)
          .textAlign m/TextAlign.start)])


       (throw (Exception (str "Unknown ui-type in home ast-store->widget: " @(get-ast-atom))))))))
