(ns icare.ui.ast
  (:require ["package:flutter/material.dart" :as m]
            ["package:uuid/uuid.dart" :refer [Uuid]]))

(def uuid-generator (.-v4 (Uuid)))
;;Build an AST from our state

(defn task-subitems->ast [derived-state subitem-idx subitem]
  (let [{:keys [type value task-uuid]} subitem
        {:keys [pub-key-to-name]} derived-state
        id (str "subitem-" task-uuid "-" subitem-idx)]
    (cond
      (= type :liked-list) {:id id :ui-type :subitem-liked-list :liked-by (mapv pub-key-to-name value)}
      (= type :time) {:id id :ui-type :subitem-time :time value}
      (= type :image) {:id id :ui-type :subitem-image :url value}
      :else (throw (Exception. (str "task-subitems->ast was given a task subitem with unknown type: " type))))))

(defn user-task->ast [derived-state task-idx task]
  (let [{:keys [uuid title completed subitems reorderable-item-idx liked-by notify?]} task
        id (str "task-" uuid)
        subitems-with-uuid (mapv #(conj % [:task-uuid uuid])
                                 (if (seq liked-by)
                                   (concat [{:type :liked-list :value liked-by}] subitems)
                                   subitems))]
    {:id id
     :ui-type :editable-task
     :title title
     :notify? notify?
     :on-complete (fn [handle-ui-event!]
                    (fn []
                      (handle-ui-event! {:type :complete-user-task
                                         :user-card-idx reorderable-item-idx
                                         :task-idx task-idx
                                         :completed (not completed)})))
     :on-edit-task-title (fn [handle-ui-event!]
                           (fn [title]
                             (if (empty? title)
                               (handle-ui-event! {:type :delete-user-task
                                                  :user-card-idx reorderable-item-idx
                                                  :task-idx task-idx
                                                  :task task})
                               (handle-ui-event! {:type :rename-user-task
                                                  :user-card-idx reorderable-item-idx
                                                  :task-idx task-idx
                                                  :title title}))))
     :completed completed
     :subitems (mapv (partial task-subitems->ast derived-state) (range) subitems-with-uuid)}))

(defn friend-task->ast [derived-state task-idx task]
  (let [{:keys [title completed liked subitems reorderable-item-idx creator-pub-key uuid notify? card-expanded?]} task
        id (str "task-" uuid)
        subitems-with-uuid (mapv #(conj % [:task-uuid uuid]) subitems)]
    {:id id
     :ui-type :ronly-task
     :title title
     :completed completed
     :notify? (and notify? card-expanded?)
     :on-notifies (fn [handle-ui-event!]
                    (fn [_]
                       (handle-ui-event! {:type :task-notification-finishes
                                          :card-idx reorderable-item-idx})))
     :on-liked (fn [handle-ui-event!]
                 (fn []
                    (handle-ui-event! {:type :like-friend-task
                                       :friend-card-idx reorderable-item-idx
                                       :task-idx task-idx
                                       :liked (not liked)
                                       :creator-pub-key creator-pub-key
                                       :task-uuid uuid})))
     :liked liked
     :subitems (mapv (partial task-subitems->ast derived-state) (range) subitems-with-uuid)}))

(defn add-tasks->ast [derived-state reorderable-item-idx pub-key]
  {:id (str "add-task-" pub-key)
   :ui-type :add-task-area
   :on-add-task (fn [handle-ui-event!]
                  (fn [value]
                    (when (not (empty? value))
                      (let [new-task {:title value
                                      :uuid (uuid-generator)
                                      :liked-by #{}
                                      :completed false
                                      :subitems []}]
                        (handle-ui-event! {:type :add-user-task
                                           :user-card-idx reorderable-item-idx
                                           :new-task new-task})))))})

(defn person->ast [derived-state reorderable-item-idx person]
  (let [{:keys [user? name tasks pub-key expanded? notify?]} person
        id (str "card-" pub-key)
        tasks (mapv #(conj % {:reorderable-item-idx reorderable-item-idx :creator-pub-key pub-key :card-expanded? expanded?}) tasks)]
    {:id id
     :ui-type :task-card
     :expanded? expanded?
     :has-alert? (some :notify? tasks)
     :key pub-key
     :idx reorderable-item-idx
     :title name
     :on-expand (fn [handle-ui-event!]
                  (fn [new-expanded?]
                    (when (not= new-expanded? expanded?)
                      (handle-ui-event! {:type :card-expansion
                                         :expanded? new-expanded?
                                         :card-idx reorderable-item-idx
                                         :pub-key pub-key}))))

     :on-rename-title (fn [handle-ui-event!]
                        (fn [value]
                           (if (empty? value)
                             (handle-ui-event! {:type :delete-card
                                                :card-idx reorderable-item-idx})
                             (handle-ui-event! {:type :rename-card
                                                :card-idx reorderable-item-idx
                                                :name value}))))
     :tasks (if user?
              (conj (mapv (partial user-task->ast derived-state) (range) tasks) (add-tasks->ast derived-state reorderable-item-idx pub-key))
              (mapv (partial friend-task->ast derived-state) (range) tasks))}))

(defn uninitialized-person->ast [derived-state reorderable-item-idx item]
  (let [{:keys [self friend uuid]} item
        id (str "uninit-" uuid)]
    {:id id
     :ui-type :uninitialized-person-card
     :key uuid
     :idx reorderable-item-idx
     :on-rename-from (fn [handle-ui-event!]
                       (fn [value]
                         (handle-ui-event! {:type :rename-uninitialized-card-self
                                            :card-idx reorderable-item-idx
                                            :name value})))
     :on-rename-to (fn [handle-ui-event!]
                     (fn [value]
                       (if (empty? value)
                         (handle-ui-event! {:type :delete-uninitialized-card
                                            :card-idx reorderable-item-idx})
                         (handle-ui-event! {:type :rename-uninitialized-card-friend
                                            :card-idx reorderable-item-idx
                                            :name value}))))
     :on-send-invite (fn [handle-ui-event!]
                       (fn []
                         (handle-ui-event! {:type :send-friend-request}))) ;;TODO we need to figure out the actual logic of this
     :on-paste-public-key (fn [handle-ui-event!]
                            (fn [value]
                              (handle-ui-event! {:type :initialize-friend
                                                 :name name
                                                 :card-idx reorderable-item-idx
                                                 :public-key value})))
     :to-title friend
     :from-title self}))

;;TODO we probably don't want a friend search, easier to
;;have local discovery and adding friends via sharing links
;;either way this is just for demo purposes
(defn friend-search->ast []
  {:id "friend-search"
   :ui-type :friend-search-area
   :on-handshake-qr (fn [handle-ui-event!]
                      (fn []
                        (handle-ui-event! {:type :toggle-handshake-qr})))
   :on-handshake-network (fn [handle-ui-event!]
                           (fn []
                             (handle-ui-event! {:type :toggle-handshake-network})))
   :on-search (fn [handle-ui-event!]
                (fn [value]
                  (handle-ui-event! {:type :add-friend
                                     :name value})))})

(defn list-item->ast [derived-state reorderable-item-idx item]
  (let [{:keys [type]} item]
    (condp = type
      :user (person->ast derived-state reorderable-item-idx (conj item {:user? true}))
      :friend (person->ast derived-state reorderable-item-idx (conj item {:user? false}))
      :uninitialized-person (uninitialized-person->ast derived-state reorderable-item-idx item)
      (throw (Exception (str "list-item->ast was given a list item with unknown type: " type))))))

(defn reorderable-list->ast [derived-state reorderable-items]
  {:id "reorderable-list"
   :ui-type :reorderable-list
   :on-reorder (fn [handle-ui-event!]
                 (fn [from-index to-index]
                   (let [[from-index to-index] (if (< from-index to-index)
                                                 [from-index (dec to-index)]
                                                 [from-index to-index])]
                     (handle-ui-event! {:type :reorder-items
                                        :from-index from-index
                                        :to-index to-index}))))
   :friend-search (friend-search->ast)
   :items (mapv (partial list-item->ast derived-state) (range) reorderable-items)})

(defn top-level-screen->ast [derived-state state]
  (let [{:keys [reorderable-items show-qr?]} state
        {:keys [user-pub-key]} derived-state]
    (cond
      show-qr? {:id "qr-screen"
                :ui-type :qr-screen
                :user-pub-key user-pub-key
                :on-close (fn [handle-ui-event!]
                            (fn []
                              (handle-ui-event! {:type :toggle-handshake-qr})))}
      :else {:id "screen-base"
             :ui-type :screen-base
             :reorderable-list (reorderable-list->ast derived-state reorderable-items)})))

;;watch out, this expects [derived-state state] as an argument, the other functions expect derived-state and state separately
(defn state->ast [[derived-state state]]
   {:id "root"
    :ui-type :root
    :screen (top-level-screen->ast derived-state state)})

;;for the sake of performance, we should write this flattened to remove the overhead of flattening the AST to update our atoms
;;honestly though, performane isn't that bad with the actual compiled app
