(ns icare.ui.ast
  (:require ["package:flutter/material.dart" :as m]
            ["package:uuid/uuid.dart" :refer [Uuid]]
            [icare.state :refer [dispatch! gather-pub-keys-and-uuids get-user-pub-key get-task-by-indexes]
             :rename {dispatch! state-dispatch!}]
            [icare.network :refer [dispatch!] :rename {dispatch! network-dispatch!}]))

(def uuid-generator (.-v4 (Uuid)))
;;Build an AST from our state

(defn task-subitems->ast [subitem]
  (let [{:keys [type value]} subitem]
    (cond
      (= type :liked-list) {:ui-type :subitem-liked-list :liked-by value}
      (= type :time) {:ui-type :subitem-time :time value}
      (= type :image) {:ui-type :subitem-image :url value}
      :else (throw (Exception. (str "task-subitems->ast was given a task subitem with unknown type: " type))))))

(defn user-task->ast [task-idx task]
  (let [{:keys [title completed subitems reorderable-item-idx liked-by]} task]
    {:ui-type :editable-task
     :title title
     :on-complete (fn []
                    (state-dispatch! {:type :complete-user-task
                                      :user-card-idx reorderable-item-idx
                                      :task-idx task-idx
                                      :completed (not completed)})
                    (let [updated-task (get-task-by-indexes reorderable-item-idx task-idx)]
                      (network-dispatch! {:type :update-task-event
                                          :deleted false
                                          :task updated-task})))
     :on-edit-task-title (fn [title]
                           (if (empty? title)
                             (do (state-dispatch! {:type :delete-user-task
                                                   :user-card-idx reorderable-item-idx
                                                   :task-idx task-idx})
                                 ;;we can't get the deleted task after deleting it from state,
                                 ;;in this case, we're only intrested in grabing
                                 ;;a task with the correct uuid to send to the network
                                 (network-dispatch! {:type :update-task-event
                                                     :deleted true
                                                     :task task}))
                             (do (state-dispatch! {:type :rename-user-task
                                                   :user-card-idx reorderable-item-idx
                                                   :task-idx task-idx
                                                   :title title})
                                 (let [updated-task (get-task-by-indexes reorderable-item-idx task-idx)]
                                   (network-dispatch! {:type :update-task-event
                                                       :deleted false
                                                       :task updated-task})))))

     :completed completed
     :subitems (mapv task-subitems->ast
                     (if (seq liked-by)
                       (concat [{:type :liked-list :value liked-by}] subitems)
                       subitems))}))

(defn friend-task->ast [task-idx task]
  (let [{:keys [title completed liked subitems reorderable-item-idx creator-pub-key uuid]} task]
    {:ui-type :ronly-task
     :title title
     :completed completed
     :on-liked (fn []
                 (network-dispatch! {:type :liked-event
                                     :liked (not liked)
                                     :creator-pub-key creator-pub-key
                                     :task-uuid uuid})
                 (state-dispatch! {:type :like-friend-task
                                   :friend-card-idx reorderable-item-idx
                                   :task-idx task-idx
                                   :liked (not liked)}))
     :liked liked
     :subitems (mapv task-subitems->ast subitems)}))

(defn add-tasks->ast [reorderable-item-idx]
  {:ui-type :add-task-area
   :on-add-task (fn [value]
                  (when (not (empty? value))
                    (let [new-task {:title value
                                    :uuid (uuid-generator)
                                    :liked-by #{}
                                    :completed false
                                    :subitems []}]
                      (state-dispatch! {:type :add-user-task
                                        :user-card-idx reorderable-item-idx
                                        :new-task new-task})
                      (network-dispatch! {:type :update-task-event
                                          :deleted false
                                          :task new-task})
                      (let [{:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids)
                            user-pub-key (get-user-pub-key)]
                        (network-dispatch! {:type :reactions-request
                                            :user-pub-key user-pub-key
                                            :user-task-uuids user-task-uuids
                                            :friend-pub-keys friend-pub-keys})))))})

(defn person->ast [reorderable-item-idx person]
  (let [{:keys [user? name tasks pub-key]} person
        tasks (mapv #(conj % {:reorderable-item-idx reorderable-item-idx :creator-pub-key pub-key}) tasks)]
    {:ui-type :task-card
     :initially-expanded user?
     :add-tasks? user?
     :key pub-key
     :title name
     :on-rename-title (fn [value]
                        (if (empty? value)
                          (do (state-dispatch! {:type :delete-card
                                                :card-idx reorderable-item-idx})
                              ;;stop receiving tasks and reactions from deleted friends
                              (let [{:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids)
                                    user-pub-key (get-user-pub-key)]
                                (network-dispatch! {:type :tasks-request
                                                    :friend-pub-keys friend-pub-keys})
                                (network-dispatch! {:type :reactions-request
                                                    :user-pub-key user-pub-key
                                                    :user-task-uuids user-task-uuids
                                                    :friend-pub-keys friend-pub-keys})))
                          (state-dispatch! {:type :rename-card
                                            :card-idx reorderable-item-idx
                                            :name value})))
     :tasks (if user?
              (conj (mapv user-task->ast (range) tasks) (add-tasks->ast reorderable-item-idx))
              (mapv friend-task->ast (range) tasks))}))

;;TODO we probably don't want a friend search, easier to
;;have local discovery and adding friends via sharing links
;;either way this is just for demo purposes
(defn friend-search->ast []
  {:ui-type :friend-search-area
   :on-search (fn [value]
                (state-dispatch! {:type :add-friend
                                  :pub-key value})
                (let [{:keys [user-task-uuids friend-pub-keys]} (gather-pub-keys-and-uuids)
                      user-pub-key (get-user-pub-key)]
                  (network-dispatch! {:type :tasks-request
                                      :friend-pub-keys friend-pub-keys})
                  (network-dispatch! {:type :reactions-request
                                      :user-pub-key user-pub-key
                                      :user-task-uuids user-task-uuids
                                      :friend-pub-keys friend-pub-keys})))})

(defn list-item->ast [reorderable-item-idx item]
  (let [{:keys [type]} item]
    (cond
      (= type :user) (person->ast reorderable-item-idx (conj item {:user? true}))
      (= type :friend) (person->ast reorderable-item-idx (conj item {:user? false}))
      (= type :friend-search) (friend-search->ast)
      :else (throw (Exception. (str "list-item->ast was given a list item with unknown type: " type))))))

(defn reorderable-list->ast [reorderable-items]
  {:ui-type :reorderable-list
   :on-reorder (fn [from-index to-index]
                 (let [[from-index to-index] (if (< from-index to-index)
                                               [from-index (dec to-index)]
                                               [from-index to-index])]
                   (state-dispatch! {:type :reorder-items
                                     :from-index from-index
                                     :to-index to-index})))
   :items (mapv list-item->ast (range) reorderable-items)})

(defn state->ast [state]
  (let [{:keys [reorderable-items]} state]
    {:ui-type :screen-base
     :reorderable-list (reorderable-list->ast reorderable-items)}))
