(ns icare.ui.ast
  (:require ["package:flutter/material.dart" :as m]
            ["package:uuid/uuid.dart" :refer [Uuid]]
            [icare.ui-events :refer [handle-ui-event!]]))

(def uuid-generator (.-v4 (Uuid)))
;;Build an AST from our state

(defn task-subitems->ast [subitem]
  (let [{:keys [type value]} subitem]
    (cond
      (= type :liked-list) {:ui-type :subitem-liked-list :liked-by value}
      (= type :time) {:ui-type :subitem-time :time value}
      (= type :image) {:ui-type :subitem-image :url value}
      :else (throw (Exception. (str "task-subitems->ast was given a task subitem with unknown type: " type))))))

(defn user-task->ast [task-idx task]
  (let [{:keys [title completed subitems reorderable-item-idx liked-by notify?]} task]
    {:ui-type :editable-task
     :title title
     :notify? notify?
     :on-complete (fn []
                    (handle-ui-event! {:type :complete-user-task
                                       :user-card-idx reorderable-item-idx
                                       :task-idx task-idx
                                       :completed (not completed)}))
     :on-edit-task-title (fn [title]
                           (if (empty? title)
                             (handle-ui-event! {:type :delete-user-task
                                                :user-card-idx reorderable-item-idx
                                                :task-idx task-idx
                                                :task task})
                             (handle-ui-event! {:type :rename-user-task
                                                :user-card-idx reorderable-item-idx
                                                :task-idx task-idx
                                                :title title})))
     :completed completed
     :subitems (mapv task-subitems->ast
                     (if (seq liked-by)
                       (concat [{:type :liked-list :value liked-by}] subitems)
                       subitems))}))

(defn friend-task->ast [task-idx task]
  (let [{:keys [title completed liked subitems reorderable-item-idx creator-pub-key uuid notify? card-expanded?]} task]
    {:ui-type :ronly-task
     :title title
     :completed completed
     :notify? (and notify? card-expanded?)
     :on-notifies (fn [_]
                     (handle-ui-event! {:type :task-notification-finishes
                                        :card-idx reorderable-item-idx}))
     :on-liked (fn []
                 (handle-ui-event! {:type :like-friend-task
                                    :friend-card-idx reorderable-item-idx
                                    :task-idx task-idx
                                    :liked (not liked)
                                    :creator-pub-key creator-pub-key
                                    :task-uuid uuid}))
     :liked liked
     :subitems (mapv task-subitems->ast subitems)}))

(defn add-tasks->ast [reorderable-item-idx]
  {:ui-type :add-task-area
   :on-add-task (fn [value]
                  (when (not (empty? value))
                    (let [new-task {:title value
                                    :uuid (uuid-generator)
                                    :liked-by #{}
                                    :completed false
                                    :subitems []}]
                      (handle-ui-event! {:type :add-user-task
                                         :user-card-idx reorderable-item-idx
                                         :new-task new-task}))))})

(defn person->ast [reorderable-item-idx person]
  (let [{:keys [user? name tasks pub-key expanded? notify?]} person
        tasks (mapv #(conj % {:reorderable-item-idx reorderable-item-idx :creator-pub-key pub-key :card-expanded? expanded?}) tasks)]
    {:ui-type :task-card
     :expanded? expanded?
     :has-alert? (some :notify? tasks)
     :key pub-key
     :idx reorderable-item-idx
     :title name
     :on-expand (fn [expanded?]
                  (handle-ui-event! {:type :card-expansion
                                     :expanded? expanded?
                                     :card-idx reorderable-item-idx
                                     :pub-key pub-key}))

     :on-rename-title (fn [value]
                        (if (empty? value)
                          (handle-ui-event! {:type :delete-card
                                             :card-idx reorderable-item-idx})
                          (handle-ui-event! {:type :rename-card
                                             :card-idx reorderable-item-idx
                                             :name value})))
     :tasks (if user?
              (conj (mapv user-task->ast (range) tasks) (add-tasks->ast reorderable-item-idx))
              (mapv friend-task->ast (range) tasks))}))

(defn uninitialized-person->ast [reorderable-item-idx item]
  (let [{:keys [name uuid]} item]
    {:ui-type :uninitialized-person-card
     :key uuid
     :idx reorderable-item-idx
     :on-rename-title (fn [value]
                        (if (empty? value)
                          ;;this is lazy, just create a delete-uninitialized-person event and wire it to the delete-card handler in state
                          (handle-ui-event! {:type :delete-uninitialized-person
                                             :card-idx reorderable-item-idx})
                          (handle-ui-event! {:type :rename-uninitialized-person
                                             :card-idx reorderable-item-idx
                                             :name value})))
     :on-show-qr (fn []
                   (handle-ui-event! {:type :toggle-qr}))
     :on-paste-public-key (fn [value]
                            (handle-ui-event! {:type :initialize-friend
                                               :card-idx reorderable-item-idx
                                               :public-key value}))
     :title name}))

;;TODO we probably don't want a friend search, easier to
;;have local discovery and adding friends via sharing links
;;either way this is just for demo purposes
(defn friend-search->ast []
  {:ui-type :friend-search-area
   :on-search (fn [value]
                (handle-ui-event! {:type :add-friend
                                   :name value}))})

(defn list-item->ast [reorderable-item-idx item]
  (let [{:keys [type]} item]
    (condp = type
      :user (person->ast reorderable-item-idx (conj item {:user? true}))
      :friend (person->ast reorderable-item-idx (conj item {:user? false}))
      :uninitialized-person (uninitialized-person->ast reorderable-item-idx item)
      :friend-search (friend-search->ast)
      (throw (Exception (str "list-item->ast was given a list item with unknown type: " type))))))

(defn reorderable-list->ast [reorderable-items]
  {:ui-type :reorderable-list
   :on-reorder (fn [from-index to-index]
                 (let [[from-index to-index] (if (< from-index to-index)
                                               [from-index (dec to-index)]
                                               [from-index to-index])]
                   (handle-ui-event! {:type :reorder-items
                                      :from-index from-index
                                      :to-index to-index})))
   :items (mapv list-item->ast (range) reorderable-items)})

(defn state->ast [state]
  (let [{:keys [reorderable-items show-qr?]} state]
    (cond
      show-qr? {:ui-type :qr-screen
                :on-close (fn []
                            (handle-ui-event! {:type :toggle-qr}))}
      :else {:ui-type :screen-base
             :reorderable-list (reorderable-list->ast reorderable-items)})))
