(ns icare.ui.build
  (:require ["package:flutter/material.dart" :as m]
            ["package:flutter_svg/flutter_svg.dart" :as svg]
            ["package:qr_flutter/qr_flutter.dart" :as qr]
            ["package:share_plus/share_plus.dart" :as share]
            [cljd.flutter :as f]
            [cljd.string :as str]))

;;TODO extract common styles to constants
(defn ast-store->widget
  ([ast-store handle-ui-event!] (ast-store->widget handle-ui-event! ast-store @(get @ast-store "root")))
  ([handle-ui-event! ast-store {:keys [ui-type id] :as ui}]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store @(get @ast-store ast-id)))
         get-ast-atom (fn [] (get @ast-store id))
         {:keys [key]} @(get-ast-atom)]
     (condp = ui-type
       :root
       (f/widget
        :watch [{:keys [screen]} (get-ast-atom)]
        (recursive-call screen))

       :screen-base
       (f/widget
        :context ctx
        :let [notch-height (-> (m/MediaQuery.of ctx) .-padding .-top)]
        (m/Stack
         .children
         [(f/widget
           :padding {:top notch-height}
           :let [{:keys [reorderable-list]} @(get-ast-atom)]
           (recursive-call reorderable-list))
          (f/widget
           (m/IgnorePointer)
           (m/Column)
           .children
           [(m/Container
             .height (* 1/5 notch-height)
             .color m/Colors.white)
            (m/Container
             .height (* 4/5 notch-height)
             .decoration (m/BoxDecoration
                          .gradient (m/LinearGradient
                                     .begin m/Alignment.topCenter
                                     .end m/Alignment.bottomCenter
                                     .colors [(m/Colors.white.withOpacity 1)
                                              (m/Colors.white.withOpacity 0)])))])]))

       :reorderable-list
       (f/widget
        (m/Scrollbar
         .interactive true)
        :watch [{:keys [items]} (get-ast-atom)]
        :let [{:keys [on-reorder friend-search]} @(get-ast-atom)]
        (m/ReorderableListView
         .clipBehavior m/Clip.none
         .padding (m/EdgeInsets.symmetric .horizontal 20)
         .onReorder (on-reorder handle-ui-event!)
         .buildDefaultDragHandles false
         .proxyDecorator (fn [child index animation] child)
         .children (mapv recursive-call items)
         .footer (recursive-call friend-search)))

       :task-card
       (f/widget
        :key key
        :managed [expansion-controller (m/ExpansibleController)]
        :watch [{:keys [expanded? idx title has-alert? title tasks]} (get-ast-atom)]
        :let [{:keys [on-expand on-rename-title]} @(get-ast-atom)
              _ (do (if expanded?
                      (.expand expansion-controller)
                      (.collapse expansion-controller))
                    nil)]
        :padding {:vertical 6}
        (m/Material
         .elevation 0
         .borderRadius (m/BorderRadius.circular 12))
        (m/ExpansionTile
         .expansionAnimationStyle (m/AnimationStyle
                                   .duration (Duration .milliseconds 700)
                                   .reverseDuration (Duration .milliseconds 100);;TODO I can't get this value to affect the actual duration
                                   .reverseCurve (m/Curves.linear)
                                   .curve (m/Curves.elasticOut))
         .controller expansion-controller
         .onExpansionChanged (on-expand handle-ui-event!)
         .childrenPadding (m/EdgeInsets.only .bottom 20)
         .expandedCrossAxisAlignment m/CrossAxisAlignment.start
         .expandedAlignment m/Alignment.topLeft
         .shape (m/RoundedRectangleBorder
                 .side (m/BorderSide
                        .color (m/Colors.green.withOpacity 1))
                 .borderRadius (m/BorderRadius.circular 12))
         .collapsedShape (m/RoundedRectangleBorder
                          .side (m/BorderSide
                                 .color (if has-alert?
                                          (m/Colors.orange.withOpacity 1)
                                          (m/Colors.black.withOpacity 0.3)))
                          .borderRadius (m/BorderRadius.circular 12))
         .leading (if expanded?
                    (m/Icon m/Icons.drag_handle .color (m/Colors.black.withOpacity 0.2) .size 24)
                    (m/ReorderableDragStartListener
                     .index idx
                     .child (m/Icon m.Icons/drag_handle .size 24)))
         .title (f/widget
                 (m/Align .alignment m/Alignment.centerLeft)
                 (m/Row)
                 .children
                 [(f/widget
                   (m/SizedBox .width 150)
                   (m/TextField
                    .style (m/TextStyle
                            .fontSize 16
                            .fontWeight m/FontWeight.bold
                            .color m/Colors.black)
                    .onSubmitted (on-rename-title handle-ui-event!)
                    .decoration (m/InputDecoration
                                 .contentPadding (m/EdgeInsets.only .bottom 0)
                                 .border m/InputBorder.none)
                    .strutStyle (m/StrutStyle
                                 .fontSize 16
                                 .height 1.9
                                 .forceStrutHeight true)
                    .controller (m/TextEditingController. .text (str title))))])
         .children (mapv recursive-call tasks)))

       :uninitialized-person-card
       (f/widget
        :key key
        :watch [{:keys [idx to-title from-title]} (get-ast-atom)]
        :let [{:keys [on-rename-from on-rename-to on-send-invite on-paste-public-key]} @(get-ast-atom)]
        :padding {:vertical 6}
        (m/Material
         .elevation 0
         .borderRadius (m/BorderRadius.circular 12))
        (m/ReorderableDragStartListener
         .index idx)
        (m/ListTile
         .shape (m/RoundedRectangleBorder
                 .side (m/BorderSide
                        .color (m/Colors.black.withOpacity 0.3))
                 .borderRadius (m/BorderRadius.circular 12))
         .title (f/widget
                 :let [y-offset -10
                       text-field-width 120]
                 (m/Transform.translate .offset (m/Offset 0 y-offset))
                 (m/Row)
                 .children
                 [(f/widget
                   (m/SizedBox .width text-field-width)
                   (m/TextField
                    .textInputAction m.TextInputAction/done
                    .style (m/TextStyle
                            .fontSize 16
                            .fontWeight m/FontWeight.bold
                            .color m/Colors.black)
                    .onSubmitted (on-rename-from handle-ui-event!)
                    .decoration (m/InputDecoration
                                 .hintText "your name..."
                                 .hintStyle (m/TextStyle .fontSize 16
                                                         .fontWeight m/FontWeight.bold
                                                         .color m.Colors/grey)
                                 .contentPadding (m/EdgeInsets.only .bottom y-offset))
                    .strutStyle (m/StrutStyle
                                 .fontSize 16
                                 .height 1.9
                                 .forceStrutHeight true)
                    .controller (m/TextEditingController .text from-title)))
                  (f/widget
                   :padding {:left 12 :right 12 :top (+ (- y-offset) 6)}
                   (m/Icon m/Icons.sync_alt_outlined .size 20 .color (if (empty? from-title) m/Colors.grey m/Colors.black)))
                  (f/widget
                   (m/SizedBox .width text-field-width)
                   (m/TextField
                    .textInputAction m.TextInputAction/done
                    .style (m/TextStyle
                            .fontSize 16
                            .fontWeight m/FontWeight.bold
                            .color m/Colors.black)
                    .onSubmitted (on-rename-to handle-ui-event!)
                    .decoration (m/InputDecoration
                                 .contentPadding (m/EdgeInsets.only .bottom y-offset))
                    .strutStyle (m/StrutStyle
                                 .fontSize 16
                                 .height 1.9
                                 .forceStrutHeight true)
                    .controller (m/TextEditingController .text (str to-title))))
                  (m/Spacer)
                  (f/widget
                   (m/Transform.translate .offset (m/Offset 0 (- y-offset)))
                   (m/IconButton
                    .iconSize 30
                    .icon (m/Icon m/Icons.send_rounded .color (if (empty? from-title) m/Colors.grey m/Colors.green))
                    .onPressed (when-not (empty? from-title)
                                 (fn []
                                   (-> (.instance share/SharePlus) ;;TODO, this smells like a resource and we should probably treat it as one, for now, this is just for demoing
                                       (.share (share/ShareParams. .text "hi, I'd like to add you as a friend on this social task app:
                                                                         something.com")))
                                   ((on-send-invite handle-ui-event!))))))])
         .subtitle (f/widget
                    :let [status-string (cond ;;TODO we can extend this with more statuses like "invite sent, waiting for acceptance", "invite accepted", "invite rejected", etc.)]
                                          (empty? from-title)
                                          "0. Start out by entering your name. This is how your friend will see you when they accept your invite."
                                          :else (str "1. Click the send button to share the invite link with your friend."))]
                    (m/Text status-string
                            .style (m/TextStyle
                                    .fontSize 14
                                    .fontWeight m/FontWeight.normal
                                    .color m/Colors.grey)))))

         ;; .subtitle (f/widget
         ;;            :let [text-controller (m/TextEditingController)]
         ;;            (m/TextField
         ;;             .textInputAction m.TextInputAction/done
         ;;             .style (m/TextStyle
         ;;                     .fontSize 16
         ;;                     .fontWeight m/FontWeight.bold
         ;;                     .color m/Colors.grey)
         ;;             .onSubmitted (on-paste-public-key handle-ui-event!)
         ;;             .decoration (m/InputDecoration
         ;;                          .hintText "paste public key..."
         ;;                          .hintStyle (m/TextStyle
         ;;                                      .fontSize 16
         ;;                                      .fontWeight m.FontWeight/normal
         ;;                                      .color m.Colors/grey)
         ;;                          .contentPadding (m/EdgeInsets.only .bottom 0))
         ;;             .controller text-controller))))

       :editable-task
       (f/widget
        :watch [{:keys [title completed subitems]} (get-ast-atom)]
        :let [{:keys [on-complete on-edit-task-title]} @(get-ast-atom)]
        :padding {:left 20 :bottom 30}
        (m/Column)
        .children
        [(m/Row
          .crossAxisAlignment m.CrossAxisAlignment/center
          .children
          [(f/widget
            (m/IconButton
             .icon (m/Icon (if completed
                             m/Icons.check_box
                             m/Icons.check_box_outline_blank)
                           .size 26
                           .color m.Colors/red)
             .onPressed (on-complete handle-ui-event!)))
           (f/widget
            (m/SizedBox .width 160)
            (m/TextField
             .keyboardType m/TextInputType.text
             .autocorrect false
             .maxLines nil
             .style (m/TextStyle
                     .fontSize 22
                     .fontWeight m/FontWeight.normal
                     .color m.Colors/black
                     .decoration (if completed
                                   m.TextDecoration/lineThrough
                                   m.TextDecoration/none))
             .onSubmitted (on-edit-task-title handle-ui-event!)
             .decoration (m/InputDecoration
                          .border m/InputBorder.none)
             .controller (m/TextEditingController. .text title)))])
         (f/widget
          :padding {:top 4}
          (m/Column .children (mapv recursive-call subitems)))])

       :add-task-area
       (f/widget
        :let [{:keys [on-add-task]} @(get-ast-atom)]
        :padding {:left 20}
        (m/Row
         .crossAxisAlignment m.CrossAxisAlignment/center
         .children [(f/widget
                     :padding {:top 8}
                     (m/IconButton
                      .icon (m/Icon m/Icons.add
                                    .size 26
                                    .color m/Colors.black)
                      .onPressed nil))
                    (f/widget
                     :let [text-controller (m/TextEditingController.)]
                     (m/SizedBox .width 180)
                     (m/TextField
                      .textInputAction m.TextInputAction/done
                      .cursorHeight 38
                      .onSubmitted (fn [new-task-title]
                                     (.clear text-controller)
                                     ((on-add-task handle-ui-event!) new-task-title))
                      .decoration (m/InputDecoration
                                   .hintText "new task..."
                                   .hintStyle (m/TextStyle
                                               .fontSize 22
                                               .fontWeight m/FontWeight.normal
                                               .color m.Colors/grey)
                                   .contentPadding (m/EdgeInsets.only .bottom 0))
                      .strutStyle (m/StrutStyle
                                   .fontSize 22
                                   .height 1.9
                                   .forceStrutHeight true)
                      .controller text-controller
                      .style (m/TextStyle
                              .fontSize 22
                              .fontWeight m/FontWeight.normal
                              .color m.Colors/black)))]))

       :ronly-task
       (f/widget
        :watch [{:keys [title completed subitems liked notify?]} (get-ast-atom)]
        :let [{:keys [on-liked on-notifies]} @(get-ast-atom)
              animation-duration 2000]
        :padding {:left 20 :bottom 30 :right 20}
        :vsync clock
        :managed [controller (m/AnimationController
                              .vsync clock
                              .duration (Duration .milliseconds animation-duration))]
        :let [color-tween (m/TweenSequence
                           [(m/TweenSequenceItem
                             .weight 30
                             .tween (m/ColorTween
                                     .begin (m/Colors.orange.withOpacity 0)
                                     .end (m/Colors.orange.withOpacity 0)))
                            (m/TweenSequenceItem
                             .weight 20
                             .tween (m/ColorTween
                                     .begin (m/Colors.orange.withOpacity 0)
                                     .end (m/Colors.orange.withOpacity 0.3)))
                            (m/TweenSequenceItem
                             .weight 50
                             .tween (m/ColorTween
                                     .begin (m/Colors.orange.withOpacity 0.3)
                                     .end (m/Colors.orange.withOpacity 0)))])
              animation (.drive controller color-tween)]
        (do
          (when notify?
            (.reset controller)
            (.then (.forward controller) (on-notifies handle-ui-event!)))
          (m/AnimatedBuilder
           .animation animation
           .builder
           (fn [ctx child]
             (f/widget
              (m/Container
               .decoration (m/BoxDecoration
                            .color (.-value animation)
                            .borderRadius (m/BorderRadius.circular 16)))
              (m/Column)
              .children
              [(m/Row
                .crossAxisAlignment m.CrossAxisAlignment/center
                .children
                [(f/widget
                  (m/IconButton
                   .icon (m/Icon (if completed
                                   m/Icons.check_box
                                   m/Icons.check_box_outline_blank)
                                 .size 26
                                 .color m/Colors.grey)
                   .onPressed nil))
                 (f/widget
                  (m/SizedBox .width 160)
                  (m/Text title
                          .maxLines nil
                          .style (m/TextStyle
                                  .fontSize 22
                                  .fontWeight m/FontWeight.normal
                                  .color m/Colors.black
                                  .decoration (if completed
                                                m/TextDecoration.lineThrough
                                                m/TextDecoration.none))))
                 (m/Spacer .flex 2)
                 (f/widget
                  (m/IconButton
                   .icon (m/Icon (if liked
                                   m/Icons.favorite
                                   m/Icons.favorite_border)
                                 .size 26
                                 .color m/Colors.red)
                   .onPressed (on-liked handle-ui-event!)))
                 (m/Spacer .flex 1)])
               (m/Transform.translate
                .offset (m/Offset 0 -2)
                .child (m/Column .children (mapv recursive-call subitems)))])))))

       :subitem-liked-list ;;todo, we have to move the name lookup to the ast so that to provide proper updates
       (f/widget
        :watch [{:keys [liked-by]} (get-ast-atom)]
        :padding {:left 15 :bottom 4}
        (m/Row
         .children [(svg/SvgPicture.asset
                     "assets/icons/ph--arrow-bend-down-right-duotone.svg"
                     .colorFilter (m/ColorFilter.mode m/Colors.red m/BlendMode.srcIn)
                     .width 16
                     .height 16)
                    (m/SizedBox .width 4)
                    (m/Text (cond
                              (= 1 (count liked-by))
                              (str "Loved by " (first liked-by))

                              (= 2 (count liked-by))
                              (str "Loved by " (str/join " and " liked-by))

                              :else (str "Loved by " (str/join ", " (butlast liked-by))
                                         ", and " (last liked-by)))
                            .style (m/TextStyle
                                    .fontSize 14
                                    .fontWeight m/FontWeight.normal
                                    .color m.Colors/red))]))

       :subitem-time
       (f/widget
        :watch [{:keys [time]} (get-ast-atom)]
        :let [time (.parse DateTime time)]
        :padding {:left 15 :bottom 4}
        (m/Row
         .children [(f/widget
                     :padding {:bottom 2}
                     (svg/SvgPicture.asset
                      "assets/icons/ph--arrow-bend-down-right-duotone.svg"
                      .colorFilter (m/ColorFilter.mode m/Colors.pink m/BlendMode.srcIn)
                      .width 16
                      .height 16))
                    (m/SizedBox .width 4)
                    (m/Text (str "Completed at " (.-hour time) ":" (.-minute time))
                            .style (m/TextStyle
                                    .fontSize 14
                                    .fontWeight m/FontWeight.normal
                                    .color m.Colors/pink))]))

       :subitem-image
       (f/widget
        :watch [{:keys [url]} (get-ast-atom)]
        :padding {:left 15 :bottom 4}
        (m/Row
         .crossAxisAlignment m.CrossAxisAlignment/start
         .children [(svg/SvgPicture.asset
                     "assets/icons/ph--arrow-bend-down-right-duotone.svg"
                     .colorFilter (m/ColorFilter.mode m/Colors.orange m/BlendMode.srcIn)
                     .width 16
                     .height 16)
                    (m/SizedBox .width 4)
                    (m/Container
                     .width 200
                     .height 120
                     .decoration (m/BoxDecoration
                                  .border (m/Border.all
                                           .color m.Colors/orange
                                           .width 2)
                                  .borderRadius (m/BorderRadius.circular 8)
                                  .image (m/DecorationImage
                                          .fit m.BoxFit/cover
                                          .image (m/NetworkImage url))))]))

       :friend-search-area
       (f/widget
        :key "friend-search-area"
        :let [{:keys [on-search on-handshake-qr on-handshake-network]} @(get-ast-atom)]
        :padding {:vertical 6}
        (m/Material
         .elevation 0)
        (m/ListTile
         .shape (m/RoundedRectangleBorder
                 .side (m/BorderSide
                        .color (m/Colors.black.withOpacity 0.3))
                 .borderRadius (m/BorderRadius.circular 12))
         .leading (m/Icon m.Icons/person_add
                          .size 24
                          .color m.Colors/black)
         .title (f/widget
                 :let [y-offset -10]
                 (m/Transform.translate .offset (m/Offset 0 y-offset))
                 (m/Row)
                 .children
                 [(f/widget
                   :let [text-controller (m/TextEditingController.)]
                   (m/SizedBox .width 180)
                   (m/TextField
                    .style (m/TextStyle
                            .fontSize 16
                            .fontWeight m/FontWeight.bold
                            .color m.Colors/black)
                    .textInputAction m.TextInputAction/done
                    ;; .cursorHeight 38
                    .onSubmitted (fn [new-friend-name]
                                   (.clear text-controller)
                                   ((on-search handle-ui-event!) new-friend-name))
                    .decoration (m/InputDecoration
                                 .hintText "add friend..."
                                 .hintStyle (m/TextStyle
                                             .fontSize 16
                                             .fontWeight m/FontWeight.bold
                                             .color m.Colors/grey)
                                 .contentPadding (m/EdgeInsets.only .bottom y-offset))
                    .strutStyle (m/StrutStyle
                                 .fontSize 16
                                 .height 1.9
                                 .forceStrutHeight true)
                    .controller text-controller))
                  (m/Spacer)
                  (f/widget
                   (m/Transform.translate .offset (m/Offset 0 (- y-offset)))
                   (m/IconButton
                    .iconSize 30
                    .icon (m/Icon m/Icons.qr_code_scanner_outlined .color m/Colors.green)
                    .onPressed (on-handshake-qr handle-ui-event!)))
                  (f/widget
                   (m/Transform.translate .offset (m/Offset 0 (- y-offset)))
                   (m/IconButton
                    .iconSize 30
                    .icon (m/Icon m/Icons.wifi_tethering .color m/Colors.green)
                    .onPressed (on-handshake-network handle-ui-event!)))])))

       :qr-screen
       (f/widget
        :let [{:keys [on-close user-pub-key]} @(get-ast-atom)]
        (m/Center)
        (m/Column
         .mainAxisAlignment m/MainAxisAlignment.center
         .children [(f/widget
                     (qr/QrImageView
                      .data user-pub-key
                      .version qr/QrVersions.auto
                      .size 300))
                    (f/widget
                     :padding {:top 20 :horizontal 40}
                     (m/Text "Let other people scan and paste this public key to add you as a friend."
                             .textAlign m/TextAlign.center
                             .style (m/TextStyle
                                     .fontSize 16
                                     .fontWeight m/FontWeight.normal
                                     .color m/Colors.black)))
                    (f/widget
                     :padding {:top 20}
                     (m/TextButton
                      .style (m/TextButton.styleFrom
                              .backgroundColor m/Colors.orange
                              .padding (m/EdgeInsets.symmetric
                                        .vertical 12
                                        .horizontal 24)
                              .shape (m/RoundedRectangleBorder
                                      .side (m/BorderSide
                                             .color m/Colors.black
                                             .width 2)
                                      .borderRadius (m/BorderRadius.circular 8)))
                      .onPressed (on-close handle-ui-event!))
                     (m/Text
                      "Close this screen!"
                      .style (m/TextStyle
                              .fontSize 24
                              .fontWeight m/FontWeight.bold
                              .color m/Colors.black)))]))

      (throw (Exception. (str "ast-store->widget tried to render an unknown ui element: " ui)))))))
