(ns icare.ui.glue
  (:require [icare.benchmarks :refer [dart-time]]
            [icare.ui.ast :refer [state->ast]]
            [icare.ui.normalized-ast :refer [ast->ast-store]]
            [icare.ui.build :refer [ast-store->widget]]))

(defonce widgets-built? (atom false))

(defn render-ui!
  "Renders the UI based on the current application state. This function transforms the
  application state into an abstract syntax tree (AST). This AST is then normalized
  and moved into a series of atoms which are watched for changes by our widgets."
  [db]
  (assert @widgets-built? "render-ui! was called before the initial build-widgets! call. Make sure to call build-widgets! first to initialize the widget tree.")
  (-> db
      state->ast
      ast->ast-store))

(defn build-widgets!
  "This is like render-ui! but it actually returns the widget tree instead of just updating the atoms.
  This is used for the initial build of the app, on subsequent attempts to render, i.e. after ui and network events
  we just call render-ui! to update the atoms and trigger re-renders of the widgets."
  [db handle-ui-event!]
  (reset! widgets-built? true)
  (-> db
      state->ast
      ast->ast-store
      (ast-store->widget handle-ui-event!)))
