(ns icare.ui.glue
  (:require ["package:flutter/material.dart" :as m]
            ;; [icare.benchmarks :refer [dart-time]]
            [icare.ui.shared.animations :refer [scale-down-fade-animation]]
            [cljd.flutter :as f]
            [icare.ui.screens.qr
             :refer [state->ast ast-store->widget]
             :rename {state->ast qr-state->ast
                      ast-store->widget qr-ast-store->widget}]
            [icare.ui.screens.pages.glue
             :refer [state->ast ast-store->widget]
             :rename {state->ast pages-state->ast
                      ast-store->widget pages-ast-store->widget}]
            [icare.ui.normalized-ast :refer [ast->ast-store]]))

;;first we transform the application state into an abstract syntax tree (AST) which represents the entire UI. This is a pure function with no side effects.
(defn state->ast [{:keys [state] :as db}]
  {:id "root"
   :ui-type ::root
   :screen (condp = (:current-screen state)
             :qr        (qr-state->ast db)
             :pages     (pages-state->ast db)
             (throw (Exception (str "Unknown screen while deriving ast: " (:current-screen state)))))})

;;then we take this AST and normalize it into a flat map of id to AST node, where each node is stored in an atom.
;;in each AST we replace their AST children with just their ids to make diffing with old asts easier.
;;In other words, we take {id "root" :ui-type :root :screen {:id "whatever" :more-stuf ...}} and transform it into
;;{"root" atom{id "root" :ui-type :root :screen "whatever"} "whatever" atom{:id "whatever" :more-stuff ...}}
;;and we do all this before passing it to the ast-store->widget.
;;Because of this, each widget can watch the specific atom that corresponds to its AST node.
(defn ast-store->widget [ast-store handle-ui-event!]
  (f/widget
   :vsync clock
   :managed [transition-controller (m/AnimationController
                                    .duration (Duration .milliseconds 220)
                                    .vsync clock)]
   :let     [build-screen          (atom (:screen @(get @ast-store "root")))
             screen-widget         (f/widget
                                    :watch [screen build-screen]
                                    (condp = screen ;;screen is the id of the root node for each screen
                                      "pages"           (pages-ast-store->widget ast-store handle-ui-event!)
                                      "qr-base"         (qr-ast-store->widget ast-store handle-ui-event!)
                                      (throw (Exception (str "Unknown screen id while deriving widgets: " screen)))))]
   :watch   [{new-screen :screen}  (get @ast-store "root")]
   (do
     (when (not= new-screen @build-screen)
       (.then (.forward transition-controller)
              (fn [_]
                (reset! build-screen new-screen)
                (.reverse transition-controller))))
     (scale-down-fade-animation
      .controller transition-controller
      .child screen-widget))))

(defonce widgets-built? (atom false))

(defn render-ui!
  "Renders the UI based on the current application state. This function transforms the
  application state into an abstract syntax tree (AST). This AST is then normalized
  and moved into a series of atoms which are watched for changes by our widgets."
  [db]
  (assert @widgets-built? "render-ui! was called before the initial build-widgets! call. Make sure to call build-widgets! first to initialize the widget tree.")
  (-> db
      state->ast
      ast->ast-store))

(defn build-widgets!
  "This is like render-ui! but it actually returns the widget tree instead of just updating the atoms.
  This is used for the initial build of the app, on subsequent attempts to render, i.e. after ui and network events
  we just call render-ui! to update the atoms and trigger re-renders of the widgets."
  [db handle-ui-event!]
  (reset! widgets-built? true)
  (-> db
      state->ast
      ast->ast-store
      (ast-store->widget handle-ui-event!)))
