(ns icare.ui.normalized-ast
    (:require [icare.benchmarks :refer [dart-time report-after-n]]))

;; Storage: {id -> atom containing node}
(defonce ast-store (atom {}))

(defn ast-node?
  "Returns true if x is an AST node"
  [x]
  (and (map? x) (contains? x :ui-type) (contains? x :id)))

(defn ast-node-collection?
  "Returns true if x is a collection with only AST nodes"
  [x]
  (and (coll? x) (empty? (filter (complement ast-node?) x))))

(defn partial-ast-node-collection?
  "Returns true if x is a partial collection of AST nodes"
  [x]
  (and (coll? x) (some ast-node? x) (some (complement ast-node?) x)))

(defn denest-ast-node
  "Takes an ast-node and replaces nested ast node values with their id's"
  [node]
  (reduce-kv (fn [denested-node key value]
               (cond
                 (ast-node? value)
                 (conj denested-node [key (:id value)])

                 (ast-node-collection? value)
                 (conj denested-node [key (mapv #(:id %) value)])

                 (partial-ast-node-collection? value)
                 (throw (Exception (str "The ast collection with at least one ast-node must be filled with ast-nodes: " value)))

                 :else
                 denested-node))
             node
             node))

(defn flatten-ast
  "Takes a list of nested AST nodes, returns a flat collection of denested-node
   Denesting replaces child AST nodes with their IDs."
  [ast]
  (mapcat (fn [node]
            (if (ast-node? node)
              (let [nested-nodes (->> node
                                      (filter (fn [[_ value]] (or (ast-node? value)
                                                                  (ast-node-collection? value))))
                                      (map second)
                                      flatten)
                    denested-node (denest-ast-node node)]
                (cons (list (:id denested-node) denested-node) (flatten-ast nested-nodes)))

              (throw (Exception (str "flatten ast encountered an element which wasn't an ast node: " node)))))
          ast))

(defn flatten-ast-nocat
  "same as flatten-ast but without using concat"
  [ast-nodes]
  (letfn [(helper [flattened-so-far ast-nodes]
            (reduce (fn [flat-nodes node]
                       (if (ast-node? node)
                         (let [nested-nodes (->> node
                                                 (filter (fn [[_ value]] (or (ast-node? value)
                                                                             (ast-node-collection? value))))
                                                 (map second)
                                                 flatten)
                               denested-node (denest-ast-node node)]
                           (cons (list (:id denested-node) denested-node) (helper flat-nodes nested-nodes)))

                         (throw (Exception (str "flatten ast encountered an element which wasn't an ast node: " node)))))
                    flattened-so-far
                    ast-nodes))]
    (helper '() ast-nodes)))

(defn sync-ast-store!
  "Updates ast-store with computed ast nodes in atoms
   does not delete nodes for increased performance for now
  ast-store is an atom containing a dictionary of
  ast id's to atoms containing ast nodes, syncing the
  ast store causes the appropriate widgets to rebuild"
  [flat-ast]
  (swap! ast-store
         (fn [ast-atoms]
           (reduce (fn [new-atoms [id node]]
                     (cond
                       (contains? new-atoms id)
                       (do (reset! (new-atoms id) node)
                           new-atoms)

                       :else
                       (conj new-atoms [id (atom node)])))
                   ast-atoms
                   flat-ast))))

(def benchmark-flatten-ast (-> flatten-ast
                               (dart-time "flatten-ast")
                               (report-after-n 10 "flatten-ast")))

(def benchmark-flatten-ast-nocat (-> flatten-ast-nocat
                                     (dart-time "flatten-ast-nocat")
                                     (report-after-n 10 "flatten-ast")))

(defn ast->ast-store [ast]
  (-> ast
      vector
      flatten-ast-nocat
      sync-ast-store!)
  ast-store)
