(ns icare.ui.shared
  (:require ["package:flutter/material.dart" :as m]
            ["dart:ui" :as ui]
            ["package:flutter/rendering.dart" :as rendering]
            ["dart:math" :refer [pi sqrt atan2 cos sin]]
            [cljd.flutter :as f]))

(defn hsv
  ([hue saturation value] (.toColor (m/HSVColor.fromAHSV 1 hue saturation value)))
  ([alpha hue saturation value] (.toColor (m/HSVColor.fromAHSV alpha hue saturation value))))

(defn rad->deg
  [rad]
  (* rad (/ 180 pi)))

(defn deg->rad
  [deg]
  (* deg (/ pi 180)))

(defn xy->rt [x y]
  (let [radius (sqrt (+ (* x x) (* y y)))
        rad (atan2 y x)
        degree (as-> (rad->deg rad) d
                 (if (< d 0) (+ d 360) d)
                 (mod (- d 90) 360)
                 (- 360 d)
                 (mod d 360))]
    [radius degree]))

(defn ^m/Offset rt->offset
  [radius degree]
  (let [rad (deg->rad degree)
        x (* radius (sin rad)) ;;this is flipped because 0 degrees is at the bottom instead of the right
        y (* radius (cos rad))]
    (m/Offset x y)))

(defn lerp-polar [r1 theta1 r2 theta2 t]
  (let [dtheta (- theta2 theta1)
        ;; Wrap to [-180, 180] (degrees)
        dtheta (cond
                 (> dtheta 180)  (- dtheta 360)
                 (< dtheta -180) (+ dtheta 360)
                 :else           dtheta)
        r (+ r1 (* (- r2 r1) t))
        theta (+ theta1 (* dtheta t))]
    [r theta]))

(defn ^m/Offset lerp-polar-offsets [^m/Offset a ^m/Offset b t]
  (let [[ra ta] (xy->rt (.-dx a) (.-dy a))
        [rb tb] (xy->rt (.-dx b) (.-dy b))
        [r theta] (lerp-polar ra ta rb tb t)]
      (rt->offset r theta)))

(defn get-polar-lerp-from-offsets [^m/Offset a ^m/Offset b]
  (let [[ra ta] (xy->rt (.-dx a) (.-dy a))
        [rb tb] (xy->rt (.-dx b) (.-dy b))]
    (fn [t]
      (let [[r theta] (lerp-polar ra ta rb tb t)]
        (rt->offset r theta)))))

(defn glass-border-painter [r]
  (reify :extends m/CustomPainter
    (paint [_ canvas size]
      (let [hi 0.9
            mid 0.7
            lo 0.4
            stroke 1.35
            half (/ stroke 2.0)
            rect (ui/Rect.fromLTWH half half
                   (- (.-width size) stroke)
                   (- (.-height size) stroke))
            rrect (ui/RRect.fromRectAndRadius rect
                    (ui/Radius.circular (- r half)))
            grad (m/SweepGradient
                  .startAngle 0.0
                  .endAngle (* 2.0 pi)
                  .colors [(m/Colors.white.withOpacity lo) (m/Colors.white.withOpacity lo)
                           (m/Colors.white.withOpacity hi) (m/Colors.white.withOpacity hi)
                           (m/Colors.white.withOpacity mid)
                           (m/Colors.white.withOpacity lo) (m/Colors.white.withOpacity lo)
                           (m/Colors.white.withOpacity hi) (m/Colors.white.withOpacity hi)
                           (m/Colors.white.withOpacity mid)
                           (m/Colors.white.withOpacity lo) (m/Colors.white.withOpacity lo)]
                  .stops [0.00 0.02
                          0.035 0.336
                          0.37 0.414
                          0.561 0.585
                          0.811 0.86
                          0.914 1.00])
            p (doto (m/Paint)
                (.-style! ui/PaintingStyle.stroke)
                (.-strokeWidth! stroke)
                (.-strokeJoin! ui/StrokeJoin.round)
                (.-isAntiAlias! true)
                (.-blendMode! m/BlendMode.hardLight)
                (.-shader! (.createShader grad rect)))]
        (.drawRRect canvas rrect p)))
    (shouldRepaint [_ _] false)))

(defn navigation-button
  "creates a default styled navigation button, content is a list of widgets given to a row,
  on-tap is the callback for when the button is tapped"
  [content on-tap]
  (f/widget
   :let [radius 12]
   (m/DefaultTextStyle.merge
    .style (m/TextStyle
            .color m/Colors.black
            .fontSize 16))
   (m/IconTheme
    .data (m/IconThemeData
           .color m/Colors.black
           .size 14))
   (m/GestureDetector
    .onTap on-tap)
   (m/CustomPaint
    .foregroundPainter (glass-border-painter radius))
   (m/Container
    .decoration (m/BoxDecoration
                 .color (hsv 0.2 0 0 1)
                 .borderRadius (m/BorderRadius.circular radius)))
   :padding {:vertical 6 :horizontal 12}
   (m/Row
    .mainAxisSize m/MainAxisSize.min)
   .children
   content))

(defn autoscroll-away-from-keyboard
  "given a scroll controller and a scrollable child returns the scrollable child
  that will automatically scroll up when a focused item is covered by the keyboard"
  [^m/ScrollController scroll-controller scrollable-child]
  (f/widget
   :context ctx
   :managed [focus-callback (fn []
                              (when-let [focused (.-primaryFocus m/FocusManager.instance)]
                                (Future.delayed
                                 (Duration .milliseconds 300)
                                 (fn []
                                   (let [phone-insets (m/MediaQuery.viewInsetsOf ctx)
                                         keyboard-to-bottom (.-bottom phone-insets)
                                         phone-size (m/MediaQuery.sizeOf ctx)
                                         phone-length (.-height phone-size)
                                         focused-to-top (.-dy (.-offset focused))
                                         focused-to-bottom (- phone-length focused-to-top)
                                         extra-height 60
                                         focus-scroll-delta (max
                                                             0
                                                             (+ extra-height
                                                                (- keyboard-to-bottom focused-to-bottom)))
                                         scroll-offset (.-offset scroll-controller)
                                         focus-scroll (+ scroll-offset focus-scroll-delta)]
                                     (when (pos? keyboard-to-bottom)
                                       (.animateTo scroll-controller
                                                   focus-scroll
                                                   .duration (Duration .milliseconds 300)
                                                   .curve m/Curves.linear)))))))
             :dispose nil
             _ (doto m/FocusManager.instance (.addListener focus-callback))
             :dispose (.removeListener focus-callback)]
   scrollable-child))

(defn scale-down-fade-animation
  "Scale down and fade animation"
  [controller child]
  (f/widget
   :managed [curved            (m/CurvedAnimation .parent controller .curve m/Curves.easeInOut) :dispose nil
             scale-animation   (.drive curved (m/Tween .begin 1.0 .end 0.85))                   :dispose nil
             opacity-animation (.drive curved (m/Tween .begin 1.0 .end 0.0))                    :dispose nil]
   (m/AnimatedBuilder
    .animation controller
    .builder (fn [_ child]
               (m/Transform.scale
                .scale (.-value scale-animation)
                .child (m/Opacity
                        .opacity (.-value opacity-animation)
                        .child child)))
    .child child)))


;;there are two ways we could to a gradient blur
;;either we create a column of gradient blurred containers
;;or we stack a series of blurs with changing heights together
;;the first is more efficient but might be less smooth,
(defn gradient-blur-with-column
  "defines a gradient blur along the y axis. 0 is at the top, 1 is at the bottom"
  [width height {:keys [start-stop end-stop start-sigma end-sigma]}]
  (let [n-steps 40
        containers (conj (apply vector
                                (m/Container .width width .height (* start-stop height) .color m/Colors.transparent)
                                (map (fn [_]
                                      (m/Container .width width
                                                   .height (/ (abs (- (* start-stop height) (* end-stop height))) n-steps)
                                                   .color m/Colors.transparent))
                                     (range n-steps)))
                         (m/Container .width width .height (* (- 1 end-stop) height) .color m/Colors.transparent))]
    (f/widget
     m/BackdropGroup
     m/Column
     .children
     (mapv (fn [idx container]
             (m/ClipRect
              .child (m/BackdropFilter.grouped
                      .filter (ui/ImageFilter.blur .sigmaX (ui/lerpDouble start-sigma end-sigma (/ idx (inc n-steps)))
                                                   .sigmaY (ui/lerpDouble start-sigma end-sigma (/ idx (inc n-steps))))
                      .child container)))
          (range) containers))))

(defn gradient-blur-with-stack [height]
    (m/Stack
     .children
     (mapv (fn [[frac sigma]]
             (m/ClipRect
              .child
              (m/BackdropFilter
               .filter (ui/ImageFilter.blur .sigmaX sigma .sigmaY sigma)
               .child (m/SizedBox
                       .height (* height frac)
                       .width double.infinity))))
           [[0.8 6.0]
            [0.9 2.0]
            [0.95 3.0]
            [1.0 1.0]])))

(defn animated-blur
  ([controller] ;;this version fills the whole background
   (f/widget
    :managed [curved          (m/CurvedAnimation .parent controller .curve m/Curves.easeInOut) :dispose nil
              blur-animation  (.drive curved (m/Tween .begin 0.0 .end 12))                     :dispose nil] ;;change end to 12 to go back to blur, blurring is pretty  expensive on older phones so maybe it's not worth it
    :let [empty-space (m/SizedBox.shrink)]
    :watch [_ controller]
    (m/BackdropFilter
     .filter (ui/ImageFilter.blur .sigmaX (.-value blur-animation) .sigmaY (.-value blur-animation))
     .child empty-space)))
  ([controller blur-width blur-height] ;;this version fills a sized area. Can be used with a translation to blur a specific area
   (f/widget
    :managed [curved          (m/CurvedAnimation .parent controller .curve m/Curves.easeInOut) :dispose nil
              blur-animation  (.drive curved (m/Tween .begin 0.0 .end 12))                     :dispose nil] ;;change end to 12 to go back to blur, blurring is pretty  expensive on older phones so maybe it's not worth it
    :let [sized-space (m/Container .width blur-width .height blur-height .color m/Colors.transparent)]
    m/ClipRect
    :watch [_ controller]
    (m/BackdropFilter
     .filter (ui/ImageFilter.blur .sigmaX (.-value blur-animation) .sigmaY (.-value blur-animation))
     .child sized-space))))

(defn add-fade-gradient [{:keys [start-stop end-stop]} child]
  (m/ShaderMask
     .blendMode m/BlendMode.dstIn
     .shaderCallback (fn [^m/Rect rect]
                       (.createShader
                        (m/LinearGradient
                         .begin m/Alignment.topCenter
                         .end m/Alignment.bottomCenter
                         .colors [m/Colors.black (m/Color 0x00000000)]
                         .stops [start-stop end-stop])
                        rect))
     .child child))

(defn animated-fade [controller {:keys [begin end]} content]
  (let [curved (m/CurvedAnimation .parent controller .curve (m/Interval begin end .curve m/Curves.easeInOut))
        opacity (.drive curved (m/Tween .begin 0.0 .end 1.0))]
    (f/widget
     :watch [_ controller]
     (m/Opacity
      .opacity (.-value opacity))
     content)))

;; render element used with fade-sliver"
(deftype RenderFadeSliver
  [^:mutable ^double fadeStart
   ^:mutable ^double fadeExtent]
  :extends rendering/RenderProxySliver
  (paint [this ^m/PaintingContext context ^m/Offset offset]
   (let [constraints  ^rendering/SliverConstraints (.-constraints this)
         sliver-top   (- (.-viewportMainAxisExtent constraints)
                         (.-remainingPaintExtent constraints))
         cross        (.-crossAxisExtent constraints)
         paint-extent (.-paintExtent (.-geometry this))
         fade-end     (+ fadeStart fadeExtent)
         rect         (.& offset (m/Size cross paint-extent))]
     (if (>= sliver-top fade-end)
       (.paintChild context (.-child this) offset)
       ;;don't ask me about the math for this
       (let [start-opacity             (.clamp (/ (- sliver-top fadeStart) fadeExtent) 0.0 1.0)
             start-stop                (.clamp (/ (- fadeStart sliver-top) paint-extent) 0.0 1.0)
             full-opacity-stop         (.clamp (/ (- fade-end sliver-top) paint-extent) 0.0 1.0)
             shader        (.createShader
                            (m/LinearGradient
                             .begin  m/Alignment.topCenter
                             .end    m/Alignment.bottomCenter
                             .colors [(m/Colors.black.withOpacity
                                       start-opacity)
                                      m/Colors.black]
                             .stops  [start-stop full-opacity-stop])
                            rect)]
         (.pushLayer context
                     (doto (rendering/ShaderMaskLayer)
                       (.-shader!    shader)
                       (.-maskRect!  rect)
                       (.-blendMode! m/BlendMode.dstIn))
                     (fn [^m/PaintingContext ctx ^m/Offset off]
                       (.paintChild ctx (.-child this) off))
                     offset))))))

(defn fade-sliver
  "takes a sliver child and applies a fade out gradient from the top of the screen to fadeStart + fadeExtent pixels down
  useful for making a sliver list fade out as it scrolls up.
  This should only be used with slivers. On regular widgets simply apply a shader mask."
  [.child .fadeExtent .fadeStart]
  (reify :extends (m/SingleChildRenderObjectWidget .child child)
    (createRenderObject [this ^m/BuildContext _ctx]
      (RenderFadeSliver fadeStart fadeExtent))
    (updateRenderObject [this ^m/BuildContext _ctx ^RenderFadeSliver ro]
      (.-fadeStart!  ro fadeStart)
      (.-fadeExtent! ro fadeExtent)
      nil)))
