(ns icare.core
  (:require ["package:flutter/material.dart" :as m]
            ["package:google_fonts/google_fonts.dart" :as gf]
            ["package:flutter/services.dart" :as services]
            ["package:firebase_core/firebase_core.dart" :as firebase]
            ["firebase_options.dart" :as firebase-options]
            ["package:haptic_feedback/haptic_feedback.dart" :as haptics]
            [cljd.flutter :as f]
            [icare.resources.glue :refer [initialize-persisted-resources!]]
            [icare.resources.state :refer [transact! uuid-generator db-conn]]
            [icare.resources.datafriend :as df]
            [icare.ui.glue :refer [build-widgets! render-ui!]]))

;; Stub for network events (TODO: implement later)
(defn handle-network-data! [data]
  (prn "Network data received (not yet implemented):" data))

(defn main []
  (await (m/WidgetsFlutterBinding.ensureInitialized))
  (await (firebase/Firebase.initializeApp
          .options firebase-options/DefaultFirebaseOptions.currentPlatform))
  (await (haptics/Haptics.canVibrate))
  (services/SystemChrome.setEnabledSystemUIMode services/SystemUiMode.edgeToEdge)
  (f/run
   (m/MaterialApp
    .title "iCare"
    .theme (m/ThemeData
              .colorScheme (m/ColorScheme.light
                            .surface m/Colors.white
                            .background m/Colors.white)
              .textTheme (gf/GoogleFonts.getTextTheme "Dekko")))
   .home
   (m/AnnotatedRegion
    .value (services/SystemUiOverlayStyle
            ;;android settings
            .systemNavigationBarColor m/Colors.transparent
            .systemNavigationBarIconBrightness services/Brightness.dark
            .systemNavigationBarContrastEnforced false
            .statusBarColor m/Colors.transparent
            .statusBarIconBrightness services/Brightness.dark))
   (m/Scaffold
    ;; .backgroundColor (m/Color 0xFFE8F5E9)
    .resizeToAvoidBottomInset false) ;;we handle this manually by scrolling to make our text fields visible
   .body
   (f/widget
    ;;We wait for futures and show a loading screen
    :watch [db-conn (initialize-persisted-resources! handle-network-data!)]
    :bypass (when-not db-conn
              (f/widget
               (m/SafeArea)
               (m/Text "Loading...")))
    :let [db @db-conn
          side-effects {:transact! transact!
                        :render! #(render-ui! @db-conn)}]
    (m/SafeArea ;;we handle the top and bottom manually for edge to edge rendering
     .bottom false
     .top false)
    (build-widgets! db side-effects))))
