(ns icare.storage
  (:require ["package:path_provider/path_provider.dart" :refer [getApplicationDocumentsDirectory]]
            ["package:flutter_secure_storage/flutter_secure_storage.dart" :refer [FlutterSecureStorage]]
            ["dart:io" :refer [File]]
            ["package:nostr/nostr.dart" :refer [Keychain]]
            [cljd.edn :refer [read-string]]))

;;This module is responsible for persisting the app state to local storage
;;We also load our secure storage here
;;basically storage handles all our persistent data needs

(defonce initialized? (atom false))
(defonce store-file (atom nil))
(defonce receipts-file (atom nil))
(defonce network-log-file (atom nil))

(defn ^Future get-secure-credentials [key-generator]
  (let [storage (FlutterSecureStorage)
        contains-private-key? (await (.containsKey storage .key "private-key"))
        contains-public-key? (await (.containsKey storage .key "public-key"))]
    (cond
      (and contains-private-key? contains-public-key?)
      (let [private-key (await (.read storage .key "private-key"))
            public-key (await (.read storage .key "public-key"))]
        [private-key public-key])

      (and (not contains-private-key?) (not contains-public-key?))
      (let [{:flds [private public]} ^Keychain (key-generator)]
        (await (.write storage .key "private-key" .value private))
        (await (.write storage .key "public-key" .value public))
        [private public])

      :else (throw (Exception "Secure credentials exist partially")))))

(defn get-or-create-file [path-to-directory file-name]
  (let [file-path (str path-to-directory "/" file-name)
        file ^File (File file-path)]
    (when-not (await (.exists file))
      (await (.create file)))
    file))

(defn read-file [^File file]
  (try
    (let [serial-content (await (.readAsString file))]
      (when (seq serial-content)
        (read-string serial-content)))
    (catch Exception e
      (prn "Failed to read file:" (.-path file) "with error:" e)
      nil)))

(defn ^Future initialize-storage! []
  (when-not @initialized?
    (prn "Initializing storage...")
    (reset! initialized? true)
    (let [directory        (await (getApplicationDocumentsDirectory))
          path             (.-path directory)
          state-file*       ^File (await (get-or-create-file path "icare_state.txt"))
          receipts-file*    ^File (await (get-or-create-file path "icare_receipts.txt"))
          network-log-file* ^File (await (get-or-create-file path "icare_network_log.txt"))]
      (reset! store-file state-file*)
      (reset! receipts-file receipts-file*)
      (reset! network-log-file network-log-file*)))
  (let [[private-key public-key] (await (get-secure-credentials (.-generate Keychain)))
        state       (await (read-file @store-file))
        receipts    (await (read-file @receipts-file))
        network-log (await (read-file @network-log-file))]
    [private-key public-key state receipts network-log]))

(defn dispatch! [event]
  (if-not @initialized?
    (throw (Exception. "Tried to dispatch to storage before it was initialized"))
    (condp = (:type event)
      :state-change-event
      (await (.writeAsString ^File @store-file (pr-str (:new-state event))))

      :receipts-change-event
      (await (.writeAsString ^File @receipts-file (pr-str (:new-receipts event))))

      :network-log-change-event
      (await (.writeAsString ^File @network-log-file (pr-str (:new-network-log event))))

      (throw (Exception (str "tried to modify storage with an unknown event" event))))))
