(ns icare.ui.screens.pages.home.base
  (:require ["package:flutter/material.dart" :as m]
            ["package:reorderable_grid/reorderable_grid.dart" :as reorderable-grid]
            ["package:flutter_svg/flutter_svg.dart" :as svg]
            ["dart:ui" :as ui]
            [icare.resources.state :refer [is-empty-list?]]
            [icare.ui.screens.pages.home.todo-list
             :refer [ui-list ast-store->widget]
             :rename {ast-store->widget expanded-icon->widget}]
            [icare.ui.shared.utils :refer [get-phone-measurements]]
            [icare.ui.shared.animations :refer [animated-blur]]
            [cljd.flutter :as f]))

(defn icon [derived-state expanded-icon-index icon-index list]
  (let [{:keys [name asset tasks uuid]} list
        is-expanded? (= icon-index expanded-icon-index)
        is-add-list-icon? (is-empty-list? list)]
      {:ui-type ::icon
       :key uuid
       :id (str "home-icon-" uuid)
       :idx icon-index
       :is-expanded? is-expanded?
       :asset asset
       :on-expand-icon (fn [handle-ui-event!]
                         (fn []
                           (handle-ui-event! {:type :icon-expansion-toggle
                                              :list-idx icon-index})))
       :title name}))

(defn state->ast [db]
  (let [{:keys [derived-state state]} db
        {:keys [expanded-list-idx lists]} state]
    {:id "home-base"
     :ui-type ::base
     :expanded-icon (when expanded-list-idx
                      (let [list (nth lists expanded-list-idx)]
                        (ui-list derived-state (:tasks list) (:name list) (:asset list) expanded-list-idx (:uuid list))))
     :on-deexpand-icon (fn [handle-ui-event!]
                         (fn [& args]
                           (when expanded-list-idx
                             (handle-ui-event! {:type :icon-expansion-toggle
                                                :list-idx expanded-list-idx}))))
     :on-reorder-icons (fn [handle-ui-event!]
                         (fn [old-idx new-idx]
                           (let [[old-idx new-idx] (if (< old-idx new-idx) ;;strangely, there doesn't seem to be a standard for what old and new mean when reordering
                                                     [old-idx (inc new-idx)]
                                                     [old-idx new-idx])]
                             (handle-ui-event! {:type :reorder-icons
                                                :from-index old-idx
                                                :to-index new-idx}))))
     :icons (mapv (partial icon derived-state expanded-list-idx) (range) lists)}))

;; Widget stuff

(def icon-radius 20)
(def number-of-columns 4)
(def title-style (m/TextStyle
                   .color m/Colors.black
                   .fontSize 14))

(defn ctx->coords [^m/BuildContext context]
  (let [box ^m/RenderBox (.findRenderObject context)
        position (.localToGlobal box m/Offset.zero)
        size (.-size box)]
    {:position position :size size}))

(defn key->coords [^m/GlobalKey key]
  (let [box ^m/RenderBox (.findRenderObject (.-currentContext key))
        position (.localToGlobal box m/Offset.zero)
        size (.-size box)]
    {:position position :size size}))


;;TODO maybe we want to scale up here also
(defn animated-content-fade [controller content]
  (let [curved (m/CurvedAnimation .parent controller .curve (m/Interval 0.3 1.0 .curve m/Curves.easeInOut))
        opacity (.drive curved (m/Tween .begin 0.0 .end 1.0))]
    (f/widget
     :watch [_ controller]
     (m/Opacity
      .opacity (.-value opacity))
     content)))

;; AST -> STORE stuff

(defn ast-store->widget
  ([ast-store handle-ui-event!] (ast-store->widget handle-ui-event! ast-store "home-base"))
  ([handle-ui-event! ast-store id]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store ast-id))
         get-ast-atom #(get @ast-store id)
         {:keys [key ui-type]} @(get-ast-atom)]
     (condp = ui-type
       ::base
       (f/widget
        :keep-alive true
        :key key
        :context ctx
        :let [{:keys [notch-height phone-height phone-width]} (get-phone-measurements ctx)
              content-start (/ (+ notch-height 40) phone-height)]
        :vsync clock
        :managed [icon-transition-controller (m/AnimationController
                                              .vsync clock
                                              .duration (Duration .milliseconds 300))
                  expanded-icon-atom (atom nil) :dispose nil]
        :bind {:expanded-icon-atom expanded-icon-atom
               :icon-transition-controller icon-transition-controller}
        m/Stack
        .children
        [(f/widget
          :let [{:keys [on-reorder-icons]} @(get-ast-atom)]
          :watch [{:keys [icons]} (get-ast-atom)]
          (reorderable-grid/ReorderableGridView.count
           .anchor content-start
           .crossAxisCount number-of-columns
           .childAspectRatio 0.8
           .proxyDecorator (fn [child _ _] child)
           .onReorder (on-reorder-icons handle-ui-event!)
           .children (mapv recursive-call icons)))
         (f/widget
          :watch [{:keys [expanded-icon]} (get-ast-atom)]
          :let [{:keys [on-deexpand-icon]} @(get-ast-atom)]
          :when expanded-icon
          (do
            (.forward icon-transition-controller)
            (m/Stack
             .children
             [(animated-blur icon-transition-controller)
              (m/GestureDetector
               .behavior m/HitTestBehavior.opaque
               .onTap (fn []
                        (.then (.reverse icon-transition-controller)
                               (fn [_]
                                 (reset! expanded-icon-atom nil)
                                 ((on-deexpand-icon handle-ui-event!))))
                        nil)
               .onHorizontalDragStart (fn [_]
                                        (.then (.reverse icon-transition-controller)
                                               (fn [_]
                                                 (reset! expanded-icon-atom nil)
                                                 ((on-deexpand-icon handle-ui-event!))))
                                        nil)
               .child (expanded-icon->widget handle-ui-event! ast-store expanded-icon))])))])

       ::icon
       (f/widget
        :key key
        :get [:expanded-icon-atom]
        :let [{:keys [idx on-expand-icon]} @(get-ast-atom)]
        :watch [{:keys [title asset is-expanded?]} (get-ast-atom)]
        :bypass (when is-expanded?
                 (m/SizedBox))
        ;;TODO maybe we don't want to use global keys here
        :managed [image-global-key (m/GlobalKey)                      :dispose nil
                  text-global-key  (m/GlobalKey)                      :dispose nil
                  text-controller (m/TextEditingController .text title)]
        (m/GestureDetector
         .behavior m/HitTestBehavior.opaque
         .onTap (fn []
                  ((on-expand-icon handle-ui-event!))
                  (reset! expanded-icon-atom {:image-coords (key->coords image-global-key)
                                              :image-key image-global-key
                                              :text-coords (key->coords text-global-key)
                                              :text-key text-global-key
                                              :icon-idx idx
                                              :title title})))
        (m/Column)
        .children
        [(m/SizedBox .height 20)
         (f/widget
          (m/Container
           .key image-global-key)
          (m/Image.asset (str "assets/animated/" asset)
                         .fit m/BoxFit.contain
                         .width 40
                         .height 40))
         (f/widget
          (m/Material
           .type m/MaterialType.transparency)
          (m/SizedBox
           .key text-global-key
           .width 95)
          (m/TextField
           .controller text-controller
           .enabled false
           .textAlign m/TextAlign.center
           .maxLines 3
           .decoration (m/InputDecoration
                        .contentPadding m/EdgeInsets.zero
                        .isDense true
                        .border m/InputBorder.none)
           .style title-style))])

       (throw (Exception (str "Unknown ui-type in home ast-store->widget: " @(get-ast-atom))))))))
