(ns icare.ui.screens.pages.home.todo-list
  (:require ["package:flutter/material.dart" :as m]
            ["package:flutter_svg/flutter_svg.dart" :as svg]
            ["dart:ui" :as ui]
            [icare.ui.shared.paint :refer [hsv fade-sliver]]
            [icare.ui.shared.utils :refer [lerp-polar-offsets get-phone-measurements]]
            [icare.ui.shared.animations :refer [animated-asset animated-sliver-fade animated-fade autoscroll-away-from-keyboard]]
            [cljd.flutter :as f]))

(defn task [derived-state name list-idx task-idx task]
  (let [{:keys [uuid title completed is-add-task-task?]} task]
    (if is-add-task-task?
      {:ui-type ::add-task-task
       :key list-idx
       :id (str "add-task-task-" list-idx)
       :on-add-task (fn [handle-ui-event!]
                      (fn [title]
                        (when-not (empty? title)
                          (handle-ui-event! {:type :add-task
                                             :title title
                                             :list-idx list-idx
                                             :task-idx task-idx}))))}
      {:ui-type ::task
       :key uuid
       :id (str name "-task-" uuid)
       :title title
       :on-complete (fn [handle-ui-event!]
                      (fn []
                        (handle-ui-event! {:type :complete-task
                                           :list-idx list-idx
                                           :task-idx task-idx
                                           :completed (not completed)})))
       :on-change-task-title (fn [handle-ui-event!]
                               (fn [new-title]
                                 (handle-ui-event! {:type :rename-task
                                                    :list-idx list-idx
                                                    :task-idx task-idx
                                                    :title new-title})))
       :on-edit-task-title (fn [handle-ui-event!]
                             (fn [title]
                               (if (empty? title)
                                 (handle-ui-event! {:type :delete-task
                                                    :list-idx list-idx
                                                    :task-idx task-idx
                                                    :task task})
                                 (handle-ui-event! {:type :rename-task
                                                    :list-idx list-idx
                                                    :task-idx task-idx
                                                    :title title}))))
       :completed completed})))

(defn ui-list [derived-state tasks name icon-idx uuid]
   {:id (str "list-base-" uuid)
    :ui-type ::list
    :on-reorder-tasks (fn [handle-ui-event!]
                        (fn [old-idx new-idx]
                          (handle-ui-event! {:type :reorder-tasks
                                             :list-index icon-idx
                                             :from-index old-idx
                                             :to-index new-idx})))
    :on-edit-list-title (fn [handle-ui-event!]
                         (fn [name]
                           (handle-ui-event! {:type :rename-list
                                              :list-idx icon-idx
                                              :name name})))
    :on-edit-asset (fn [handle-ui-event!]
                     (fn [asset]
                       (handle-ui-event! {:type :edit-list-asset
                                          :list-idx icon-idx
                                          :asset asset})))
    :title name
    :tasks (mapv (partial task derived-state name icon-idx) (range) tasks)})

(def task-padding {:left 30 :bottom 0})

(def ^m/TextStyle task-text-style (m/TextStyle
                                   .color m/Colors.black
                                   .fontFamily "Inter"
                                   .fontWeight m/FontWeight.normal
                                   .fontSize 20))

(def title-style (m/TextStyle
                   .color m/Colors.black
                   .fontSize 14))
(def ^m/Offset image-destination (m/Offset 50 100))

(defn normalize-expansion-coords [{:keys [icon-coords image-coords text-coords]}]
  (if icon-coords
    {:image-origin (:position icon-coords)
     :image-size   (:size icon-coords)
     :title-origin (:position icon-coords)
     :title-size   (:size icon-coords)}
    {:image-origin (:position image-coords)
     :image-size   (:size image-coords)
     :title-origin (:position text-coords)
     :title-size   (:size text-coords)}))

(defn ast-store->widget
  ([handle-ui-event! ast-store id]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store ast-id))
         get-ast-atom #(get @ast-store id)
         {:keys [key ui-type]} @(get-ast-atom)]
     (condp = ui-type
       ::list
       (f/widget
        :context ctx
        :get [:icon-transition-controller :expanded-icon-atom]
        :let [{:keys [on-reorder-tasks on-edit-list-title title]} @(get-ast-atom)
              {:keys [notch-height phone-height phone-width]} (get-phone-measurements ctx)
              content-start (/ (+ notch-height 150) phone-height)
              {:keys [^m/ImageStream? image-stream]} @expanded-icon-atom
              {:keys [^m/Offset image-origin ^m/Size image-size
                      ^m/Offset title-origin ^m/Size title-size]} (normalize-expansion-coords @expanded-icon-atom)
              title-destination                        (.+ image-destination (m/Offset (+ (* 0.5 (.-width title-size)) 140) -20))
              log-destination                          (.+ image-destination (m/Offset 100 -30))
              curved                                   (m/CurvedAnimation .parent icon-transition-controller .curve m/Curves.easeInSine)
              t                                        (.drive curved (m/Tween .begin 0.0 .end 1.0))
              log (f/widget
                   (m/GestureDetector
                    .behavior m/HitTestBehavior.opaque
                    .onTap (fn [] (prn "log tapped")))
                   (m/Container
                    .decoration (m/BoxDecoration
                                 .border (m/Border.all .color m/Colors.red .width 2)))
                   (svg/SvgPicture.asset "assets/icons/streamline-plump--log-remix.svg"
                                          .colorFilter (m/ColorFilter.mode m/Colors.black m/BlendMode.srcIn)
                                          .width 40
                                          .height 40))]
        :managed [scroll-controller (m/ScrollController)
                  list-title-controller (m/TextEditingController .text title)]
        :watch [{:keys [tasks]} (get-ast-atom)]
        :let [title (f/widget
                     (m/Container
                      .decoration (m/BoxDecoration
                                   .border (m/Border.all .color m/Colors.red .width 2)))
                     (m/SizedBox .width 95)
                     (m/TextField
                      .keyboardType m/TextInputType.text
                      .textAlign m/TextAlign.center
                      .autocorrect false
                      .maxLines nil
                      .style title-style
                      .onSubmitted (on-edit-list-title handle-ui-event!)
                      .onChanged (on-edit-list-title handle-ui-event!)
                      .decoration (m/InputDecoration
                                   .contentPadding m/EdgeInsets.zero
                                   .isDense true
                                   .border m/InputBorder.none)
                      .controller list-title-controller))
              image (if image-stream
                      (f/widget
                       (m/GestureDetector
                        .behavior m/HitTestBehavior.opaque
                        .onTap (fn [] (prn "image tapped")))
                       (m/Container
                        .decoration (m/BoxDecoration
                                     .border (m/Border.all .color m/Colors.red .width 2))
                        .child (animated-asset image-stream 40 40)))
                      (svg/SvgPicture.asset "assets/icons/gg--add-r.svg"
                       .colorFilter (m/ColorFilter.mode m/Colors.red m/BlendMode.srcIn)
                       .width 40
                       .height 40))]
        (m/CustomScrollView
         ;; .anchor content-start
         .controller scroll-controller
         .physics (m/AlwaysScrollableScrollPhysics)
         .slivers [(m/SliverPersistentHeader
                    .pinned true
                    .delegate (reify :extends m/SliverPersistentHeaderDelegate
                                (build [this context shrink-offset overlaps-content?]
                                  (let [current-size (max (.-minExtent this) (- (.-maxExtent this) shrink-offset))
                                        percent (.clamp (/ shrink-offset 100) 0.0 1.0)
                                        scaled-title-offset (m/Offset -60 -20)
                                        scaled-log-offset (m/Offset -40 -20)
                                        scaled-image-offset (m/Offset 0 -30)
                                        scaledown (- 1.0 (/ shrink-offset (.-maxExtent this)))
                                        log-scale (max 0.8 scaledown)
                                        image-scale (max 0.5 scaledown)
                                        text-scale (max 0.8 scaledown)]
                                    (f/widget
                                     (m/Container
                                      .height current-size)
                                     (m/Stack
                                      .children
                                      [(f/widget
                                        (m/Transform.translate
                                         .offset (m/Offset.lerp log-destination (.+ log-destination scaled-log-offset) percent))
                                        (m/Transform.scale
                                         .scale log-scale)
                                        (animated-fade
                                         .controller icon-transition-controller
                                         .begin 0.8
                                         .end 1.0)
                                        log)
                                       (f/widget
                                        :watch [_ icon-transition-controller]
                                        (m/Transform.translate
                                         .offset (m/Offset.lerp (m/Offset.lerp image-origin image-destination (.-value t))
                                                                (.+ image-destination scaled-image-offset)
                                                                (* percent (.-value t))))
                                        (m/Transform.scale
                                         .scale (ui/lerpDouble 1.0 (* image-scale 3.0) (.-value t)))
                                        image)
                                       (f/widget
                                        :watch [_ icon-transition-controller]
                                        (m/Transform.translate
                                         .offset (lerp-polar-offsets (lerp-polar-offsets title-origin title-destination (.-value t))
                                                                     (.+ title-destination scaled-title-offset)
                                                                     (* percent (.-value t))))
                                        (m/Transform.scale
                                         .scale (ui/lerpDouble 1.0 (* text-scale 2.0) (.-value t)))
                                        title)]))))
                                (maxExtent [_] 180)
                                (minExtent [_] 180)
                                (shouldRebuild [_ old-delegate] false)))
                   (f/widget
                    (animated-sliver-fade
                     .controller icon-transition-controller)
                    (fade-sliver
                     .child (f/widget
                             (autoscroll-away-from-keyboard
                              .scrollController scroll-controller)
                             (m/SliverReorderableList
                              .itemBuilder (fn [_ idx] (recursive-call (nth tasks idx)))
                              .itemCount (count tasks)
                              .onReorder (on-reorder-tasks handle-ui-event!)))
                     .fadeStart 100
                     .fadeExtent 100))
                   (m/SliverToBoxAdapter
                    .child (m/SizedBox .height 400))]))

       ::task
       (f/widget
        :key key
        :let [{:keys [title]} @(get-ast-atom)]
        :managed [text-controller (m/TextEditingController .text title)] ;;we manage the text controller before the watch so that it doesn't update text focus every time the title changes.
        :watch [{:keys [completed subitems]} (get-ast-atom)]
        :let [{:keys [on-complete on-edit-task-title on-change-task-title]} @(get-ast-atom)]
        :padding task-padding
        m/Row
        .children
        [(f/widget
          :padding {:top 2}
          (m/IconButton
           .icon (m/Icon (if completed
                           m/Icons.check_box
                           m/Icons.check_box_outline_blank)
                         .size 26
                         .color m.Colors/red)
           .onPressed (on-complete handle-ui-event!)))
         (f/widget
          (m/SizedBox .width 200)
          (m/TextField
           .keyboardType m/TextInputType.text
           .autocorrect false
           .maxLines nil
           .style (.copyWith task-text-style .color (if completed m/Colors.red m/Colors.black))
           .onSubmitted (on-edit-task-title handle-ui-event!)
           .onChanged (on-change-task-title handle-ui-event!)
           .decoration (m/InputDecoration
                        .border m/InputBorder.none)
           .controller text-controller))])

       ::add-task-task
       (f/widget
        :key key
        :let [{:keys [on-add-task]} @(get-ast-atom)]
        :padding task-padding
        (m/Row)
        .children
        [(f/widget
          :padding {:top 2}
          (m/IconButton
           .icon (m/Icon m/Icons.check_box_outline_blank
                         .size 26
                         .color m/Colors.grey)
           .onPressed nil))
         (f/widget
          :managed [text-controller (m/TextEditingController)]
          (m/SizedBox .width 200)
          (m/TextField
           .style task-text-style
           .textInputAction m.TextInputAction/done
           .cursorHeight 38
           .onSubmitted (fn [new-task-title]
                          (.clear text-controller)
                          ((on-add-task handle-ui-event!) new-task-title))
           .decoration (m/InputDecoration .border m/InputBorder.none)
           .controller text-controller))])


       (throw (Exception (str "Unknown ui-type in home page todo-list ast-store->widget: " @(get-ast-atom))))))))
