(ns icare.ui.screens.pages.bookmarks.base
  (:require ["package:flutter/material.dart" :as m]
            [icare.ui.shared.paint :refer [hsv]]
            [icare.ui.shared.utils :refer [get-phone-measurements]]
            [icare.ui.shared.animations :refer [autoscroll-away-from-keyboard]]
            [cljd.flutter :as f]))

(defn bookmark [derived-state bookmark-idx bookmark]
  (let [{:keys [pub-key name notify?]} bookmark]
    {:ui-type ::bookmark
     :key pub-key
     :id (str "bookmark-" pub-key)
     :title name
     :on-edit-bookmark-title (fn [handle-ui-event!]
                               (fn [title]
                                 (if (empty? title)
                                   (handle-ui-event! {:type :delete-bookmark
                                                      :bookmark-idx bookmark-idx
                                                      :bookmark bookmark})
                                   (handle-ui-event! {:type :rename-bookmark
                                                      :bookmark-idx bookmark-idx
                                                      :title title}))))}))

(defn state->ast [db]
  (let [{:keys [derived-state state]} db
        bookmarks (-> state :bookmarks)]
    {:id "bookmarks-base"
     :ui-type ::base
     :on-reorder-bookmarks (fn [handle-ui-event!]
                             (fn [old-idx new-idx]
                                 (handle-ui-event! {:type :reorder-bookmarks
                                                    :from-index old-idx
                                                    :to-index new-idx})))
     :bookmarks (mapv (partial bookmark derived-state) (range) bookmarks)}))

(def bookmark-padding {:left 40 :bottom 30})

(defn ast-store->widget
  ([ast-store handle-ui-event!] (ast-store->widget handle-ui-event! ast-store "bookmarks-base"))
  ([handle-ui-event! ast-store id]
   (let [recursive-call (fn [ast-id]
                          ;; (prn "ast-store->widget called with ast-id: " ast-id)
                          (ast-store->widget handle-ui-event! ast-store ast-id))
         get-ast-atom #(get @ast-store id)
         {:keys [ui-type key]} @(get-ast-atom)]
     (condp = ui-type
       ::base
       (f/widget
        :keep-alive true
        :context ctx
        :let [{:keys [notch-height phone-height phone-width]} (get-phone-measurements ctx)
              content-start (/ (+ notch-height 40) phone-height)]
        :managed [scroll-controller (m/ScrollController)]
        :let [{:keys [on-reorder-bookmarks]} @(get-ast-atom)]
        :watch [{:keys [bookmarks]} (get-ast-atom)]
        (autoscroll-away-from-keyboard
         .scrollController scroll-controller)
        (m/ReorderableListView
         ;; .itemBuilder (fn [_ idx] (recursive-call (nth tasks idx)))
         ;; .itemCount (count tasks)
         .physics (m/AlwaysScrollableScrollPhysics)
         .children (mapv recursive-call bookmarks)
         .onReorder (on-reorder-bookmarks handle-ui-event!)
         .anchor content-start
         .scrollController scroll-controller
         .footer (m/SizedBox .height 400)))

       ::bookmark
       (f/widget
        :key key
        :watch [{:keys [title]} (get-ast-atom)]
        :managed [text-controller (m/TextEditingController .text title)]
        :let [{:keys [on-edit-bookmark-title]} @(get-ast-atom)]
        :padding bookmark-padding
        (m/TextField
         .keyboardType m/TextInputType.text
         .autocorrect false
         .maxLines nil
         .style (m/TextStyle
                 .color m/Colors.black
                 .fontFamily "Inter"
                 .fontWeight m/FontWeight.normal
                 .fontSize 20)
         .onSubmitted (on-edit-bookmark-title handle-ui-event!)
         .decoration (m/InputDecoration
                      .border m/InputBorder.none)
         .controller text-controller))

       (throw (Exception (str "Unknown ui-type in todo-list ast-store->widget: " @(get-ast-atom))))))))
